### ISSUE TITLE
`test_sra_not_signed` from golem's concent acceptance tests is failing

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#1000]
to reproduce:
`pytest scripts/concent_acceptance_tests/force_payment/test_payment.py::RequestorDoesntPayTestCase::test_sra_not_signed` on branch `chore-update-concent-acceptance-test-after-sra-update` (GM v2.17.0)

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162449556
