### ISSUE TITLE
The settlement algorithm does not do forced subtask payment matching

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#1005]
As explained in the #996 blueprint, Concent should only take a forced subtask payment into account if the provider has submitted an acceptance with matching subtask ID. Otherwise it should not include its value in `LF`.

This was confirmed yesterday by @lukasz-glen:
> Do payment matchingu bierze się tylko `ReimburseForNoPayment`.
> `ReimburseForSubtask` wykonywane są tylko dla subtasków, które nie dostaną SRA. W przypadku dodatkowej weryfikacji i negatywnej ścieżki UC3.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162505371

**Comment by cameel** [comment]
Since it turned out that `LF` is supposed to contain settlement payments, not forced subtask payments, we do not need payment matching. Concent never really checks those payments. I'm closing this issue.
