### ISSUE TITLE
The settlement algorithm does not accept acceptances signed by Concent

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#1006]
As explained in the #996 blueprint, the provider must be able to submit acceptances signed not only by the requestor but also by Concent. Otherwise he won't be able to prove that he performed the work paid by forced subtask payments and Concent will count those payments towards other subtasks which is wrong.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162505388

**Comment by cameel** [comment]
Probably. But please give me some time to update the spec and issues. I don't want to confirm anything until I get a clear picture of the situation.

**Comment by cameel** [comment]
I'm closing it. Concent does not issue acceptances in UC3 and UC4 after all. It's not necessary because UC5 is not supposed to take forced subtask payments into account as I previously thought.
