### ISSUE TITLE
Preventing multiple settlement payments for the same subtasks

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#1009]
This task depends on #1017.

In #984 we have implemented a mechanism that checks if Concent has already issued a settlement payment and prevents the acceptances covered in that settlement from being submitted again. This mechanism has a critical flaw: the settlement payment may not be visible on the blockchain for several minutes or more because blockchain transactions are not instant. This gives the provider plenty of time to call Concent again and force another payment for the same subtasks.

(EDIT: Even though we're going to revert #984 the point still stands: if the provider runs UC5 multiple times, he should not be paid multiple times for the same thing. If the first run covered only 50% of what he was owed (due to not enough deposit), the next run should see the forced payment and cover no more than the other 50%.)

Fortunately Concent can know that it has issued a payment because this information is stored inside `DatabaseClaim`s created by Bankster.

Modify the implementation of UC5 so that:
1. It finds all `DatabaseClaims` that represent settlement payments from requestor's Ethereum account to provider's Ethereum account and for which a transaction has already been sent to the Ethereum client. It creates a list of those transactions.
2. It gets the list of settlement payments from the blockchain
3. It finds transactions that are on both lists and removes them from the list of transactions found in claims.
    - It compares the duplicates and if the information in the database (e.g. the amount or `closure_time`) differs from the information on the blockchain, aborts the settlement and responds with HTTP 500. This should never happen in practice and if it does, we want to get a report and fix the problem.
4. It uses both lists when checking existing settlement payments.

When the task is done, please drop me a note in #996 because the specification will need to be updated.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162732368

**Comment by cameel** [comment]
I started wondering if we should maybe take into account claims that are not yet finalized (i.e. do not have a transaction). But I think ignoring them is better. Below is my rationale in case anyone is interested. I think it would be a good idea to create a test case for this.

Let's assume that requestor's deposit is 100 GNT, there's an unfinalized claim from UC3 for 50 GNT and the provider starts UC5 because he's not been paid 100 GNT for a different subtask.
1) If we take unfinalized claims into account
    1) If the claim from UC3 eventually gets finalized, provider gets 50 GNT in UC5 and 50 GNT in UC3. 100 GNT total.
    2) If the claim from UC3 eventually gets removed, provider gets 50 GNT in UC5 and 0 GNT in UC3. 50 GNT total.
2) If we don't take unfinalized claims into account
    1) If the claim from UC3 eventually gets finalized, provider gets 100 GNT in UC5 and 0 GNT in UC3 (`finalize_payment()` decreases UC3 payment to 0). 100 GNT total
    2) If the claim from UC3 eventually gets removed, provider gets 100 GNT in UC5 and 0 GNT in UC3. 100 GNT total.

So including them could decrease provider's payout in some cases.

The only potential downside of not including them is that in case of not enough deposit provider can run UC5 gain if he sees that the requestor has replenished the deposit. That's not possible in UC3 and UC4. So in case 1.ii. the provider still has a slim chance of getting the 50 GNT from UC5 back. He has no such chance in case of 50 GNT from UC3 in 2.i.
