### ISSUE TITLE
Sharing MessageAuth between all messages related to a single task

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#101]
As implemented in #16 each `Message` in the database has is own `MessageAuth` object (see https://github.com/golemfactory/concent/pull/29/files#r166491902). There's a 1:1 relationship between them.

This is not how the feature is supposed to work. Provider and requestor keys are supposed to be stored once, when the task is first submitted and later used in all the subsequent communication.

The current implementation works around this by ignoring `MessageAuth` associated with any message other than the `Force...` message that starts the processing of a task.

This has to be fixed soon because it won't be easy to migrate this once we go to production.

**Comment by cameel** [comment]
This task is obsolete now. The issue will be fixed by #142.

**Comment by cameel** [comment]
@rwrzesien Please close this if #142 is done.

**Comment by rwrzesien** [comment]
@cameel Closing.
