### ISSUE TITLE
`test_requestor_has_no_funds` acceptance test is failing 

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#1011]
Expected response from Concent is: `ServiceRefused` with reason `TooSmallRequestorDeposit`.

Actual response: `ForcePaymentRejected` with reason `NoUnsettledTasksFound`
To reproduce:
`pytest scripts/concent_acceptance_tests/force_payment/test_payment.py::RequestorDoesntPayTestCase::test_requestor_has_no_funds` on branch `chore-update-concent-acceptance-test-after-sra-update` (GM v2.17.0)

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162603467
