### ISSUE TITLE
Confusing names in sci_backend

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#1018]
Names in our `core.payments.backends.sci_backend` module may be confusing for someone who has read the #996 blueprint. Please change them to make the code easier to understand:
1) `make_force_payment_to_provider()` should be called `make_settlement_payment()`.
    - Also, if you see any comments or variables referring to "forced payments" (but watch out for "forced subtask payments" - it's not the same thing), it would be a good idea to change them too. It's too easy to confuse "forced payment" and "forced subtask payment". "Settlement payment" is a less ambiguous name for the former. Don't spend too much time on it though. Our main goal is changing the public names visible in `sci_backend.py`.
2) `make_force_payment_to_provider()` has a parameter called `payment_ts`. It should be called `closure_time` because it's used as the value for `closure_time` in the payment. Calling it `payment_ts` makes it too easy to confuse it with `SubtaskResultsAccepted.payment_ts` because they're often used in the same context.
3) `get_list_of_payments()` has a parameter called `payment_ts`. It would be better to call it `min_block_timestamp` because it has absolutely nothing to do with `payment_ts` in `SubtaskResultsAccepted` or `ForcePaymentCommitted`. They cannot even be compared directly.
4) `call_on_confirmed_transaction()` is a weird name for a callback. It's telling the programmer what he is supposed to do with it instead of telling it what it does. I'd call it `confirmed_transaction_callback()` or `confirmed_transaction_handler()`.
    - EDIT: After looking at it again, I see that I was wrong about what this function does (which only confirms that the current name is not good). It's the other function it gets as a parameter that gets called, not this function itself. In that case I think that `on_confirmed_transaction()` or `register_confirmed_transaction_handler()` would be better.

These names should be adjusted to avoid potential bugs caused by wrong interpretation of the code.

Please consider renaming badly named functions, parameters and variables also in other parts of our payment system  if you notice any (see for example https://github.com/golemfactory/concent/pull/1043#discussion_r243700491). Misleading or out of date names make the code harder to understand.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162632122
