### ISSUE TITLE
[Sentry] 'Ensure this value is less than or equal to 2147483647.'

### ISSUE THREAD

**Issue by Jakub89** [golemfactory/concent#1023]
https://talkback.golem.network/sentry/concent/issues/44675/

Default for django `IntegerField()` is 4-bytes value. We can replace it with django `BigIntegerField()` where we can store value up to "9223372036854775807", but it still might not be enough if someone decide to make a deposit for millions of GNT. @cameel ? @rwrzesien ? @dybi ?

**Comment by rwrzesien** [comment]
Can be `DecimalField(max_digits=78, decimal_places=0)` .

**Comment by cameel** [comment]
Yeah, it should be the same type we use in our transaction storage. I now don't 100% remember if we ended up using `Decimal` but if so, we can use it here too.

This applies to any other places where we're storing GNT or ETH amounts. If you're aware of any (please look through our models to be sure), they need to be fixed too.

**Comment by PaweuB** [comment]
Yes, it is in Pivotal since yesterday and @Jakub89 is assigned for this since yesterday (-; 

https://www.pivotaltracker.com/story/show/16264040
