### ISSUE TITLE
Bankster: Guard against passing the same claim twice to finalize_payment()

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#1024]
Currently `finalize_payment()` does not check if the `DepositClaim` passed to it has `tx_hash` filled out or not. If it's filled out it will be ignored and overwritten.

This does not matter as long as Concent is using it correctly but I think we need at least a sanity check (`assert`) for that case.

Since Bankster is an internal API, it's also fine to use a normal `if` and raise an exception. But in that case you should replace other sanity checks with validatios too: for example the check that the use case is either UC3 or UC4 is now enforced with an assertion.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/162732447
