### ISSUE TITLE
Nonce does not get incremented if `settle_overdue_acceptances()` fails after the payment

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#1037]
We have encountered a situation in which `settle_overdue_acceptances()` fails due to a validation error when it's trying to save a `DepositClaim` and this makes `DatabaseTransactionStorage`'s changes to `GlobalTransactionState.nonce` disappear. In our case the next transaction after the failure still tried to use the same nonce.

Please try to reproduce this situation and fix the problem. It's serious because a situation like this blocks any subsequent transactions in Concent and requires a manual intervention from the admin to fix.

### Logs
```
2018-12-17 20:17:23.000 CET 19:17:23 INFO | requestor_payable_amount is 163888888888888889 for ethereum address 0x87014585C67b299bc1382C310f2726E434EeDe57.
2018-12-17 20:17:23.000 CET 19:17:23 INFO | Saving transaction 0x68128afae79285f7e5e126afdc1f0400335be27701807cadc45cd62324090b19, nonce=83
2018-12-17 20:17:23.000 CET 19:17:23 ERROR | Internal Server Error: /api/v1/send/
(...)
2018-12-18 09:04:53.000 CET 08:04:53 INFO | requestor_payable_amount is 163888888888888889 for ethereum address 0x8c922584747aC02F887105A5021590CC0515D2c5.
2018-12-18 09:04:53.000 CET 08:04:53 INFO | Saving transaction 0x54cd9ce53943c67e3c189ea21a9f1c29d5447a224e32827411c0a8a45300a050, nonce=83
2018-12-18 09:04:53.000 CET 08:04:53 CRITICAL | web3 JSON rpc critical error ValueError({'code': -32000, 'message': 'nonce too low'},)
2018-12-18 09:04:53.000 CET 08:04:53 INFO | Successfully reverted last PendingEthereumTransaction with nonce 83.
2018-12-18 09:04:53.000 CET 08:04:53 ERROR | Internal Server Error: /api/v1/send/
```

The validation error was at 20:17 (it was the problem reported in #1034). `Saving transaction ...` indicates that `DatabaseTransactionStorage.set_nonce_sign_and_save_tx()` called from SCI has successfully created a transaction and increased the nonce to 83.

Then at 8:04 Concent tried to make another transaction, which failed due to `nonce too low` which indicates that the previous transaction was indeed published on the blockchain but Concent's nonce counter was not increased.

There were no other transactions between the two, so that part of the logs is omitted. Note that there was no `Successfully reverted last ...` between them which indicates that the nonce was not lowered on purpose. It must have been rolled back. This could have happened if the database transaction `set_nonce_sign_and_save_tx()` is wrapped in was actually nested in another transaction and converted to a savepoint by Django. It should not be possible since @rwrzesien reported during his implementation of #937 that we have no nested transactions.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/162728443

**Comment by dybi** [comment]
Ok, I guess I have found the problem... 
in `settle_overdue_acceptances()`:
```python
with transaction.atomic(using='control'):
  #...
  transaction_hash = service.make_force_payment_to_provider(  # pylint: disable=no-value-for-parameter
            requestor_eth_address=requestor_ethereum_address,
            provider_eth_address=provider_ethereum_address,
            value=requestor_payable_amount,
            payment_ts=youngest_payment_ts,
        )
```
Then, in `make_force_payment_to_provider()`:
```python
return PaymentInterface().force_payment(  # type: ignore  # pylint: disable=no-member
        requestor_address   = Web3.toChecksumAddress(requestor_eth_address),
        provider_address    = Web3.toChecksumAddress(provider_eth_address),
        value               = value,
        closure_time        = payment_ts,
    )
```
Then, in `force_payment()` we call `_create_and_send_transaction()` which calls `_sign_and_send_transaction()` which calls `_storage.set_nonce_sign_and_save_tx(self._tx_sign, tx)` from `DatabaseTransactionsStorage`:
```python
@transaction.atomic(using='control')
    def set_nonce_sign_and_save_tx(
        self,
        sign_tx: Callable[[Transaction], None],
        tx: Transaction
    ) -> None:
```
The last function is wrapped in transaction as well, co it makes a checkpoint. If validation of `DepositClaim` fails for whatever reason - setting `nonce` will be rollbacked as well.

@cameel - suggestions?

**Comment by cameel** [comment]
So that's what I suspected. In that case we need to change the way transactions are run. `settle_overdue_acceptances()` must make sure it makes payment after it commits its own transaction. It should:
1) Create a `DespositClaim` without `tx_hash` in the transaction that holds a lock on the `DepositAccount`.
2) Commit the transaction.
3) Make payment with `make_force_payment_to_provider()`.
4) Update `DepositClaim` in a separate transaction (a lock is not necessary).
5) Commit the new transaction.

Also, we need to make sure that the same problem does not exist in `finalize_payment()`. It should be issuing the payment outside of its transaction.

**Comment by cameel** [comment]
As always there's the problem of "what happens if the payment fails". If step 3 raises an exception, we're left with a `DepositClaim` that will never be associated with a transaction or removed.

We could try to do limit the damage, e.g. by catching the exception, removing the claim and reraising - but you can't really be sure if the transaction was actually created or not. The failure may have occurred after the transaction has already been passed to the blockchain client. If we delete the claim we lose the information that we could later use to find the transaction on the blockchain.

This is not something that can be dealt with locally anyway. We can't assume that the `except` or `finally` blocks will always run because there's always some risk that the container or process is simply killed during step 3, without any way to clean up after itself. Making it 100% reliable requires a periodic cleanup task.

This periodic taks is out of scope of this issue. I think that leaving the unfinished claim in the database is the best we can do at the moment. At least it will let us spot the problem in the admin panel and deal with it manually if it's a really important transaction.
