### ISSUE TITLE
Missing check for version of nested messages during handling messages from database 

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#1051]
Quote from https://github.com/golemfactory/concent/issues/857 blueprint:

> receive/ endpoint
> Since Concent creates responses on the fly, the client will always get a response containing a message created with Concent's version of golem-messages. Client can see this version in the Concent-Golem-Messages-Version HTTP header on the response.
> 
> If the response needs to contain a nested message taken from the database and that message is not compatible with Concent's version of golem-messages, Concent responds with ServiceRefused. The client is always required to stay on the same protocol version while communicating about the same subtask.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163020955

**Comment by cameel** [comment]
Update: we'll respond with HTTP 404 if versions are not compatible.
