### ISSUE TITLE
get_or_create_with_retry() will not be able to handle all IntegrityErrors it's supposed to

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#1056]
The issue originates from comment: https://github.com/golemfactory/concent/pull/1041#pullrequestreview-187567211

EDIT by @cameel:
"Get or create" operations implemented at the application level always have an inherent race condition. They need to check if the object exists and then either fetch or create it - but there's a short time gap between the check and the creation. Another process running in parallel can insert the row in that time. This is not merely a theoretical problem: see for example #486.

When this happens, the create operation in the first process fails with `IntegrityError` (`pgcode`: `UNIQUE_VIOLATION`) due to non-unique primary key. It's safe to deal with it by simply retrying the operation. #1041/#1042 introduced `get_or_create_with_retry()` which is a wrapper over Django's `get_or_create()` which does just that.

The problem with the wrapper is that it does not commit its changes to the database. This means that when it's called within an `@atomic` block, the `IntegrityError` may be raised at the end of that block when the transaction is committed - i.e. outside of the `try`/`except` block. This is because at the default transaction isolation level used by Django (`READ COMMITTED`) the processes do not see each other's changes until commit and the database won't detect a conflict until that point. As a result the `IntegrityError` will not be caught by the wrapper.

The simplest way to fix the wrapper is to put the body of the `try` block in an `@atomic` block.

This caused some controversy in https://github.com/golemfactory/concent/pull/1041#pullrequestreview-187567211 so please try to reproduce such a situation and report your findings in comments. It would actually be best to have a test instead but unit tests that test stuff related to transactions are often tricky - so it's enough to modify code locally to cause a situation in which there's an `IntegrityError` on commit and make sure that it can happen and that the fix works.

Also, while at it, please replace `get_or_create()` in the `except` block with just a simple `get()`. If the first create failed, it's pointless to try to create it again. This will save us one database query.

**Comment by PaweuB** [comment]
Please provide more information about Issue. 
Is it critical?

**Comment by cameel** [comment]
@PaweuB I have added a proper description.
