### ISSUE TITLE
Change `ZERO_SIGNATURE` to factory method `sign__privkey()` 

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#1058]
Now in tests we init messages signature using `fake_sig()`:

```python
report_computed_task = factories.tasks.ReportComputedTaskFactory(
        sig=ZERO_SIGNATURE,
        task_to_compute=task_to_compute,
    )
```

Factories from Golem Messages contains method to signing messages during it initialization. All places where `ZERO_SIGNATURE` is used should be changed to:
```python
report_computed_task = factories.tasks.ReportComputedTaskFactory(
        sign__privkey=PROVIDER_PRIVATE_KEY,
        task_to_compute=task_to_compute,
    )

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/163115199
