### ISSUE TITLE
api-e2e-force-accept-or-reject-results-test.py case 2a is not complete

### ISSUE THREAD

**Issue by Jakub89** [golemfactory/concent#1062]
Issue happen  when trying to deploy concent on cluster. CI block deployment because script that runs all e2e tests fails, because `api-e2e-force-accept-or-reject-results-test.py` creates unresolved  `DepositClaim` that effect the outcome of `api-e2e-force-payment.py`.

**Comment by rwrzesien** [comment]
@Jakub89 Could you please provide more info about the effect? Does it block some amount of the deposit?

**Comment by Jakub89** [comment]
@rwrzesien Yes, when we have unresolved DepositClaim(), it's being add to sum of payments in `force-payment` test. So the bug is just wrong(other then we expect) value that's being claimed from requestor.
