### ISSUE TITLE
Reverse order of validations in force payment handler.

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#1076]
Original Sentry issue: https://talkback.golem.network/sentry/concent/issues/40709/

It happened that `subtask_results_accepted` in `subtask_results_accepted_list` list has no `task_to_compute`. We should first call `validate_task_to_compute` before calling `are_keys_and_addresses_unique_in_message_subtask_results_accepted`. Currently both of those are called, but in reverse order.

After fixing this please resolve Sentry issue.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/163362084

**Comment by cameel** [comment]
@rwrzesien
> After fixing this please resolve Sentry issue.

Our workflow is to mark a Sentry report resolved as soon as you create an issue for it. We don't need it open in Sentry because we don't use it for tracking tasks. Only unresolved issues in Sentry should be the fresh ones where no one has decided whether to report or close them yet.

**Comment by rwrzesien** [comment]
After examining this further, it looks like the issue is already resolved in golem-messages, so I am closing this as resolved.
