### ISSUE TITLE
`ConcentNodeTest::test_force_accept` in `/node_integration_tests/tests/test_concent.py` fails and rises `premature: still within the verification timeout`

### ISSUE THREAD

**Issue by PaweuB** [golemfactory/concent#1095]
This Issue is reported from Golem Factory (@shadeofblue) and should be reproduced from Concent Node Integration Tests in:

```/scripts/node_integration_tests/tests/test_concent.py::ConcentNodeTest::test_force_accept```

This test fails and raises reason:

`premature: still within the verification timeout`

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163621653

**Comment by dybi** [comment]
seems it has been fixed in `golem`
