### ISSUE TITLE
`OperationalError` could not connect to server: Connection refused 

### ISSUE THREAD

**Issue by PaweuB** [golemfactory/concent#1101]
Sentry rises exception in environment: concent-testnet.
Please investigate and resolve exception due to our workflow. 

```
OperationalError
could not connect to server: Connection refused
	Is the server running on host "35.198.142.52" and accepting
	TCP/IP connections on port 5432?
```

More details specified as provided below:
https://talkback.golem.network/share/issue/5f7c93415fca465abc0afcc76d15496f/

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163861686

**Comment by kbeker** [comment]
Problem is not related with our machines. Most likely, this is a problem related to the temporary unavailability of the database service (from what is seen in the exception of sentry is about 2 minutes). We are closing it now. If the problem repeats in future then we will pay attention to it.
