### ISSUE TITLE
Test Concent behavior when Geth is out of sync

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#1103]
We need to make sure that Concent does not hang and time out when Geth is out of sync. @bartoszbetka reports that it does happen now. This might be caused by our readiness probe, which is going to be removed in https://github.com/golemfactory/concent-deployment/issues/341.

After #1077 Concent should be able to detect desynchronizations on its own so the probe is not necessary.

When the probe is removed, test the code on a cluster by making a request to the API while Geth is out of sync. The request should either succeed or result in an error. It should not hang for a long period of time or return an empty response (which would indicate that the server has closed the connection on its side).

**Comment by dybi** [comment]
works!
