### ISSUE TITLE
New messages from client which already used Concent Service on older GM version are rejected

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#1104]
Currently, when Concent had Golem Messages in version e.g. `2.15.0` and the client used his service, then every new message which will be sent by the same client in newer Golem Messages version will be rejected because of messages which were send on GM `2.15.0` and are stored in database. This need to be fixed.

**Comment by cameel** [comment]
I think each client should only see messages compatible with its own version.

One small problem is that it's a bit misleading to tell the client that there are no more messages to receive when there are messages meant for other versions. We could indicate it with a HTTP header (e.g. `Concent-Incompatible-Messages-Available: 0.2.13`). I doubt a Golem client will ever use this so it's optional to implement but in my opinion a good, complete and friendly API should have some way to discover that fact.

**Comment by dybi** [comment]
not valid anymore - it has been agreed that msg flow connected with one `subtask_id` must happen using one version of golem messages; if client updated "in the meantime", it's taking all the risk
