### ISSUE TITLE
"Requestor does not pay for computation" use case: Script for testing on a real cluster

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#121]
There should be added test script, which will test full functionality of "Requestor does not pay for computation" use case. This test should follow our current convention of cluster tests.

We will have option to set a custom backend in django settings, so we can either reuse test backend written in https://github.com/golemfactory/concent/issues/120 or create a separate backend for cluster tests or use real backend using golem-smart-contracts-interface with some sandbox data.

Each of test cases should cover one of 2A, 2B, 2C, and 2D cases, use requests and check for responses described in https://github.com/golemfactory/concent/issues/116.

- Case 2A
```
Provider  -> Concent:   ForcePayment
Concent   -> Provider:  ServiceRefused (with reason "INVALID_REQUEST")
```

- Case 2B
```
Provider  -> Concent:   ForcePayment
Concent   -> Provider:  TIMESTAMP_ERROR (with reason "WRONG_PAYMENT_TIME")
```

- Case 2C
```
Provider  -> Concent:   ForcePayment
Concent   -> Provider:  ForcePaymentRejected (with reason "NO_UNSETTLED_TASKS_FOUND")
```

- Case 2D
```
Provider  -> Concent:   ForcePayment
Concent   -> Provider:  ForcePaymentCommitted
Concent   -> Requestor: ForcePaymentCommitted (out of band)
```

**Comment by Jakub89** [comment]
Closing via #157
