### ISSUE TITLE
Header with Concent version on all HTTP responses

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#126]
Add a header containing Concent version to all HTTP responses from Concent API. Call it `Concent-Version`.

Version should come from a git tag but not directly. Create a script that will store this version in a text file. The server should not use git but read the file instead. Running the script and creating the file will be part of our deployment. Version file should be listed in `.gitignore` to avoid committing it to the repo by accident.

Make sure version comes from a tag on the repository the code is located in. I.e. `concent` and not `concent-deployment`.

**Comment by jiivan** [comment]
Here's and example what we is used in golem core and golem-messages to get a version from git tag: https://gist.github.com/jiivan/cd7f12200f34cfe3fa5ec8c9da8d98c0
