### ISSUE TITLE
ForceReportComputedTask should contain ReportComputedTask in cluster tests

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#129]
After update golem_message to v1.9.0 `MessageForceReportComputedTask` is wrapper for `MessageReportComputedTask`. It should be changed in `api-integration-force-report-computed-task-task.py'`, because for this moment it only contain `MessageTaskToCompute` as it was in versions before v1.9.0. Example of MessageForceReportComputedTask: 
  ``` python
    {
        'timestamp':            1510401120,     # 2017-11-11 14:52
        'report_computed_task':     # ReportComputedTask
            {
                'timestamp': 1510401000,     # 2017-11-11 14:52
                'task_to_compute':   {               # TaskToCompute
                    'timestamp': 1510390800,    # 2017-11-11 10:00
                    'compute_task_def': {
                        'task_id':   '2',
                        'deadline':  1510394400,    # 2017-11-11 11:00
                    },
                },
        },
    }

**Comment by cameel** [comment]
By the way, stuff like this should normally be fixed as a part of the update to the next version. Testing scripts should not be left broken after the update.

**Comment by rwrzesien** [comment]
Closed and merged.
