### ISSUE TITLE
Logic for requests for 'Get Task Result' use case in views

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#13]
Add support for the message exchange defined in #12.

General guidelines:
* In first version we don't want to check if files were upload on Nginx Cluster, it will be done in https://github.com/golemfactory/concent/issues/26.
* Make handling of each message type in separate function, like:
```
if message_type == "Message1":
    handle_message1()
elif message_type == "Message2":
    handle_message2()
```
etc.
* If there will be a piece of code (like several calls in same order, but might be with different parameters) that is repeating, move it to separate parameterized funcion.
* Do the basic logic first, then add identifying by key.
* Cases 1,2,3 are very similar to what was for ForceReportComputedTask case, most of the logic can be reused.
* Cases 4a, 4b, 4c, 4d are those which are checking upload on NginxCluster.
* Cluster address should be taken from settings, which will define a list of available addresses. For now I think it should be ok to get just random entry from that list. In the future we might change it to be a model, store addresses along with pending requests count, and query for less used cluster at the moment, which would imitate load balancing.
* subtask_id will be received in ForceGetTaskResult according to #12, this message will be stored in database, so we can use subtask_id in requests to storage cluster.

Probably no changes in models will be needed for this issue. However, following objects should be created on each case:

* Step 1 + 2C: Requestor forces getting task results via Concent and concent acknowledges requestor's request:
** Message object with ForceGetTaskResultUpload data.
** MessageAuth objects with used keys for created Message.
** ReceiveStatus for receive for created Message.

* Step 1+ 2A: Requestor forces getting task results via Concent and Concent rejects requestor's request immediately if requestor has already initiated getting task results:
** No new objects created here.

* Step 1+ 2B: Requestor forces getting task results via Concent and Concent rejects requestor's request immediately if the time for downloading results is already up:
** No new objects created here.

* Step 3: Concent requests task results from the provider:
** Marks Messages from step 1 + 2C as delivered.
** Message object with ForceGetTaskResultUpload data.
** MessageAuth objects with used keys for created Message.
** ReceiveStatus for receive for each created Message.

* Step 4A: Concent reports a failure to get task results if the provider does not submit anything:
** Message object with ForceGetTaskResultFailed data.
** MessageAuth object with used keys for created Message..
** ReceiveStatus for created Message.

* Step 4B: Concent reports a failure to get task results if it is unable to get the files from the provider before the time is up:
** Message object with ForceGetTaskResultFailed data.
** MessageAuth object with used keys for created Message..
** ReceiveStatus for created Message.

* Step 4C: Concent reports a failure to get task results if it the files submitted by the provider are bad or incomplete:
** Message object with ForceGetTaskResultFailed data.
** MessageAuth object with used keys for created Message..
** ReceiveStatus for created Message.

* Step 4D: Concent notifies the provider that task results are ready to be downloaded:
** Message object with ForceGetTaskResultUpload data.
** MessageAuth object with used keys for created Message..
** ReceiveStatus for created Message.

**Comment by cameel** [comment]
Actually I think I'll have to split this one into several smaller tasks. Update soon.

**Comment by rwrzesien** [comment]
@cameel Please review, I am not sure if messages created in 4A, 4B, 4C and 4D should be created there or as dynamic messages in 3.

**Comment by cameel** [comment]
> I am not sure if messages created in 4A, 4B, 4C and 4D should be created there or as dynamic messages in 3.

Dynamic because Concent does not do anything until the requestor calls `receive/`. You can't put them in queue ahead of time.

**Comment by cameel** [comment]
You should add more info on how the tokens are generated:
- What goes into `subtask_id`.
- How are file paths generated.
- Where does the address of the storage cluster come from.

**Comment by cameel** [comment]
Also, you're not creating status objects in 4A-4D so the messages won't be delivered.

**Comment by rwrzesien** [comment]
@cameel 
- I have added info about status objects in 4A-4D.
- About subtask_id, I think it should be id of TaskToCompute, is that correct ? It is just in request body of ForceGetTaskResult, so where should I mention it ?
- About the storage cluster address, I have read the docs and couldn't find this information. Would it be in settings ?
- About file paths, don't they come from gatekeeper ?

**Comment by cameel** [comment]
> About subtask_id, I think it should be id of TaskToCompute, is that correct ? It is just in request body of ForceGetTaskResult, so where should I mention it ?

I'm not sure if `TaskToCompute` contains `subtask_id` or `task_id`. Please check.

Even if it's in `ForceGetTaskResult` we still want it in the token so that we can log the ID on the storage cluster. Łukasz requested it today: https://github.com/golemfactory/golem-messages/issues/75

> About the storage cluster address, I have read the docs and couldn't find this information. Would it be in settings ?

That's the catch :) It's not in the spec. It's an implementation detail that's up to you. If I wanted to write the spec down to every little detail, it would take as much time as implementing it. That's why I wanted you to carefully think through the implementation and make the small decisions that do not require my input and ask about stuff that isn't obvious.

About this particular issue - please propose something. Keep in mind that there are going to be multiple storage clusters connected to a single control cluster.

> About file paths, don't they come from gatekeeper ?

No. Concent API decides the paths and puts them in the token. Gatekeeper only verifies that the token has been signed by Concent API and, if so, allows upload.

**Comment by rwrzesien** [comment]
> I'm not sure if TaskToCompute contains subtask_id or task_id. Please check.
subtask_id is in ComputeTaskDef, which is in TaskToCompute, but what I have meant is that we will receive it in `ForceGetTaskResult` according to https://github.com/golemfactory/concent/issues/12. And we will store this message so we can use subtask_id in requests to storage cluster.

**Comment by cameel** [comment]
> subtask_id is in ComputeTaskDef, which is in TaskToCompute, but what I have meant is that we will receive it in `ForceGetTaskResult` according to https://github.com/golemfactory/concent/issues/12. And we will store this message so we can use subtask_id in requests to storage cluster.

I'm not sure I understand what you mean. Are you stating a fact or asking me a question? What is the question?

> >  No. Concent API decides the paths and puts them in the token. Gatekeeper only verifies that the token has been signed by Concent API and, if so, allows upload.

> But are we implementing upload in this use case ?

We're implementing the code that generates the token which allows the client to upload. The upload itself is already implemented (gatekeeper, storage cluster, etc.)

**Comment by rwrzesien** [comment]
> I'm not sure I understand what you mean. Are you just stating a fact or asking me a question? What is the question?

I am just writing how I think subtask_id should be handled, it will come in ForceGetTaskResult message, message will be stored in database, and for future requests in this operation we will use it from stored message.

**Comment by cameel** [comment]
OK. Please add that to the description.

**Comment by rwrzesien** [comment]
Updated info about replacing TaskResultHash with ForceGetTaskResultUpload.

**Comment by rwrzesien** [comment]
@cameel This one is totally outdated, we don't use most of the models described here, but the use case was implemented using those general guidelines. In other words, it was done this way at some point of time, but currently works differently as it was changes in other issues, so I am closing this one.
