### ISSUE TITLE
Machine-readable codes in JSON error messages

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#131]
Currently our JSON error messages only contain human-readable strings describing the issue. The only thing the client can do with such a string is to show it to the user. The messages are not stable enough to rely on them. They can change between versions without notice. Even worse if we ever enable translations. Messages can also contain embedded values from the request which would require the client to parse them according to some pattern making identifying specific errors even more complex. We have this issue even in our tests where we can't reliably test why the request fails - only that it does fail.

Update all JSON error responses to contain the following fields:
- `error_message`
- `error_code`

Example
``` json
{
    "error_message": "-123 is not a valid timestamp. Timestamp cannot be negative",
    "error_code":    "negative-timestamp"
}
```

Error codes can be arbitrary, unique strings. They should be granular enough for the client to be able to discern every important case but not so granular that every instance of an error has a different code.

We can come up with them ad-hoc but if you can suggest a sensible hierarchy that's even better. Maybe it would make sense to use lists of strings or dotted names instead of a single string. E.g. `["gatekeeper", "validation.checksum", "not-a-sha1-hash"]` or `"gatekeeper.validation.checksum.not-a-sha1-hash"`.

**Comment by rwrzesien** [comment]
I suggest adding those codes as constants, as they will be repeatable along the code.
