### ISSUE TITLE
Concent should use subtask_id, not task_id to identify subtasks

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#137]
`TaskToCompute` represents a subtask and `subtask_id` (not `task_id`) is its unique identifier.

- Use `subtask_id` to identify subtasks in the database. It should be unique.
    - Validate that all the subtasks with the same `task_id` have the same requestor.
    - Update all queries that currently refer to `task_id`.
- Add `subtask_id` validation to our message validations in the views.
- When logging information about a subtask, always include both `task_id` and `subtask_id`.
- If we have any names or text referring to tasks, change it to make it clear that we mean subtasks.
- Update all tests.

**Comment by cameel** [comment]
Is this task done?

**Comment by cameel** [comment]
@rwrzesien What about this task?

**Comment by rwrzesien** [comment]
@cameel Resolved in https://github.com/golemfactory/concent/pull/158 and https://github.com/golemfactory/concent/pull/162, apart from 

> When logging information about a subtask, always include both task_id and subtask_id.

It is missing in few places in logging, so I will create a separate issue for it and I am closing this one.
