### ISSUE TITLE
Don't clear message signatures when storing them in the database

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#145]
The current code ofen does something like this before storing a message in the database:
``` python
message.sig = None
```

This means that we're removing the original signature from the message. This should not be happening for messages submitted by clients. We won't be able to verify their authenticity later. And for messages created by Concent it should not be necessary at all.

Investigate all such cases and remove them from the code if possible. Each one that remains must have a very good reason to remain.

**Comment by cameel** [comment]
@rwrzesien Let's keep discussions on what the best solution is out of pull requests. Reviews cause so much noise that it's hard to discuss anything that's not related to a particular line of code there.

> This is just a fix proposal. The original issue is caused when `.serialize()` method is called on message, and no `sign_func` parameter is provided, method is calling `_fake_sign` to set the `.sig` to:
>
> ```
> def _fake_sign(_):
>     return b'\0' * Message.SIG_LEN
> ```
>
> Which cause issues on loading that message. 
>
> In my solution we don't need to worry and remember about clearing this overwritten signature, but we still, on few occasions, store messages with this overwritten signature in database (when there is no original signature, so when the message was created by concent). However, there is no harm because we never send them back to client.
>
> The other solutions might be:
> 1. Report this as bug to golem-messages.
> 2. Keep the current solution.
> 3. Use different serialization method for storing messages in database (ie. pickle).
> 4. Use the same `sign_func` as `dump` function and sign message with concent keys
`functools.partial(cryptography.ecdsa_sign, privkey)`
>
> Please let me know what do you guys think about this.

So you're basically saying that `serialize()` without a parameter discards the original signature and replaces it with zeros? This is definitely unexpected behavior to me, maybe even a bug. It's both unexpected and inconsistent with what happens with the message if you let `golem-messages` serialize it. Please report it.

I see that your solution is simply letting golem-messages serialize the nested messages. That's good, less code for us. If we don't need to serialize explicitly, let's not.

For messages created by ourselves letting `golem-messages` replace the null sig with a string of zeros is fine as long as we never send such messages to the client. We can treat it as a special value, just like `None` or empty string.

We should add some assertions that make sure that a message returned from a view never has a signature that's a string of zeros. This applies to nested messages too (would be nice to have a function that checks this recursively).

**Comment by rwrzesien** [comment]
> So you're basically saying that serialize() without a parameter discards the original signature and replaces it with zeros?

Only when signature is `None` at the moment when .serialize() is called. It doesn't replace other signatures. But as already 2 out of 2 developers who saw this issue suggested to report it to Golem team, I will.

**Comment by rwrzesien** [comment]
It works ok for those.

**Comment by cameel** [comment]
So... why were we doing `message.sig = None` if it was already `None`?

**Comment by rwrzesien** [comment]
It was `None` when it was created, but after calling `.serialize()` it is filled with what `_fake_sign` function returns. And, as you see on this PR's changes, previously we were serializing the same message which was returned to client. Now I am creating copy of it.

**Comment by cameel** [comment]
Oh, so what was being cleared was the signature filled with zeros that was created as a result of serializing a message before and not the original signature? I'm still not sure if that's what you mean because it's not clearly stated in your description of the problem.

If that's the case then `serialize()` is not as broken as I thought. I think that it still should just refuse to serialize the message instead of filling it with zeros and pretending it's a good signature but it's much less severe than overwriting the original signature (which I thought was the problem here).

> And, as you see on this PR's changes, previously we were serializing the same message which was returned to client. Now I am creating copy of it.

But we sign it before returning it, right? If so, instead of making a copy it would be better to just add a condition that checks if signature is all zeros and assumes that the message is not signed if it is.

**Comment by rwrzesien** [comment]
> Oh, so what was being cleared was the signature filled with zeros that was created as a result of serializing a message before and not the original signature? I'm still not sure if that's what you mean because it's not clearly stated in your description of the problem.

Yes, exactly.

> If that's the case then serialize() is not as broken as I thought.

That is why I have asked if it should be reported to golem team.

> But we sign it before returning it, right? If so, instead of making a copy it would be better to just add a condition that checks if signature is all zeros and assumes that the message is not signed if it is.

Those are two different cases. We still need to serialize it when storing to database, and when called during view execution it changes `sig` value outside of the `store..` function too. So that is why a copy is created, otherwise it will be returned with zeros.
And yes, we sign it using `dump()` but that is in `api_view.py`, after view is finished.

**Comment by cameel** [comment]
> We still need to serialize it when storing to database, and when called during view execution it changes sig value outside of the store.. function too. So that is why a copy is created, otherwise it will be returned with zeros.

Oh. Right, if someone passes data to your function you should not modify it unless that's clear from function's name or docs. In that case making a copy is necessary. That's another thing I should mention in the coding style when I do the next update.

I have commented on this in https://github.com/golemfactory/golem-messages/issues/162 and hopefully that will be changed so that we can seralize messages without modifying them. If not, we'll have to add checks for `sig` filled with zeros everywhere.

**Comment by rwrzesien** [comment]
I have added the check already in `api_view.py`.

**Comment by cameel** [comment]
There's a pull request with a fix for https://github.com/golemfactory/golem-messages/issues/162

Turns out that clearing the sig is actually the right thing to do. I now see why. There's no option to have no signature in a serialized message. A signature of all zeros is still the output of some (fake) signing algorithm. We need to clear that signature before we sign the message again.
