### ISSUE TITLE
Identifying clients based on public keys passed in headers

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#16]
We don't have an authorization mechanism yet and we also don't even check who is sending/receiving a message. All we currently do is to ensure that a message signature matches the key sent in the `Concent-Client-Public-Key` HTTP header.

The authorization mechanism is still to be designed but for now we should at least start to identify the clients.
- Every message to be delivered from `receive/` and `receive-out-of-band/` endpoints should only be delivered to the client it's meant for. So you should store receiver's public key with the message and only return that message if the key is the same as the one in the `Concent-Client-Public-Key` HTTP header.
- In the `send/` endpoint:
    - The public key or the client who sent `ForceReportComputedTask` should be remembered as provider's key for that task. All the subsequent messages from the provider regarding this task must use the same key.
    - When sending `ForceReportComputedTask`, the client must send requestor's public key in the `Concent-Requestor-Public-Key` header. The key must match the signature on the `TaskToCompute` message. All subsequent messages from the requestor regarding this task must use the same key.
    - `AckReportComputedTask` and `RejectReportComputedTask` must be submitted and signed by the requestor.
    - `CannotComputeTask` and `TaskFailure` messages sent inside other messages must be signed by the provider.

**Comment by cameel** [comment]
Note that @kbeker has already added a special HTTP header for submitting the public key of the other party. Remove support for that header and accept only `Concent-Requestor-Public-Key` as stated above and only with the message that starts each use case. So, for now only with `ForceReportComputedTask`. Later, when we're done with #12, also `ForceGetTaskResult`.

**Comment by rwrzesien** [comment]
@cameel I am thinking about following solution:
1. Use Django authorization system, overwrite authorization backend to authorize in a way you have described it. Then we can use it's features, like permissions etc. Also a lot of 3rd party libs use it.
2. Subclass Django User, let it store its key.
3. Add a ManyToMany for that subclassed User and Message. Then Message can match both Provider User and Requestor User.
4. All the logic can be then implemented on subclassed User instead of in endpoints.
What do you think ?

**Comment by cameel** [comment]
I'm not sure it's worth the hassle to try to use the `User` class here. We won't ever have anything resembling user accounts. We won't have any information about our users. We won't use Django's permissions. User's won't "log in" - there are no sessions.

I think that a simple table for storing public keys is be enough at this point. I would not go far beyond that because we don't know how the authorization - and by that I mostly mean key exchange - will really look like. That part is not designed by Łukasz yet. So I'd hold off until we know more. This issue is really just a temporary solution until we have enough information to implement real authorization.

Also `Message` does not really belong to a user. The status object does. `Message` is just a generic storage of messages for any purpose. Right now there are two status tables that reference the message table - they represent queues for `receive/` and `receive-out-of-band/`. In the future we might have other tables referencing `Message`. And there can be entries in `Message` that do not have associated status objects.
