### ISSUE TITLE
[report computed task] Concent does not look at provider's public key when checking if a task is already being processed

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#160]
In `handle_send_force_report_computed_task` there is a check:

```
    if StoredMessage.objects.filter(task_id = client_message.report_computed_task.task_to_compute.compute_task_def['task_id']).exists():
        raise Http400("{} is already being processed for this task.".format(client_message.__class__.__name__))
```

it should also include filtering by provider's public key and message type. Otherwise client can use prepared message to lock possibility for other clients to start communication for used `task_id`.

A test which verifies that in `test_auth_report_computed_task.py` is also needed.

**Comment by cameel** [comment]
As discussed today with @rwrzesien, the check should not be in the filter but after it. For now keep treating `subtask_id` as unique. Just find the task and then, if you find one, reject the message. At most the error message could be dependent on whether the provider matches or not.

**Comment by rwrzesien** [comment]
According to @cameel comment I am closing it.
