### ISSUE TITLE
Validate that nested messages in the Subtask table are consistent with each other

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#177]
Extracted from https://github.com/golemfactory/concent/pull/158#discussion_r173774893:

> - Validate that `task_compute` is the same as the one inside `report_computed_task` if the latter is not `None`. Same for any other nested messages.

The above is just an example. Please find and fix all such places.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/157690904
