### ISSUE TITLE
Response header with version of golem-messages

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#18]
In all HTTP responses from concent-api and gatekeeper include a header with version of golem-message being used on the server.

If we're using a tagged version, include that tag. Otherwise include the commit ID.

Requested by @jiivan to help in debugging Concent-related issues on the Golem side.

**Comment by rwrzesien** [comment]
@cameel I would like to use GitPython for this http://gitpython.readthedocs.io . Now, it has attribute name_rev on commit object, which have value like:
'ca6f01c15451fbf877ef6e3043bd55e607b7d935 tags/v1.2.1' when commit is tag, and 
'f94d72024f8fc4d496978915c31256d6a45fc55f remotes/origin/concent-messages' when commit is not a tag. 

Would that be ok to use this as version header ? It contains all the info plus extra branch name and origin for non-tag commits.

If you want to have like in the original description, it is not a problem, it will just require one or two more ifs.

**Comment by cameel** [comment]
I think that we should have just the tag (i.e. `v1.2.1`) when it's a tagged commit. I think that most of the time we'll be running a tagged version and the commit ID is just noise in that case. It's still helpful if there is no tag though to so it's fine to add it on untagged commits. Branch name is completely unnecessary.

Another thing is that I'd prefer if we did not rely entirely on git. The code does not have to come from git. It can be installed from a python package.

**Comment by cameel** [comment]
I see that @jiivan has added `__version__` to golem-messages a few days ago: https://github.com/golemfactory/golem-messages/commit/eed9f9340f97513e949f64c8ec8be96334003dbf#diff-ae716e1448ba977101f358c0355724abR8. We should use it.

It looks like it also can handle installing from a package (via a `RELEASE-VERSION` file that must be placed in the package during build). See [version.py](https://github.com/golemfactory/golem-messages/blob/v1.3.1/version.py).

**Comment by rwrzesien** [comment]
@cameel Pull request created https://github.com/golemfactory/concent/pull/33

**Comment by cameel** [comment]
Merged into master: 83cd12b8f021e692e68460b91752fa5174a9b2c5
