### ISSUE TITLE
"None of subtask changed state" in concent_api logs

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#182]
We're getting lots of lines like this in logs on staging:

```
textPayload: "17:08:56 INFO     | None of subtask changed state -- CLIENT PUBLIC KEY: b'07byqHcsE3uMqRRw3q5GykDQyK0YNXjUO1N1JnZpHiPykajphbddrrTdSw8PJ79BO2masDxXm2SXgep/RovsYQ=='
```

I think that `None` was meant to be a number. Please find and fix the error that's causing this.

**Comment by kbeker** [comment]
It means that for this client none of subtask is already after deadline and none of his subtask changed state for diffrent one.

**Comment by cameel** [comment]
This should be reworded in that case.

What about `No subtask changed state`? `0 subtasks changed state`?

**Comment by rwrzesien** [comment]
I vote for `0 subtasks ...` and simplifying this part by removing `if`.
