### ISSUE TITLE
Better tests coverage for the "force report task computed" use case

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#21]
The code is severely undertested. Basically, every conditional branch in `receive()`, `receive-out-of-band()` and `send()` should have the corresponding test.

Make sure that corner cases are covered:
- Sending a message twice
- Sending ack/reject when force has not been sent
- Sending contradictory ack and reject
- Invalid values in headers (no key, bad key, truncated key, too short key, key that's not a valid base64-encoded string, multiple keys)
- Invalid messages
- Trying to fetch messages when queue is empty
- Trying to fetch a message that's created dynamically
- Requestor sending ack or reject when his time window is already over.

Anything else you can think of. None of these cases should result in failed assertions or 5xx errors.

**Comment by rwrzesien** [comment]
@cameel What do you think about adding test coverage report ?

**Comment by cameel** [comment]
> 1. What do you think about adding test coverage report ? 

Good idea. I wanted to add it at some point. I have created a new task for it: #23.

> 2. What does it mean that 'message is created dynamically' ?

Sometimes `receive/` and `receive-out-of-band/` are supposed to return something based on the current time even if there are no messages waiting in the queue stored in the database. For example if there was no ack from requestor, `receive/` does not return anything to the provider before the end of provider's phase. But after that it's supposed to generate an ack on its own - because the requestor did not respond. We can't store such messages in queue ahead of time. We could have a process watching the deadline and generating them. But it's much simpler to create them only when the provider calls `receive/`.

> 3. I will add tests for bad headers here, but generally for all types of messages those should work the same way, being caught on same layer.

Yeah, these should be generic tests for `send`/`receive`/`receive-out-of-band` not tied to any particular use case. This issue is both about tests for the first use case and for Karol's work with `golem-messages`  because they're both implemented together.

> 4. By "Sending contradictory ack and reject" do you mean sending:
>    - MessageCannotComputeTask in MessageAckReportComputedTask
>    - MessageTaskToCompute in MessageRejectReportComputedTask

I mean the situation where requestor for example first sends an ack and then sends a reject, still within his time window. Or the reverse. Remember that requestor has a time interval when he is supposed to send us a message and he could potentially send multiple messages during that window. We have to handle this gracefully.

As an aside, another test case I thought of just now, unrelated to your question, would be requestor sending ack or reject when his time window is already over. I'll add it to the list.

> 5. Could you please explain a little bit more about 'Invalid messages' ? Or do you mean by that what I have described in point 4. ?

I mean sequences of bytes that do not represent serialized `Message` objects. For example a message that has been cut in half. Or mangled by removing every other byte. Or a sequence of zeros that's not really a message. Anything else you can think of.

> 6. There are two tests for invalid key, which fails inside golem-messages. Should those be skipped for now, expect exception or reported to golem team ?

These are exactly the cases I wanted these tests to catch. Yeah, they should be fixed in golem-messages so please report them. In most cases golem-messages should simply be raising a custom exception that indicates a validation issue. E.g. something like `InvalidPublicKey` instead of `AttributeError`. Karol has already reported one of these cases here: https://github.com/golemfactory/golem-messages/issues/52#issuecomment-353121604

But in the meantime we have to deal with them on our side. We absolutely must not return HTTP 500 when we simply get malformed messages or keys from the client. So investigate each of these cases to make sure it's really caused by bad data and if so, simply catch the exception `golem-messages` is raising now and add a FIXME to change it when golem-messages adds a custom type.

If it's not caused by bad data but a bug in `golem-messages` then that's a blocker for us and should be added as such in Pivotal.

> 7. By "Trying to fetch messages when queue is empty" do you mean case when we are trying to get computed task report on non-existing task ?

I mean calling `receive/` or `receive-out-of-band/` when there are no messages waiting for the client. That's allowed but it's not covered by integration tests becuase normally every client sticks to its time window and knows when there should be a message waiting for it. But if the client does call Concent too many times or outside of its time window and there's nothing waiting in queue, Concent should still respond in some way. In our case it's HTTP 204 and possibly some headers.

**Comment by rwrzesien** [comment]
Ad 1) Ok.
Ad 2) Those are already covered by yours tests.
Ad 3) Ok, so lest at some point move them to be more generic tests instead of repeating them for every functionality.
Ad 4) Ok
Ad 5) Ok, I have found one that can be golem-messages bug, lets discuss it tomorrow.
Ad 6) I have found a way to handle those in Concent.
Ad 7) Looks like it was good idea because from tests I have found out that I was able to receive message outside of time window and also twice. I will work on fixing those two cases now.

**Comment by cameel** [comment]
> Ad 7) Looks like it was good idea because from tests I have found out that I was able to receive message outside of time window and also twice. I will work on fixing those two cases now.

I see that this part has been edited out but I still wanted to point out one important thing. `send/` should not accept messages from a client outside of its time window. But `receive/` is different. If a message has been queued, the client should be able to fetch it, no matter if it's within the time window or not. This applies to dynamic messages to. The messages should not normally "disppear" from queue.

We'll probably have some predefined period after which we delete old messages (we're not going store them forever) but it will be independent of the time windows and probably much longer.

I want it that way because that's closer to how a P2P protocol would work - if you have sent a message (and for us adding it to a queue is the same as sending it out) you can't take it back. It's up to the client to discard it if it's no longer valid.

I also think that this makes the service more straightforward and predictable. It should make it a bit easier to debug issues from the client side if it's not so heavily affected by timing.

**Comment by cameel** [comment]
Code in 585065f2035bf444b94b3d32a28fa294cea2bc33

Merged into master as a part of #25
