### ISSUE TITLE
Verifier: receiving a task and sending a response

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#220]
This is a part of the implementation of the #193 blueprint.

- Create an app called `verifier` inside the `concent_api` Django project.
- Create a Celery handler for the `blender_verification_order` message (see #193).
- When you receive the task, respond with `verification_result` message.
    - For now just return a random or hard-coded result. This will be changed in subsequent implementation tasks.
- Log beginning and finishing a task and any information needed to identify it in logs.

### Task separation
We want to be able to connect three separate workers types to the queue: Concent, Conductor and Verifier. Each of them should have its own task handlers. When you start one of them with `celery worker` command it must not start processing tasks that belong to other worker types.

We'll achieve this by adding a new value to `settings.CONCENT_FEATURES`. Worker's tasks handlers should be registered only if that setting contains `'verifier'` string.

### Setup for local development
For local development you'll need to run a RabbitMQ server and a single Celery worker. You can run RabbitMQ in a docker container in one terminal and start the worker in the other. See https://github.com/golemfactory/concent/issues/197#issuecomment-375620295. It should work out of the box because `settings/development.py` is configured to connect to a RabbitMQ server on default port running on localhost.

**Comment by cameel** [comment]
Update: task separation. (see description)

**Comment by rwrzesien** [comment]
@cameel 

> Create a Celery handler for the verification_order message (see #193).

This should be a django view, which schedules celery task ?

**Comment by cameel** [comment]
We talked about it on a hangout. For the record: This should be a celery task. When I write "worker" I mean code that is started via `celery worker` and runs inside a Celery task. When I write something HTTP or something API I mean code that is a part of a web server and runs inside a Django view.

**Comment by cameel** [comment]
Update: `verification_order` modified in the blueprint:
- Renamed to `blender_verification_order`.
- Many fields removed or modified.

**Comment by rwrzesien** [comment]
@cameel 
According to https://github.com/golemfactory/concent/issues/193

> blender_verification_order task
> Same as blender_verification_request

`blender_verification_order` is already defined in Conductor, why do we need it here again ?
