### ISSUE TITLE
Verifier: downloading files from the storage server

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#221]
This is a part of the implementation of the #193 blueprint. This task depends on #220.

1) Define the following settings and Django checks for them:
    - `STORAGE_SERVER_INTERNAL_ADDRESS`: URL of the storage server. Similar to `STORAGE_CLUSTER_ADDRESS` used by Concent but not the same because Verifier is running inside the storage cluster and should not refer to that server by its external address. It's meant to be combined with file names in the same way.
        - The setting must be non-blank and point to an existing directory when `verifier` is in `CONCENT_FEATURES`. Otherwise it must be blank or undefined.
        - If it's not blank, do the same checks as for `STORAGE_CLUSTER_ADDRESS`.
    - `VERIFIER_STORAGE_PATH`: Path to a directory where verifier can store files downloaded from the storage server, rendering results and any intermediate files. This directory is guaranteed to have substantially more space available than locations inside container's root file system.
        - The setting must be non-blank and point to an existing directory when `verifier` is in `CONCENT_FEATURES`. Otherwise it must be blank or undefined.
        - If it's not blank the directory must exist and have write permission for the user we're running as.

2) After receiving `blender_verification_order` and before issuing a response `verifier` should perform the following steps:
    - Generate a `FileTransferToken` valid for a download of any file listed in the order.
    - Remove any files from `VERIFIER_STORAGE_PATH`.
        - If removal fails, ignore the error. If it's a problem, one of the later steps will fails anyway. If it's not a problem, there's no reason not to continue.
    - Download all the files listed in the message from the storage server to local storage.
        - If download fails, verification ends. Send `verification_result` describing the error to the work queue.

#### Work queue
For local development you'll need to run a RabbitMQ server and a single Celery worker. You can run RabbitMQ in a docker container in one terminal and start the worker in the other. See https://github.com/golemfactory/concent/issues/197#issuecomment-375620295. It should work out of the box because `settings/development.py` is configured to connect to a RabbitMQ server on default port running on localhost.

#### Storage server
You'll need a local server to serve the files. This can be easily arranged by running a `nginx` image from DockerHub. You can ignore token checks and gatekeeper when running it locally.

**Comment by cameel** [comment]
### Running a local `nginx` container for serving files

Save this in a file called `run-nginx-storage.sh`:
``` bash
#!/bin/bash -e

mkdir --parents /tmp/nginx-storage/{download,config}/

nginx_root=/tmp/nginx-storage

cat <<- EOF > $nginx_root/config/nginx-storage.conf
server {
    listen  127.0.0.1:80;
    charset utf-8;

    location /download/ {
        root $nginx_root/;
    }
}
EOF

cat <<- EOF > $nginx_root/download/index.html
<html>
    <body>
        <h1>nginx-storage</h1>
        <p>All files located in $nginx_root/download/ can now be downloaded from URLs starting with http://localhost/download/.</p>
    <body>
<html>
EOF

sudo systemctl start docker

docker run                                                                           \
    --rm                                                                             \
    --volume $nginx_root/config/nginx-storage.conf:/etc/nginx/conf.d/default.conf:ro \
    --volume $nginx_root/download/:$nginx_root/download/:ro                          \
    --net    host                                                                    \
    --name   nginx-storage                                                           \
    nginx:alpine
```

Make it executable:
``` bash
chmod +x run-nginx-storage.sh
```

The script starts docker (if it's not running yet), downloads a nginx image and configures it so that all files placed in `/tmp/nginx-storage/download/` can be download from URLs starting with `http://localhost/download/`.

If you already have a server running at port 80, just change the port to something else.

**Comment by rwrzesien** [comment]
@cameel 

> The setting must be non-blank and point to an existing directory when verifier is in CONCENT_FEATURES. Otherwise it must not be blank.

Should it be `Otherwise it must be blank.` ?

**Comment by cameel** [comment]
Yes. Fixed.

**Comment by rwrzesien** [comment]
@cameel 
> Generate a FileTransferToken valid for a download of any file listed in the order.

Isn't there going to be only one file at this moment ?

**Comment by cameel** [comment]
> Isn't there going to be exactly two files at this moment ?

Right now, with Blender - yes, but in general - not necessarily. I don't want the control cluster to have too many assumptions about this. Only the storage cluster needs to know more. That's why it's a list of files here and specific files in later subtasks.

But actually I need to review this part of the spec and make sure it makes sense. maybe I'll need to change it. I hope I'll to get to it today. I'll post an update here.

> How to get their `path`, `size` and `checksum` for `FileInfo` message ? I think we only know file name at this point.

Why do you need that information? You can assume that if a file is on the storage server it has already been verified.

Paths are relative and are on the file list (though you could really put it anywhere you want; only the file name matters).

And for checking if there's enough space - you can do that when you start the download. nginx gives you the `Content-Length` header. Of you can check with a `HEAD` request if you need that information before download.

> What if two or more tasks will be running at the same time ?

Not in the same container. Every container is processing only one task at a time. And each of them has its own storage attached. You don't have to worry about that. We'll start only one Celery worker per container.

**Comment by cameel** [comment]
Update: `verification_order` modified in the blueprint:
- Renamed to `blender_verification_order`.
- Many fields removed or modified.
