### ISSUE TITLE
Checking if provider has uploaded the files for 'Get Task Result' use case

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#26]
When realizing https://github.com/golemfactory/concent/issues/12 points 4A, 4B, 4C and 4D, Concent API should ask Nginx Storage if files where uploaded to the Storage Cluster. It should be done in `receive/` endpoint. Concent API should sent `HEAD` request to Storage Cluster, in the same way as it would like to download files, which means it should use download token. 

Sample request:
```
curl --head http://storage.concent.golem.network/download/blender/benchmark/test_task/scene-Helicopter-27-cycles.blend \
    --header "Authorization: Golem dG9rZW4K" \
    --header "Concent-Client-Public-Key: MTIzNDU2Cg=="
```

The response should be handled like this:
* Response `200` - files were uploaded, it should continue this request flow.
* Response `2xx` - should return 500 response  from Concent API as something unexpected was returned from Storage Cluster.
* Response `3xx` - should return 500 response  from Concent API as as something unexpected was returned from Storage Cluster.
* Response `404` - files were not uploaded, Concent API should return 404.
* Response `4xx` - should return 500 response  from Concent API as something went wrong between Concent API and Storage Cluster.
* Response `5xx` - should return 502 response from Concent API.

Also, there should be added integration tests, which will test full functionality with mocked response from the storage cluster

**Comment by rwrzesien** [comment]
@cameel Please review, I think there is only limited number of response statuses which can be returned from gatekeeper and they are described above, I have checked the code and there are no redirect or 2xx responses there. But if you think they can happen and should be handled we need to discuss because I don't know on which flow they are returned.

**Comment by cameel** [comment]
> `curl -X HEAD`

You should use `curl --head`. `curl -X HEAD` sends a GET request and only changes the method name which is not the same. https://serverfault.com/questions/140149/difference-between-curl-i-and-curl-x-head 

> Response 401 - access denied, Concent API should return 404.

I'd return HTTP 500 or some other 5xx error. Access denied would mean that the cluster does not accept our own token. Something must be very wrong. For example both clusters have different private keys (they must have the same keys for tokens to work). One of the clusters must be misconfigured. This is not a client's mistake so 4xx is not appropriate.

You did not specify what to do about any other 4xx errors.

> Also, there should be added integration tests, which will test full functionality from sending request through Concent API to Nginx Cluster. This test should not use DjangoTestClient nor DjangoTestCase. Each test should cover one of 4A, 4B, 4C and 4D cases, use requests and check for responses described in #12.

I think that in this issue functional tests that mock the response from the storage cluster are enough.

You should create a separate issue to make a testing script that works with a real cluster. That script should not run as a part of `manage.py test` because it requires extra setup.

**Comment by cameel** [comment]
> I have checked the code and there are no redirect or 2xx responses there. But if you think they can happen and should be handled we need to discuss because I don't know on which flow they are returned.

Please do not rely on the implementation. It can change. When you're handling a response you should be prepared to handle any status. You can get something unexpected when, for example, we put the server behind a proxy and the server goes down. Or if there's something wrong with the proxy. Or the request is wrong.

You don't have to force yourself to do something meaningful in every case. But you should at least return a 5xx error when you get something unexpected and you don't know how to handle it. You should not just ignore it and assume that it can't happen. The key idea is "crash early".

**Comment by rwrzesien** [comment]
Changed tests description.

**Comment by kbeker** [comment]
Status code 401 should be 500 as @cameel said before.

**Comment by rwrzesien** [comment]
@kbeker Yes, as described 

> Response 4xx - should return 500 response from Concent API as something went wrong between Concent API and Storage Cluster.

**Comment by cameel** [comment]
@rwrzesien @kbeker ?

**Comment by rwrzesien** [comment]
@cameel 

> Response 5xx - should return 502 response from Concent API.

This is working differently now, 5xx returns 500 response from Concent API. But I think it was discussed to work this way. Rest is ok.

**Comment by Jakub89** [comment]
Based on last comment, I think we can close this issue.
