### ISSUE TITLE
Refactor send(), receive() and receive_out_of_band() logic to make it less repetitive and easier to understand.

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#27]
To do:
* Move logic of message handling into separate functions.
* Identify repeating pieces of code and move them into separate functions.
* Move strings into constants.

**Comment by rwrzesien** [comment]
To do:
* Move each message handling into separate functions.
* Identify repeating pieces of code and move them to parametrized functions.
* Move strings into constants

**Comment by cameel** [comment]
I'd leave moving strings into constants for another round of refactoring, the one after the second use case. This one is meant to be very minimal and focus on making the code easier to understand for review purposes. It's much more important to reorganize the conditions into something more logical.
