### ISSUE TITLE
MAXIMUM_DOWNLOAD_TIME must depend on file size

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#281]
Currently `MAXIMUM_DOWNLOAD_TIME` is a setting and its value never changes at runtime. golem-messages has taken a different approach: it has [maximum_download_time()](https://github.com/golemfactory/golem-messages/blob/v2.3.4/golem_messages/helpers.py#L23-L39) function which computes the maximum time based on file size. Concent should use that too.

- Replace the `MAXIMUM_DOWNLOAD_TIME` setting with two new ones: `MINIMUM_UPLOAD_RATE` and `DOWNLOAD_LEADIN_TIME`.
    - Use values from `constants` module in golem-messages as defaults.
    - Add system checks for the new settings.
        - Both must be defined.
        - Both must be integers.
        - `DOWNLOAD_LEADIN_TIME` cannot be negative.
        - `MINIMUM_UPLOAD_RATE` cannot be lower than 1 bit per second.
    - Remove the old one and add the new values to `protocol-constants`.
- Create a function that computes the maximum download time based on file size and settings.
    - Use `maximum_download_size()` from golem-messages in the implementation.
    - Pass our setting values to it.
        - Note: as of v2.3.4 the function has `DOWNLOAD_LEADIN_TIME` hard-coded but this is going to change soon.
- All timeouts based on `MAXIMUM_DOWNLOAD_TIME` should now use our function instead.

**Comment by cameel** [comment]
@rwrzesien
> >    Both must be integers.
>
> DOWNLOAD_LEADIN_TIME is timedelta in golem_messages.

I see that this comment was remove but that's actually a good point.

I generally prefer the settings to have simple values. But we could support both `timedelta` and `int`. Do you think it would be useful?

The downside I see that for consistency we should probably support `timedelta` for all timing-related settings and that might make the code a bit messier.

**Comment by rwrzesien** [comment]
@cameel Exactly, that is why I chose to cast it to `int`, as we use it over the application as time.
