### ISSUE TITLE
Concent crashes if requestor checks for ForceGetTaskResultDownload too late

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#305]
SCENARIO:

>  Requestor -> Concent:     ForceGetTaskResult
>         Concent   -> Requestor:   AckForceGetTaskResult
>         Concent   -> Provider:    ForceGetTaskResultUpload
>         Provider  -> Concent:     Upload good files
>         Concent   -> Requestor:    #ForceGetTaskResultDownload

Concent should always have not outdated toke, when checks if file transefer is finished.
Client should be able to receive message with outdated token (when requests `receive/` endpoint too late) - it's client's problem what to do with such a token.

**Comment by cameel** [comment]
Crash report in Sentry: https://talkback.golem.network/sentry/concent/issues/9083
