### ISSUE TITLE
Rename the 'default' database to 'control'

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#330]
There's a problem in our deployment for conductor: Django always requires the `'default'` database to be defined. It can have empty config but it must be there (see [Multiple databases > Defining your databases](https://docs.djangoproject.com/en/1.11/topics/db/multi-db/#defining-your-databases)).

Each of our apps needs only one database and we were just going to delete the config of the other one during deployment but this makes it impossible. We can work around it by setting `'default'` to `{}` but it would be better to just get rid of the concept of the derault database in our project. The default one would have to change depending on what we're deploying to make sense.

Steps to do:
- Rename `DATABASES['default']` to `DATABASES['control']` in `base.py`, `testing.py` and any other place in the code where it's used (other configs, database router, etc.).
- Add a new entry called `'default'` and set it to an empty dict.
- Modify our system checks so that a configuration consisting of just an empty dict is allowed. Right now we require `ATOMIC_REQUESTS` in every configuration dict (#279).
- Update the migration command in the `README` so that it properly migrates both databases. If plain `migrate` without extra options does not migrate both databases, replace it with two separate commands.
- (Optional) Since #279 is done, you can also refactor our database config so that there are no defaults for production:
    - Move `DATABASES` from `base.py` to `development.py`. But at least leave a comment in `base.py` explaning how it should be configured (i.e. that `'default'` should be left empty and which app needs which database).

**Comment by cameel** [comment]
If #152/#233 gets merged before this, remember to update the database used for live config: https://github.com/golemfactory/concent/pull/233#discussion_r184784795

**Comment by cameel** [comment]
1) What about [README](https://github.com/golemfactory/concent/blob/master/README.md)? Does it migrate both databases without extra options?

2) If some parts of the issue are marked as optional, please remember to drop a comment in the issue on whether they were actually implemented or not. @bartoszbetka will need to adjust his deployment changes accordingly and it would be easier for him if he could easily find that out without digging into the pull request.

**Comment by rwrzesien** [comment]
The optional part was not done.
