### ISSUE TITLE
Showing time left until Concent shuts down

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#335]
In #152 we implement soft shutdown. When it's enabled the system still processes existing subtasks but does not accept new ones. We can't say for sure when it will shut down but we can easily compute the upper bound - it's the time when the last active subtask times out.

Add a bar at the top of the admin panel that shows the shutdown status. It should contain:
- A message saying what the current state is:
    - Not shutting down (but in this case it's best to just not show the bar)
    - Shutting down and there are active subtasks
    - Shutting down and all subtasks are passive but there may be downloads going on (see https://github.com/golemfactory/concent/issues/152#issuecomment-384696044)
    - Everything shut down. No active subtasks or downloads.
- Maybe use different colors for different states.
- How much time is left until the last subtask times out and goes into a passive state.
    - The date and time in UTC and the number of minutes (or hours?) left. It's enough to update it on page refreshes.
- The number of active subtasks and subtasks with possible downloads.
- Try to make it generic enough that we can easily make some simple changes in how it works. E.g. move this elesewhere (e.g. to a separate page), make it public (so that login is not required) or change its look. Don't overengineer it but also don't make everything hard-coded.

This might be useful to display the data https://medium.com/@hakibenita/how-to-turn-django-admin-into-a-lightweight-dashboard-a0e0bbf609ad.

**Comment by rwrzesien** [comment]
Added link to data display plugin.
