### ISSUE TITLE
More logging in Gatekeeper

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#35]
`gatekeeper` should log more messages so that we can better understand what it's doing when deployed to the cluster. Add logging in the following situations:
- DEBUG: Upload or download request has been received. Include the path, client's public key, subtask ID, operation. Maybe also more information from the token.
- INFO: 4xx errors. Include the path, client's key, subtask ID, error message.

**Comment by Jakub89** [comment]
I've added all the changes. They are in "chore-gatekeeper-logging" branch. I will make pull request, when new version of "golem-messages" arrives, because "subtask ID" will be added then(it's on master branch, but with no v1.x.x, and that's what we use in requirements).
