### ISSUE TITLE
Logging all communication in Django apps

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#359]
To be able to debug issues that occur on a live cluster with limited access for developers, we need to log enough information for someone to be able to reproduce the whole situation on his machine but without giving everyone access to everything.

I think that the thing we should focus on are the requests and messages coming in and out of each container.

### Typical scenario
- Someone reports a problem with his subtask on the cluster.
- Admin identifies the subtask and filters the logs by its ID.
- The filtered logs are sent to the programmer.
- The programmer looks at the timing of the messages and their content and tries to recreate them in his own environment.
- If that's enough to reproduce the error - great. This should cover the majority of cases.
    - If not, the next step is getting a dump of the data related to the subtask but that will be a different feature.

### The task
Every HTTP request and response going through our endpoints must be logged, together with a useful subset of the data that was included in it.

It's pointless to print the raw, undecoded data because on a real cluster the programmer won't have access to the keys that would allow decoding it. In some cases not having access to the raw data won't allow us to recreate the events with 100% accuracy but in most cases the mechanism described here should be sufficient.

This should be done in all apps: concent-api, gatekepper, conductor, verifier, etc. For both internal and external communication.

What should be logged:
- In views: HTTP headers that are relevant to the application and the client.
    - Including all of them might be an overkill. Don't print the ones we don't even look at. For example `User-Agent` is not relevant but `Content-Type` or `Concent-Client-Public-Key` is.
- In views: Golem-messages, JSON or text data included in HTTP requests.
    - Ignore images, zip files or HTML. Use a whitelist of allowed formats.
    - Golem messages should be printed in a decoded form. It should be a representation that will allow the programmer to create his own messages with similar content but not necessarily the same signature.
- Celery tasks
    - Print the parameters that are passed to the function that processes the task
    - Don't worry about logging raw AMQP messages. We'll be logging them inside RabbitMQ.
- Outgoing HTTP requests
    - Requests to geth.
    - Requests to the storage cluster.
    - Log the parameters that went into that call, not the raw message. This will be enough for someone to reproduce it. And we'll have logging on the other side anyway.

Every message should include `subtask_id` that we can use to filter the logs.

Avoid logging binary data.

### Settings
- `COMMUNICATION_LOG_MESSAGE_SIZE_LIMIT`: int or `None`.
    - Defines the maximum size (number of unicode characters) of the part of a message to be logged. This only applies to messages logged as a part of this feature, not logging in general. It's meant to allow us to prevent our logs from getting overloaded with huge messages.
    - Must not be negative
    - `None` means no limit. This is the default.
    - `0` means that the messages are not printed at all.

**Comment by pawelkisielewicz** [comment]
I divide this task to 2 "subtasks":
1. I will create functions in all applications to log the "flow" of requests. It will allow to restore the way of handling of requests. We have already some logging functions in our code, it's a good start. Based on them I will log important information in several points in all apps, including fields, that allow to  identify each request(like `subtask_id`, `client key`). 

2. Second part is decorator, that will log all requests going in and out application. It will work like:
- log request going In. Generally, here will be logged everything, without unused fields (like constants) that will allow to "reproduce" messages and request. All `golem messages` included in request will be parsed to `json` and logged like this.
- start  view function
- log response from view

**Comment by pawelkisielewicz** [comment]
I divide this task to 2 "subtasks":
1. I will create functions in all applications to log the "flow" of requests. It will allow to restore the way of handling of requests. We have already some logging functions in our code, it's a good start. Based on them I will log important information in several points in all apps, including fields, that allow to  identify each request(like `subtask_id`, `client key`). 
For core views send the points of logging will be:
- info about subtasks changing theirs states- before handling messages
- confirmation of storing and saving subtasks in database - just after it 
- confirmation of storing and saving pending responses in database - just after it. Its also a confirmation of acceptance for further processing.
Current logging functions that will be deleted (logs from them are already at attached sample log):
- `log_timeout` in `handle_send_force_report_computed_task`, `handle_send_force_get_task_result`, `handle_send_force_subtask_results`. In this places are returning messages that will be logged in decorator going out of application. `log_timeout` function in this place would be duplication.
- `log_message_accepted` in `handle_errors_and_responses`. This method is called just after `log_new_pending_response` in `store_pending_message` and `log_new_pending_response` is actually the confirmation of acceptance this message for further processing.   

For core views receive endpoint: WIP

2. Second part is decorator, that will log all requests going in and out application. It will work like:
- log request going In. Generally, here will be logged everything, without unused fields (like constants) that will allow to "reproduce" messages and request. All `golem messages` included in request will be parsed to `json` and logged like this.
- start  view function
- log response from view

I have made first version of this task. It's not finished yet, the name of logger will be changed (now it is core and utils.logging, will be changed to separate logger for each file and utils.logging will be used no more). Also client keys will be decoded.

Here is sample log from test: `core.tests_core_views.test_send_should_accept_valid_message:

[log_sample.zip](https://github.com/golemfactory/concent/files/2074855/log_sample.zip)

It's not finished yet, known problems are:
- Client keys are not unified yet (in some places are in b64, some bytes). They will be unified. 
- Logger name is core and utils.logging. In final version all components will have their own logger name, like e.g.: core.views, core.message_handlers. It will be no more logs from utils.logging- it's only helper. 
- Lack of logging messages returning from views, it will be added.

**Comment by pawelkisielewicz** [comment]
For now our 'messages handling' decorators are:
`@require_golem_message`
`@handle_errors_and_responses`

There are two ways to place the logging-decorator:

1. At the beginning, like:
`@log_communication`
`@require_golem_message`
`@handle_errors_and_responses`
And in `@log_communication` decorator message would be decoded (or tried to be decoded) for logging

2. After decoding, like:
`@require_golem_message`
`@handle_errors_and_responses`
`@log_communication`
In this case  `@log_communication` gets already decoded message.

Our 'decoding part' in `require_golem_message` looks like:
 ` try:`
                `    golem_message = load_without_public_key(request.body)`
                `    assert golem_message is not None`
               `     client_public_key = get_validated_client_public_key_from_client_message(golem_message)`
           `except:.....`

First solution allows to decode message without checking time, like:
 `golem_message = load_without_public_key(request.body, check_time=false)'
 and save in logs this messages. It would not be able in second solution. 

This way (first) requires additional decoding (message is decoded 2 times).
Second way makes unable to log messages with incorrect timing- messages aren't decoded and only `JsonResponse` with Error is raised. It's impossible to log message going IN, only anonymous   `JsonResponse` could be logged. But it would be not very useful..

**Comment by rwrzesien** [comment]
@pawelkisielewicz 

> I will create functions in all applications to log the "flow" of requests. It will allow to restore the way of handling of requests. We have already some logging functions in our code, it's a good start. Based on them I will log important information in several points in all apps, including fields, that allow to identify each request(like subtask_id, client key).

I think all of the points which you have listed are already covered. What exactly do you want to add or change ?

> Second part is decorator, that will log all requests going in and out application. It will work like:

I don't think we need extra decorator for that. There are two cases:
- views which accepts golem message, they already have decorators which load message, so you could put the logging there, after loading.
- views which don't need loading messages, for them you can use Django to configure logging requests https://docs.djangoproject.com/en/2.0/topics/logging/#django-request (you may also check the whole chapter)

I think we should try using tools that framework gives us.

> There are two ways to place the logging-decorator:

By doing it the way I have described you don't have this dilemma.

**Comment by cameel** [comment]
> log_sample.zip

Please put this directly in your comment. If it's too long, shorten it a bit.

> There are two ways to place the logging-decorator:

This a problem that makes me think that adding a separate decorator for this is not a good solution. We should really not have to do too much additional processing to get the info to log. We should be logging what we already know at a given point.

Logging is unfortunately not something that can be nicely encapsulated in a separate utility. At least not with repeating the whole message decoding and processing.

I've been thinking a lot about how to proceed with logging and I have some new ideas. We'll need to talk about it before you proceed with this task.

**Comment by cameel** [comment]
I'm closing this since we have decided to change our approach a bit:
- Logging system is not the best solution for saving the data that goes in and out of each component. There's just too much data. For debugging it may be too little and for seeing what's going on on the cluster it may be too much.
    - We're going to create a separate component for storing audit data.
    - This data will be captured in text form at selected "checkpoints" in the system.
    - We'll have settings to disable or enable specific checkpoints.
    - This can be extended to other components too.
- Logs should tell us what our code did, but we can't really expect to be able to know why it did what it did without getting the full audit data.
