### ISSUE TITLE
FileTransferToken in AckSubtaskResultsVerify should contain two files

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#365]
`FileTransferToken` in `AckSubtaskResultsVerify` should contain two files, one for sources and one for results, which Provider should use to upload both. Currently there is only one.

**Comment by rwrzesien** [comment]
@cameel 

1. Should `FileTransferToken` with two files use the same `calculate_token_expiration_deadline` function as for one file ? Shouldn't there be more time for downloading two files ?
2. We have functions for creating paths for source and result files on storage cluster. How about `blender_verification_order` receives task_id along with subtask_id and create source_package_path and result_package_path by its own ?

**Comment by cameel** [comment]
Please don't close the issue it if there are still pending questions :)

> 1. Should `FileTransferToken` with two files use the same `calculate_token_expiration_deadline` function as for one file ? Shouldn't there be more time for downloading two files ?

A token is issued for the whole file transfer operation. The operation may involve transferring multiple files. There's no need for a separate deadline for each one. You can think of the token as issued for a use case, not for a file.

But keep in mind that deadline in the verification use case is different than the one in the result transfer use case. The verification deadline is long enough to upload both packages.

> 2. We have functions for creating paths for source and result files on storage cluster. How about `blender_verification_order` receives task_id along with subtask_id and create source_package_path and result_package_path by its own ?

I think it should stay on the control cluster. It's the one that generates names for the token. All the other places in code should get the names from there. We could theoretically use a name that cannot be constructed from those IDs. I want to keep the name generating code in one place.

**Comment by dybi** [comment]
all questions seem to be answered, thus issue seems to be no longer valid - closing
