### ISSUE TITLE
Concent API does not have the same checksum validations as gatekeeper

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#382]
Gatekeeper currently has extensive validations for `FileTransferToken`, including file checksums. Concent API does not have the same validations. In effect it's possible for the client to send us `ReportComputedTask` with a bad checksum and crash the server because we'll use that checksum in a token and use it in a request to the storage server.

To fix this:
- Validate `package_hash` in every `TaskToCompute` and `ReportComputedTask` the same way gatekeeper does.
- When creating tokens, `assert` that the created token passes those validations.
- Use the new `is_valid` hook from golem-messages.

Please also do #79 first.

**Comment by Jakub89** [comment]
`is_valid()` method is possible to use only for `message.tasks.TaskMessage` so we can't use it with `ForcePayment` message. Don't know if that's a bug, just saying that I won't be able to do it as a part of that issue.

**Comment by cameel** [comment]
OK. That's something we should raise with @shadeofblue. I think `ForcePayment` should have validations too.

**Comment by cameel** [comment]
@Jakub89 could you explain why you needed to validate `ForcePayment` in this task?

I'm reopening this just so that it does not get buried because @Jakub89 is now on vacation.

**Comment by Jakub89** [comment]
@cameel I don't really need to validate it, It's just something I've notice while adding `is_valid()` method. We use it for every message that go through `send()` endpoint, and `ForcePayment` is the only one that is not instance of `message.tasks.TaskMessage`, so we need to have special case for it.
I've created issue on golem-messages repo, but still now reply:
https://github.com/golemfactory/golem-messages/issues/233

**Comment by dybi** [comment]
a separate issue has been created in proper repository - closing
