### ISSUE TITLE
Atomic receive()

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#4]
Currently the `receive()` gets a pending message from the database and marks it as delivered as two separate operations. We need it to be atomic. Otherwise two processes handling separate requests at the same time might grab the same message before any of them marks it as delivered.

Use database locks ([select_for_update()](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#select-for-update)) to ensure that getting a message and marking it as delivered are a single, atomic operation.

Consider possible failures:
- View crashes while holding a lock (the lock must always be released in case of an exception)
- A badly behaved piece of code is holding a lock for a long time (we need a timeout)
- View gets a message and marks it as delivered but crashes before the message is actually sent via HTTP (database state needs to be rolled back in case of a crash)
- The whole container is killed while the view is holding a lock, not even giving Django a chance to catch an exception and release the lock (this is not trivial to handle; it will require some monitoring mechanism external to the container itself).

All of this, of course, applies to `receive_out_of_band()` too.

**Comment by rwrzesien** [comment]
@cameel 
1. In case of two separate requests at the same time try to grab the same message before any of them marks it as delivered, and one of them locks the row, a second should wait, or skip, or do something else ?
2. About last point, the external monitoring mechanism, do you think Redis might be good solution for this case ?

**Comment by cameel** [comment]
> 1. In case of two separate requests at the same time try to grab the same message before any of them marks it as delivered, and one of them locks the row, a second should wait, or skip, or do something else ?

One of the requests should wait for the other to release the lock. With a timeout. When the time is up, fail. Or try again, if you think it makes sense - but eventually fail with the appropriate HTTP 5xx status (504 kinda fits here but not quite; 500 if there's no other option). Don't forget to ensure that the process that creates the lock releases it no matter what when it ends (i.e. in a `finally` block).

The idea is that we keep the lock for as little time as possible so conflicts will be rare and wait time short. We also lock only a specific row so this impacts only one provider-requestor pair and only for a specific task. All the other requests do not wait.

> 2. About last point, the external monitoring mechanism, do you think Redis might be good solution for this case ?

But you would still need some active agent here, right? Redis is just storage and could store some information but won't actively connect to our database and check locks.

Or do you mean replacing database with Redis? If so, the problem is persistence. We need those messages stored in such a way that we do not lose them if the container goes down (crashes, is shut down during upgrade, etc.).

Could you explain your solution in more detail?

**Comment by rwrzesien** [comment]
> Could you explain your solution in more detail?
Sure, we are considering only situation when the whole container is killed while the view is holding a lock. I was thinking about adding info to Redis that a specific row is locked before it actually happens and removing that info after it is released, so if anything fails between it will still be marked as locked in external storage. Then, when container is started, it can check in Redis if there are any locks and release them, in similar way on how system_check works (or even it can be added there). After thinking it through, it doesn't have to be Redis, it can be any other storage, Redis just fits for me for this job.

**Comment by cameel** [comment]
It could just as well be another table in the same database. Or a lock :) In other words we're just making another level of lock this way.

**Comment by cameel** [comment]
I'm closing this issue because #718 will cover it.

As for the situations mentioned at the end:
- Crashing or having the whole container killed while holding a lock is not a problem after all because the locks are released automatically when the transaction ends and the transaction ends automatically when the connection to the database is broken.
- The problem that the view might mark the message as delivered but not really deliver it is a hard one and I don't see a viable solution for it in the near future. As long as we're inside the view, an exception will cause a rollback. But as soon as we hand the response to Django, it's too late. The fact is that the response might be sent out but never processed by the client (e.g. because it crashes) so the problem is not completely on our side. I think that this might simply require some tolerance for lost messages.
- The problem with the view entering an infinite loop is not something that we need to worry about here. gunicorn will kill the process if it exceeds a timeout.
