### ISSUE TITLE
Conductor: Notifying the control cluster about finished uploads for verification subtasks

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#411]
This is a change to Conductor's behavior described in #208 and #224. It's a part of the #193 blueprint.

Currently Conductor gives an order to start verification as soon as it receives a verification request from the control cluster and the provider finishes uploading the last file. We want to change it so that the control cluster gets notified when all the files have been uploaded and Conductor does not start verification until the control cluster acknowledges the upload.

- Add `upload_finished` and `upload_acknowledged` fields to the `VerificationRequest` table. They should be `False` by default.
    - These fields are purely for our information for now. Nothing is going to depend on their values (yet).
- Make Conductor stop sending `blender_verification_order` when everything is ready. It should queue an `upload_finished` task instead.
    - The only information needed is the ID of the subtask.
    - When `upload_finished` is queued, the corresponding field in the `VerificationRequest` table should be set to `True`.
    - `upload_finished` should be routed to the `concent` queue (see #407).
- Add a Celery handler for the `upload_acknowledged` task. It also contains only subtask ID. The handler should now be the one adding `blender_verification_order` to the work queue.
    - Don't worry about adding `upload_acknowledged` to the work queue. It's a separate issue: #413.
    - When `upload_acknowledged` is received, the corresponding field in the `VerificationRequest` table should be set to `True`.
    - `upload_acknowledged` should be routed to the `conductor` queue (see #407).

This and #413 have to be deployed together. They're separate issues so that pull requests are smaller but they're really two parts of a single feature. Don't merge one into master without the other.

**Comment by dybi** [comment]
@cameel, what about handling `upload_finished` in `core`? It seems not to be defined anywhere.

**Comment by cameel** [comment]
@dybi It's in #413.

**Comment by dybi** [comment]
@cameel , It is not stated clearly in the issue description above. It only states, that

> Don't worry about adding `upload_acknowledged` to the work queue. It's a separate issue: #413.


Please update the description

**Comment by cameel** [comment]
Updated.
