### ISSUE TITLE
receive/ and receive-out-of-band/ sometimes return HTTP 204 even if there's a message queued

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#44]
The current implementation of `receive/` and `receive-out-of-band/` views processes only one message at a time and returns `None` (which results in HTTP 204) if that message does not need to be returned to the client. This is not the correct behavior. If there's another message waiting in queue, that message should be returned instead. The views should only ever return HTTP 204 if there are no pending messages for the client.

Consider for example this piece of code: https://github.com/golemfactory/concent/blob/d5404685b4c8ac02924e62b1a3c54dbaf972e595/concent_api/core/views.py#L220-L227

If the client asks about the message outside of the right time window, the view returns `None`. It does not even check if there's another message waiting.

Another thing is that there should be no timeout checks in these views. If the message has been queued, it must be returned even it has already expired. The messages should never just disappear. Such behavior will make the views less predictable and harder to test reliably.

**Comment by cameel** [comment]
@rwrzesien This one was pretty important. Could you make sure it's done and close it?

**Comment by rwrzesien** [comment]
@cameel Yes, done in https://github.com/golemfactory/concent/pull/162.
