### ISSUE TITLE
Celery queues should not be created 'ad hoc'

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#445]
There should be only fixed/manually defined celery queues, missing ones should not be created:
`app.conf.task_create_missing_queues = False` in `celery.py`.

This task, most probably, requires switching to [manual routing](http://docs.celeryproject.org/en/latest/userguide/routing.html#manual-routing) in `celery.py`

**Comment by cameel** [comment]
I don't think this requires manual routing. In fact, we don't want manual routing.

There's a section above that shows how to define queues without switching to manual routing: [Routing Tasks > How the queues are defined](http://docs.celeryproject.org/en/latest/userguide/routing.html#how-the-queues-are-defined).

**Comment by kbeker** [comment]
Already resolved in: https://github.com/golemfactory/concent/pull/638
