### ISSUE TITLE
Concent still uses numeric types in error messages

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#457]
#296 is back. Here's an example of an error message seen in the wild (#455):
```
{
    "error":      "There was an exception when validating if golem_message 2002 is signed with public key b'|\\xcc\\xfa\\x1d<\\xa1\\x9b{\\xc4\\xedp\\xcb\\xfb\\x0b\\x89$~\\x05\\xae\\x06c3\\xe6\\x9az\\xf3\\x95\\xe3\\x83\\xbc\\x16\\xe1,m0\\x1ah5\\xae\\x14,\\x17Op\\x82\\x9a\\xd9\\xd4\\xaex3hc;\\xe0@\\xee\\xad\\xe5\\x92\\xca\\xee\\xd3\\x8c'",
    "error_code": "message.signature.wrong"
}
```

This message contains a numeric message type (2002) instead of the name of the message (`ForceReportComputedTask`).

Please fix it and also review the code around to ensure that we're always printing message names.

**Comment by pawelkisielewicz** [comment]
Resolved in pull request: https://github.com/golemfactory/concent/pull/569
