### ISSUE TITLE
Make verification mock for cluster testing

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#475]
Introduce a temporary setting in `base.py`: `MOCK_VERIFICATION_ENABLED=True` that will allow some testing on cluster.
1. If the flag is enabeld blender verification should
 -  return `VerificationResult.MATCH` if the last char of `subtask_id` is equal to `m`
- return `VerificationResult.MATCH` otherwise

2. If the flag is disabled - verification should work normally

**Comment by cameel** [comment]
Please set it to `True` by default. I said `False` because I thought we were talking about something like `ENABLE_VERIFIER` that disables the unfinished code when set to `False` :)
