### ISSUE TITLE
5xx errors are returned as HTML by default

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#488]
In #57 we implemented middleware that replaces HTML pages for 5xx errors with JSON equivalents. JSON should be returned by default as can be seen in [determine_return_type()](https://github.com/golemfactory/concent/blob/v0.7.1/concent_api/concent_api/middleware.py#L55-L65). @shadeofblue reports that he still gets the HTML pages on staging even though he's not sending the `Accept` header.

**Comment by cameel** [comment]
Actually, @shadeofblue could you verify that you're not sending the `Accept` header? Maybe requests is including one by default?

**Comment by rwrzesien** [comment]
@cameel `requests` does not but `curl` is, and this header has value `*/*`, and `best_match` returns `text/html` for it. I can add condition which will return `application/json` for this value. What are your thoughts on that ?

**Comment by cameel** [comment]
It should choose `application/json` in any situation where both it and `test/html` have the same `q` value. `*/*` is only a special case of this.

Also, aside from the `q` value there's also specificity. `*/* is less specific than `text/*` which is less specific than `text/html`. The value with higher specificity should be chosen.

>  Media ranges can be overridden by more specific media ranges or specific media types. If more than one media range applies to a given type, the most specific reference has precedence. For example,
> 
>        Accept: text/*, text/html, text/html;level=1, */*
> 
> have the following precedence:
> 
>        1) text/html;level=1
>        2) text/html
>        3) text/*
>        4) */*

[RFC 2616 Hypertext Transfer Protocol -- HTTP/1.1 > 14 Header Field Definitions > 14.1 Accept](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1)

What does it do e.g. when the header is `text/html; */*`? It should chose HTML then because it's more specific. The hack you propose would not cover that.
