### ISSUE TITLE
Missing `ResultsFailed` field in Origin in `SubtaskResultsSettled`

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#500]
It should be added field `ResultsFailed` in Origin enum in `SubtaskResultsSettled` message.
This information should also be added in golem_messages

**Comment by dybi** [comment]
PR for `golem_messages`: https://github.com/golemfactory/golem-messages/pull/232

**Comment by dybi** [comment]
closing as not applicable anymore (misunderstood specs)
