### ISSUE TITLE
Wrap all Celery tasks in transactions

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#512]
We have a mechanism that starts a database transaction when a view starts executing, commits it on success or rolls back on error. We need the same mechanism in our Celery tasks.

It can be achieved by simply putting the `@atomic` decorator on every task handler.

**Comment by rwrzesien** [comment]
@cameel Another common problem is that often task is being run in the middle of the current transaction and tries to read/write same data that current transaction, which results in exception. It can be avoided by running task using `on_commit` hook from Django, then the task is run after current transaction finishes. However, I went through our current code and currently didn't find a situation when task is trying to modify the same data as the code which runs it. But do we want to add this for the future ?

**Comment by cameel** [comment]
We do. But not with any Python-level mechanisms like `on_commit`. #412 is all about dealing with this problem.
