### ISSUE TITLE
Rendering image fragment in verifier

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#520]
Currently Verifier tries to render the whole image defined in the `.blend` file. This is not the correct approach because in most cases the goal of a single subtask is to render only a fragment of that image, to be later joined with other fragments rendered by other providers.

[A typical `TaskToCompute` message](https://github.com/golemfactory/concent/issues/235#issuecomment-378525017) contains two scripts:
- `src_code` - a Python script to be executed by Golem inside the docker image. It gets a few parameters from `TaskToCompute` (via a `params.py` module generated by Golem) and runs Blender.
- `script_src` - a Python script to be executed by Blender. It's generated by rendering [blendercrop.py.template](https://github.com/golemfactory/golem/blob/develop/apps/blender/resources/scripts/blendercrop.py.template) with parameters like size of the image, crop window, etc. `src_code` script writes `script_src` to a file called `blenderscript.py` and passes its path to Blender.

To render just the fragment we must pass the `src_code` script to Blender using `-P` option and enable scripting with `-y`.

The purpose of this task is to send the whole script from the control cluster to the verifier and just let Blender execute it. This is not a good design from the security standpoint (the script comes from the client) but will get the job done. There will be a separate task for making this mechanism more secure by allowing only whitelisted scripts.

Steps to do:
- Get the value of `script_src` value from `TaskToCompute` included in `SubtaskResultsVerify` and pass it along to the verifier.
    - Add `blender_crop_script` parameter to `blender_verification_request` and `blender_verification_order` Celery tasks. It should contain the value from `script_src`. 
    - Add `blender_crop_script` field to `BlenderSubtaskDefinition` model.
- In verifier pass the script to Blender.
    - Remove the script after rendering to make sure that the next task does not reuse it.

**Comment by rwrzesien** [comment]
As resolving this issue requires data migration which crates non-null field `blender_crop_script`, I have following data migration propositions:
- add default ''
- update it with data extracted from related Subtask and its stored messages, but this will require having both `control` and `storage` databases available.

**Comment by cameel** [comment]
We've been using hard-coded `''` so far so putting `''` in existing objects is true to what has already been happening. Those subtasks will not render with the right crop but they would not have rendered properly before either so it's fine. It does not fix anything but also does not break anything that was working already.

**Comment by rwrzesien** [comment]
@cameel If you have time please update https://github.com/golemfactory/concent/issues/193 on new field for `BlenderSubtaskDefinition`.

**Comment by cameel** [comment]
Updated. I have also included changes from #537.

**Comment by rwrzesien** [comment]
@cameel What should happen if compute_task_def `extra_data` is missing `script_src` ?

**Comment by rwrzesien** [comment]
@cameel What should happen if `ComputeTaskDef` doesn't contain 'script_src' in 'extra_data' ?
