### ISSUE TITLE
Refactor blender_verification_order task

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#524]
@dybi Original comment from https://github.com/golemfactory/concent/pull/441#discussion_r195663586

> this whole task has grown dramatically. There's a lot of logic and for me it is very hard to follow what's going on. I would really instist on having it refactored in a way that small functions are extracted and the task consits of calls to such small functions.

One of the proposals is to hide implementation into smaller functions. Exceptions handling will work this way:
- on cought exception, smaller functions will raise custom exception, ie. `VerificationFinishedPrematurelyError` with error message and error code.
- `VerificationFinishedPrematurelyError` will be cought in main task try/except code, except block will call `verification_result.delay`with extracted error message and error code.

If any other refactor proposals appear please add them here.

**Comment by dybi** [comment]
task done under: https://github.com/golemfactory/concent/issues/549
