### ISSUE TITLE
Verification of image sequences

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#537]
A subtask may involve rendering more than one frame. Even if there's only one frame this might not necessarily be the first frame. We need to take it into account and render the right frames during verification.

`TaskToCompute.compute_task_def.extra_data.frames` specifies frame numbers to be rendered.

To tell Blender to render a specific frame use the `-f` option. Don't use `-s`/`-e` - this will render multiple frames into a video file which is not what we want. Each frame should be a separate image.

#### Concent Core
Concent Core should validate `TaskToCompute.compute_task_def.extra_data.frames`
- It's a list
- Each frame number is a non-negative integer

#### Conductor
- Add `frames` parameter to `blender_verification_request` and `blender_verification_order`. It should be the list of frames.
- Add `Frame` model to the `storage` database with the following fields:
    - `blender_subtask_definition`: foreign key to `BlenderSubtaskDefinition`, non-null.
    - `number`: int, non-null.
    - `BlenderSubtaskDefinition` and `number` must be unique together.

#### Verifier
- Immediately after unpacking the result package from provider:
    - Parse file names in the archive to determine which frames are present.
    - Compare the frame numbers present there with the ones received in `blender_verification_order`.
        - If any of the frames listed in the order is not present, report mismatch and end verification.
        - If there are more frames than necessary, log a warning but continue verification.
- Run Blender separately for each frame.
    - Run only one Blender process at a time. Don't start rendering the next frame until the previous one finishes.
    - The number of threads used by Blender for rendering each frame should be a setting: `BLENDER_THREADS`, int, default = 1.
- Upload all rendered frames to the storage server (as separate files)
- Compare all the frame pairs.

### Frame names in the result package
Please try to run Golem with a rendering task containing multiple frames. Look into the archive it produces and see how the frames are named.

**Comment by cameel** [comment]
Description updated. The frame names I got don't appear to be right. We need to run Golem and find out how they're named.

**Comment by cameel** [comment]
Description updated to match my changes in #193. `Frame` contains a foreign key to `BlenderSubtaskDefinition`, not `VerificationRequest`.

**Comment by kbeker** [comment]
@cameel 
```Compare the frame numbers present there with the ones received in blender_verification_order. If they don't match, report mismatch and end verification.```
It is obvious that when we have stored e.q. Frames [1,2,3] and we get results zip which won't have even one of these is MISMATCH, but
If we have same situation as above that we stored Frames [1,2,3] but we get results zip with franes [1,2,3,4]. Should it also be MISMATCH?

**Comment by cameel** [comment]
Good point. Let's log something at the WARNING level and proceed. If frames 1, 2 and 3 are correct then it's fine. Does not matter what else requestor gave us (I'm pretty sure Golem would ignore other frames too). If they do not match then we'll return an error anyway.

**Comment by kbeker** [comment]
@cameel Should frames be checked in every use case where TaskToCompute is?

**Comment by cameel** [comment]
You mean: "should the list of frame numbers in `TaskToCompute` be validated together with the whole `TaskToCompute` at the begginning of every use case"?

Yes.
