### ISSUE TITLE
Requestor doesn't receive ForcePaymentCommitted

### ISSUE THREAD

**Issue by jiivan** [golemfactory/concent#546]
Requestor should receive his own copy of `ForcePaymentCommitted`.

**Comment by rwrzesien** [comment]
@jiivan Could you please provide more details ? Currently `ForcePaymentCommitted` can be received by requestor from `receive-out-of-band` endpoint.

**Comment by jiivan** [comment]
Sure. Pls run `test_force_payment_commited` from https://github.com/golemfactory/golem/blob/uc5_force_payment/scripts/concent_integration_tests/force_payment/test_payment.py

It waits 10 seconds after receiving `ForcePaymentCommitted` by provider and tries to receive it by requestor.

**Comment by rwrzesien** [comment]
@jiivan I have followed up the code, in https://github.com/golemfactory/golem/blob/uc5_force_payment/golem/network/concent/client.py#L129 you are declaring endpoint to `receive`, but this message can be currently received by requestor only from `receive-out-of-band`.

**Comment by rwrzesien** [comment]
In documentation there is:
> Wysyła do Requestora powyższy komunikat MessageForcePaymentCommitted z flagą, że jest to komunikat do Requestora, jako pozaprotokołowy długotrwały komunikat.

**Comment by jiivan** [comment]
I've fixed test to use `receive-out-of-band`. Issue solved.
