### ISSUE TITLE
24-hour time in admin panel

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#552]
Currently the admin panel displays date and time as e.g. `June 25, 2018, 1:26 p.m.`. Configure Django to use 24-hour time format: 13:26.

While at it, the ISO format for dates (2018-06-25) might be more readable too.

Preferably this should be done in the global configuration rather than for every field separately.

**Comment by rwrzesien** [comment]
Definitely something that can be achieved using only Django settings

**Comment by rwrzesien** [comment]
@cameel Where in admin panel have you seen this exactly ?

**Comment by cameel** [comment]
On the subtask list. There's a column that shows `next_deadline`.
