### ISSUE TITLE
Show creation and modification time in the admin panel

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#553]
Currently the creation and modification time of a subtask is not displayed on the subtask list in the admin panel. This might be useful for other models too, like `PendingResponse` or `StoredMessage`.

Add the missing columns.

**Comment by cameel** [comment]
Well, it's easy enough to add them to the column list. It's simpler if you can see all the fields at a glance and there's nothing hidden. It also lets you easily control their position.

I have nothing against mixins but it might be an overkill in this case.

**Comment by rwrzesien** [comment]
I have misread the description, I thought we want to add them to models.

**Comment by rwrzesien** [comment]
Actually only one of the models has only `created_at` field. I think it is a good practice in Django to have most of the models both of those fields, so I have added `BaseModel` class containing those two fields and made other models inherit from it.

**Comment by cameel** [comment]
It's better to have them by default than not to have them at all. But that's just an easy solution for when you don't want to think about them too much. They are not always needed and I'm adding them only to models that actually need them.

Sometimes there's another timestamp field that already stores creation or modification date. Sometimes we need different timestamps (e.g. the time when a transaction was submitted). And sometimes adding them makes the object unnecessarily heavy - for example why would we need creation and modification date for each row that stores a frame number for the verifier? It's enough to store it for the `VerificationRequest` itself.

So let's keep it as is. If you think there are models that should have the timestamps but don't have them now, tell me and I'll add them to the spec.

**Comment by rwrzesien** [comment]
> for example why would we need creation and modification date for each row that stores a frame number for the verifier?

This is a good example where it is not necessary, however in most cases I think it is good for debugging. I think sooner or later this information will become helpful and it would be better to already have it. As I have said, it is only matter of good practice.

> Sometimes there's another timestamp field that already stores creation or modification date. 

That is one of the reasons of doing this in master class - they get unified and stay consistent. 

> Sometimes we need different timestamps (e.g. the time when a transaction was submitted).

There is no problem with having both.

> So let's keep it as is. If you think there are models that should have the timestamps but don't have them now, tell me and I'll add them to the spec.

Ok, so my proposal is to add them to:
- StoredMessage
- Client
- Subtask
- PendingResponse
- PaymentInfo
- VerificationRequest
- BlenderSubtaskDefinition
- UploadReport

and not add them to:
- Frame

If you disagree with any we can discuss each other separately.

**Comment by cameel** [comment]
> >  Sometimes there's another timestamp field that already stores creation or modification date.
>
> That is one of the reasons of doing this in master class - they get unified and stay consistent.

Not if it has a different name. I mean a situation where there's a timestamp that's for a different purpose but effectively is as useful as creation or modification date. For example the `timestamp` field in `StoredMessage`.

> Sometimes we need different timestamps (e.g. the time when a transaction was submitted).
>
> There is no problem with having both.

I think that it would be be confusing to have multiple fields for the same purpose.

> Ok, so my proposal is to add them to:
> - StoredMessage

It already has a timestamp from the message. And it's not supposed to be modified so it does not need a modification timestamp.

Well, technically this is the timestamp created by the client and his clock may be out of sync so we could add creation timestamp to be able to cross-check it.

> - Client

I don't see the point of having it here, but I'm not strongly against it.

> - Subtask

Yeah, this one should have the timestamps.

> - PendingResponse
> - UploadReport

They already have the creation timestamp. They do not need modification timestamp because they're never supposed to be modified.

> - VerificationRequest

This one looks like my mistake. I should have put the timestamp in `VerificationRequest` not in `BlenderSubtaskDefinition` (which conceptually inherits from `VerificationRequest`).

> - BlenderSubtaskDefinition
> - PaymentInfo

These models are related to a "parent" model that already has a timestamp (this is a relation that works like inheritance). They're read-only so they do not need a modification timestamp.


Anyway, this discussion is off-topic here. The issue is about adding the existing timestamps to the admin panel, not changing the models. We can continue in #604 (which contains my current suggestions). Let's continue there and close this issue without adding new timestamp fields until we agree on that.

**Comment by rwrzesien** [comment]
@cameel So to finish this task I will only `PendingResponse.created_at` and `StoredMessage.timestamp`, because others do not exist right, and lets discuss in #604.
