### ISSUE TITLE
Verification timeout not based on protocol times

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#556]
Currently the timeout for additional verification (as stated in #165) is `SubtaskResultsRejected.timestamp` + AVCT. This was based on Łukasz's spec but later it turned out that this was just a hint and is not considered a part of the protocol. The requirement is simply that we should give verification enough time to have a high chance of not hitting the timeout while not being unreasonably long.

 Moreover, since we're rendering the whole scene (until a more reliable verification method is devised) we may need to set the maximum rendering time to more than AVCT.

For that reason we'll replace the current timeout with a custom one. We'll base our timeout on how long the task normally takes to compute:
- Add a setting called `ADDITIONAL_VERIFICATION_TIME_MULTIPLIER`
    - Type: float
    - Non-empty
    - Default value of 2, set in `base.py`.
- Time for additional verification should be computed as `(TaskToCompute.deadline - TaskToCompute.timestamp) * ADDITIONAL_VERIFICATION_TIME_MULTIPLIER / BLENDER_THREADS` (see #537 for info about `BLENDER_THREADS`).
    - Put this in a function called `additional_verification_call_time()`.
    - Remove `ADDITIONAL_VERIFICATION_CALL_TIME` setting that's now obsolete (the function replaces it).
- Define a value for `ADDITIONAL_VERIFICATION_TIME_MULTIPLIER` in [concent-deployment](https://github.com/golemfactory/concent-deployment) when `fast_timing` is enabled.

**Comment by rwrzesien** [comment]
@cameel Should `ADDITIONAL_VERIFICATION_CALL_TIME` setting be removed ? It will be no longer used after this change.

**Comment by rwrzesien** [comment]
@cameel What do you mean by `Non-empty` in context of the `float` ?

**Comment by cameel** [comment]
@rwrzesien 
> Should `ADDITIONAL_VERIFICATION_CALL_TIME` setting be removed ? It will be no longer used after this change.

Interesting. I missed it. Yes, let's remove it and call the function that computes the time `additional_verification_call_time()` - it still serves the same purpose but it's not a constant.

> What do you mean by `Non-empty` in context of the `float` ?

Defined and not `None`. When I say "empty"/"non-empty", "required"/"optional" rather than explicitly "not `None`", "not `""`" or defined it's because I do not want to go into implementation details. Sometimes multiple empty values are allowed, sometimes not. Sometimes field or setting may be missing. Sometimes we know that it's present. Decide based on context.

**Comment by rwrzesien** [comment]
> Defined and not None.

Ok, for me saying `Type: float` implies `not None`.
