### ISSUE TITLE
Stateless Bankster: settle-overdue-acceptances operation

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#565]
This is a part of the implementation of the "Stateless Bankster" blueprint (#564).

1. **`settle-overdue-acceptances` operation**
2. **Use the new operation in Concent Core**
    - Replace the current code that computes the amount to pay and submits an Ethereum transaction with a call to the new operation.
        - Concent Core should still be responsible for decoding golem messages, validating their signatures, timestamps and content.
        - Bankster should be responsible for any calls to SCI and any calculations of amounts to be paid.
        - Concent should still be responsible for generating responses and adding them to the receive queue.
    - Generate responses based on the response from the operation.

#### Input
| Parameter                       | Type                        | Optional | Remarks                                                                                                                 |
|---------------------------------|-----------------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `requestor_ethereum_address` | string                      | no       | Address of the Ethereum account belonging to the requestor. Cannot be the same as `requestor_ethereum_address`. Comes from `TaskToCompute`.
| `requestor_ethereum_address`  | string                      | no       | Address of the Ethereum account belonging to the provider. Cannot be the same as `requestor_ethereum_address`. Comes from `TaskToCompute`.
| `acceptances`                   | list of `SubtaskResultsAccepted` | no       | List of `SubtaskResultsAccepted` golem messages describing each acceptance. The list must contain at least one object.

#### Output
| Parameter                       | Type                        | Optional | Remarks                                                                                                                 |
|---------------------------------|-----------------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `requestors_claim_payment_info` | `ClaimPaymentInfo`          | yes      | Information about the payment made from requestors's deposit. Empty if and only if the claim against requestors's deposit is zero.

#### Sequence of operation
1. **Deposit query**:
    - Bankster asks SCI about the amount of funds available in requestor's deposit.
2. **Claim calculation**:
    - Bankster sums up the amount specified in acceptances.
    - Bankster asks SCI for the list of all relevant payments listed on the blockchain (both normal payments performed by the requestor and forced payments performed by Concent).
    - Bankster computes the amount that is still owed to the provider.
    - Bankster compares the amount with the available deposit.
        - If the whole amount can't be paid, Concent lowers it to pay as much as possible.
3. **Payment calculation**: Bankster reduces the amount to be paid if there's not enough funds in the deposit.
    - If the deposit is zero, the payment is reduced to zero.
    - Otherwise if the deposit does not have enough funds to cover the whole claim, the payment is reduced to the size of the deposit.
4. **Transaction**:
    - If claim is zero, `requestors_claim_payment_info` is empty.
    - Otherwise if claim is non-zero but the deposit is empty, Bankster creates `ClaimPaymentInfo`
        - `tx_hash`: empty
        - `payment_ts`: empty
        - `amount_paid`: 0
        - `amount_pending`: the full amount claimed
    - Otherwise:
        - Bankster uses SCI to create an Ethereum transaction.
        - Bankster creates `ClaimPaymentInfo`
            - `tx_hash`: hash of the transaction
            - `payment_ts`: timestamp when Concent called SCI to create the transaction
            - `amount_paid`: the amount to be paid
            - `amount_pending`: full amount claimed minus the amount paid
5. **Response**: Bankster returns the created `ClaimPaymentInfo` object.

**Comment by rwrzesien** [comment]
@cameel 
> The SCI singleton should only exist in Bankster. Maybe would be a good idea to define an entry in CONCENT_FEATURES for it?

If it exists **only** in Bankster then I think Bankster in CONCENT_FEATURES is enough for now.

> Make sure that Concent Core works without access to Geth (it won't be configured for it it in deployment; only Bankster will).

All our integration and cluster tests pass when payment backend is set to mock, so I consider this to be enough check. Or maybe you think about something else which can be done to verify this ? @kbeker maybe you have an idea ?

**Comment by rwrzesien** [comment]
Changed to match #564 update, which is endpoint replaced by operation.

Renamed parameters:
`requestor_ethereum_public_key` => `requestor_ethereum_address`
`provider_ethereum_public_key` => `provider_ethereum_address`

Changed `acceptances` parameter accept list of `SubtaskResultsAccepted` golem messages instead of list of dicts.

Changed the way on how `payment_ts` is passed to `ClaimPaymentInfo` in `Sequence of operation 4.Transaction`. As there is no such or similar value in `ethereum.Transaction` object, it will be generated in Concent when it calls SCI for creating transaction.

Removed info about `Internal API validations`.

Removed info about making `bankster` separate value in `CONCENT_FEATURES`, as the current solution with pluggable backends works in similar way.
