### ISSUE TITLE
Stateless Bankster: claim-deposit operation

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#567]
This is a part of the implementation of the "Stateless Bankster" blueprint (#564).

The description below assumes that this is being implemented after #565. If not, you'll have to do a few additional steps described in that issue first (creating `bankster` app, extracting SCI, etc.)

1. **Implement `claim-deposit` operation**
 2. **Use the new operation in Concent Core**
    - Replace the current code that checks if there's enough deposit in the `ForceAcceptance` and `AdditionalVerification` use cases with a call to the new operation.
         - Split responsibilities as described in #565: Concent Core keeps communication with the client, Bankster does all the calculations and communication with the blockchain via SCI.        

#### Input
| Parameter                       | Type                  | Optional | Remarks                                                                                                                 |
|---------------------------------|-----------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `concent_use_case`              | `ConcentUseCase`      | no       | Use case in which Concent claims the deposit.
| `requestor_ethereum_address` | string                | no       | Address of the Ethereum account belonging to the requestor. Cannot be the same as `provider_ethereum_address`. Comes from `TaskToCompute`.
| `provider_ethereum_address`  | string                | no       | Address of the Ethereum account belonging to the provider. Cannot be the same as `requestor_ethereum_address`. Comes from `TaskToCompute`.
| `subtask_cost`                  | int               | no       | The cost of performing the work on the subtask that the requestor has agreed to pay the provider. Comes from `TaskToCompute.price`. Must be greater than zero.

#### `ConcentUseCase` enum
- `ForcedAcceptance`
- `AdditionalVerification`
- `ForcedPayment`

#### Output
| Parameter                       | Type                  | Optional | Remarks                                                                                                                 |
|---------------------------------|-----------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `requestor_has_enough_deposit`  | bool                  | no       | `True` if requestor currently has enough funds in his deposit to pay.
| `provider_has_enough_deposit`   | bool                  | no      | `True` if provider currently has enough funds in his deposit to pay.

#### Sequence of operation
1. **Claim calculation**: Bankster determines the amount that needs to be claimed from each account:
    - In `ForcedAcceptance` use case:
        - Requestor may have to pay `subtask_cost`.
        - Provider does not pay anything.
    - In `AdditionalVerification` use case:
        - Requestor may have to pay `subtask_cost`.
        - Provider needs to pay verification cost (which is constant and determined by Concent's settings).
2. **Deposit query**:
    - Bankster asks SCI about the amount of funds available in requestor's deposit.
    - If the amount claimed from provider's deposit is non-zero, Bankster asks SCI about the amount of funds available in his deposit.
3. **Requestor's spare deposit check**:
    - **Claims against requestor's deposit can be paid partially** because the service has already been performed by the provider and giving him something is better than giving nothing.
        If the requestor's deposit is zero, we can't add a new claim.
        `requestor_has_enough_deposit` is `False`.
    - Otherwise `requestor_has_enough_deposit` is `True`.
4. **Provider's spare deposit check**: If the amount claimed from his deposit is non-zero.
    - **Claims against provider's deposit must be paid in full** because they're payments for using Concent and we did not perform the service yet so we can just refuse.
      If the provider's claim is greater than his current deposit, we can't add a new claim.
        - `provider_has_enough_deposit` is `False`.
    - Otherwise `provider_has_enough_deposit` is `True`.
5. **Result**: If everything goes well, the operation returns.
     - Bankster returns the tuple of values of `requestor_has_enough_deposit` and `provider_has_enough_deposit`.

**Comment by rwrzesien** [comment]
Renamed parameters:  
`requestor_ethereum_public_key` => `requestor_ethereum_address`
`provider_ethereum_public_key` => `provider_ethereum_address`

**Comment by dybi** [comment]
@rwrzesien It looks good, apart from
> Changed return type to `bool`.

the type of what is being changed and what was the return value initially?

**Comment by rwrzesien** [comment]
@dybi Please check the current blueprint https://github.com/golemfactory/concent/issues/564 => `claim deposit` => `output`. As I understand, currently it should be tupple, ie. `(True, True)`, but as we use this result directly in `if` statements only I think it should be casted to `bool` before returning .

**Comment by rwrzesien** [comment]
After discussion, reverted the return type to `tuple` of `requestor_has_enough_deposit` and `provider_has_enough_deposit`.
