### ISSUE TITLE
Returning JSON on HTTP 5xx errors

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#57]
Currently in case of an exception Concent API and gatekeeper return a HTML page that just says "Internal Server Error". When `DEBUG=True` the page contains more information but I don't think we want to run with `DEBUG` enabled on the cluster.

1) We want a JSON response rather than HTML
2) The response should contain an error message and error code
3) In production mode we want just a generic message. In development we also want to include stack trace and exception message.
    - Add a separate setting to switch between these modes (`DEBUG_INFO_IN_ERROR_RESPONSES` or something like that). If the setting is not defined its value should be the same as `DEBUG`. But it should be possible to set it independently.

You'll probably have to catch all exceptions in views to achieve this. Or create a middleware. In any case, keep in mind that in case of an error you have to roll back the current database transaction.

Please remember that this middleware should be turned off when running tests.

**Comment by rwrzesien** [comment]
@dybi Let me put some thoughts to it:
`handle_errors_and_responses` - yes, that would be a good place to put it, however you won't be able to reuse it in other views, as `gatekeeper` and `conductor` handle their errors in different way.
So if you want to extend this error handling on all views, I would suggest either middleware as you have proposed, or a new decorator, which will be put on top of all others, only for catching and handling 500 of everything below.

**Comment by cameel** [comment]
After this is merged, we should enable the extra info on our development clusters: https://github.com/golemfactory/concent-deployment/issues/120

**Comment by cameel** [comment]
@rwrzesien Actually `handle_errors_and_responses` is pretty generic now. I think it would be a good idea to use it on all API views. Some views don't need all of its features (for example support for encoding Golem messages is not necessary in gatekeeper) but having them there does not hurt.

As for decorator vs middleware: there's also a third option - [handler500](https://docs.djangoproject.com/en/2.0/topics/http/views/#customizing-error-views). We could override it to provide custom error 500 "page" that's just a piece of JSON. If possible, we want to use this because it extends Django's mechanism rather than just replace it.

The goal here is never to return HTML for HTTP 500 in our API views because the client will simply not be able to get any useful information out of that. Does not really matter where the error comes from, only that if the client is accessing an API URL we should try hard never to give it HTML. Middleware seems more comprehensive in that regard because we can handle stuff coming from the middleware too.

There's also a case that I forgot to mention in the description: the admin panel. It's would be best to keep HTML error pages in the admin if possible. So we should actually look at the `Accept` header to decide what we should return.

**Comment by rwrzesien** [comment]
> @rwrzesien Actually handle_errors_and_responses is pretty generic now. I think it would be a good idea to use it on all API views. Some views don't need all of its features (for example support for encoding Golem messages is not necessary in gatekeeper) but having them there does not hurt.

Ok, just please be careful when changing anything there, as it has influence on core Concent behaviour.

**Comment by rwrzesien** [comment]
Added request to remove catching 500 in tests.

**Comment by cameel** [comment]
@dybi asked about clarification for my proposal with the [`Accept` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept).

Client sends a request which may include a HTTP header called `Accept`. The header lists content types that the client can process. It could look like this: `text/html, application/xhtml+xml, application/xml;q=0.9, */*;q=0.8` which means that the client can process HTML, XHTML, XML or any other format but prefers (X)HTML to plain XML and will accept a format other than those three if they're not available.

The server uses this as a recommendation when deciding which `Content-Type` to use when responding to the request. For example if the server can return the same data as HTML, CSV or JSON the client can use `Accept` header to select one of them. This is particularly useful when we want to support both a human using a browser and an automated client. The former will prefer HTML while the latter may want to get all the data as JSON because parsing it out of the HTML version is never reliable.

The `*/*` part is not mandatory. If it's missing and none of the supported `Content-Type`s can be found in the `Accept` header the server can respond with [HTTP 406 NOT ACCEPTABLE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406).

It's not defined what should happen if `Accept` header is missing. We can treat it as the client not specifying any preference and use our default format. This could be just HTML or could depend on whether one is accessing the API or the admin panel.

In our case I think that we should expect a Golem client to set `Accept` to something like `application/octet-stream, application/json;q=0.9, */*;q=0.8`. This way we don't have to hard-code the response to JSON. We can generate a HTML or JSON error according to client's preference.

**Comment by dybi** [comment]
@cameel 
> The */* part is not mandatory. If it's missing and none of the supported Content-Types can be found in the Accept header the server can respond with HTTP 406 NOT ACCEPTABLE.

This looks like another wrapper/middleware. Shall I handle it in the same issue?

**Comment by cameel** [comment]
Yeah. Sure. This might be a generic utility.

But it should let you list additional content types that might be returned by the view. And the view may still need to return HTTP 406 if the client wants JSON and it cannot return it.
