### ISSUE TITLE
NoneType in ForceGetTaskResultUpload handling

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#578]
Probably migration issues - while creating `ForceGetTaskResultUpload`:
 - before v0.7.3, concent created new 'ForceGetTaskResult' based on stored `ReportComputedTask`
- since v0.7.3, cocent creates `ForceGetTaskResultUpload` based on stored `ForceGetTaskResult` - in case client had sent `ForceGetTaskResult` before, it hasn't been stored

Fix:
check if ForceGetTaskResult is stored in DB, if not create it

**Comment by rwrzesien** [comment]
@dybi How about resolving this using data migration ? This way it will be executed only once on given environment and you don't have to modify existing Concent core code.

**Comment by dybi** [comment]
ok, I didn't get you point before, now I get it:) I will do it in migration, as suggested.

**Comment by cameel** [comment]
Just for reference: The original issue that was missing a migration was #531.

**Comment by cameel** [comment]
I'm removing the `compatibility-hack` label since we did it with a migration after all.
