### ISSUE TITLE
Add annotations for `blender_verification_order` (verifier) helper functions

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#583]
functions that (for sure) need annotations:
- `download_archives_from_storage`
- `validate_downloaded_archives`
- `unpack_archives`
- `render_image`
- `delete_source_files`
- `try_to_upload_blender_output_file`
-  `load_images`
- `compare_images`

**Comment by PaweuB** [comment]
'Not in pivotal' label but resolved in PR #549 ?
What's about considering a new label for Issues resolved like above (e.g. 'included in other PR')? If something was done in parallel. 
Then it will be two labels for Issues like this ('not in pivotal' + 'included in other PR') providing information that it's done and needs no action in Pivotal.
