### ISSUE TITLE
DatabaseTransactionsStorage for smart-contracts-interface

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#584]
golem-smart-contracts-interface needs to keep some local state - a list of pending transactions and a nonce. This state is kept in an object that implements the [TransactionsStorage](https://github.com/golemfactory/golem-smart-contracts-interface/blob/v1.4.2/golem_sci/transactionsstorage.py#L16-L53) interface. To protect multiple instances of SCI using the same contract from race conditions the implementation of this interface should allow sharing the state between instances.

The default implementation ([JsonTransactionsStorage](https://github.com/golemfactory/golem-smart-contracts-interface/blob/v1.4.2/golem_sci/transactionsstorage.py#L56-L143)) keeps data in a file on disk (`transactions.json`). Since each instance of Concent runs in a separate container, this is not enough to provide shared state.

### `DatabaseTransactionsStorage`
We need to create a new implementation that stores its state in the database. The database structure is as follows:

#### `GlobalTransactionState` model
| Field                           | Type      | Size           |
|---------------------------------|-----------|----------------|
| `nonce`                         | int       | up to 32 bytes |

There should always be at most one object of this type with `id = 0`. If it does not exist, it should be created and `nonce` initialized with a value obtained from SCI (`Client.get_transaction_count()`).
- Use the typical get-or-create pattern - try to get it from the database and create a new one if it does not exist. Since the `id` is unique, it will fail if another process tries to create it at the same time. When that happens just retry your query and use the object created by the other process.

#### `PendingEthereumTransaction` model
| Field                           | Type      | Size           |
|---------------------------------|-----------|----------------|
| `nonce`                         | int       | up to 32 bytes |
| `gasprice`                      | int       | up to 32 bytes |
| `startgas`                      | int       | up to 32 bytes |
| `to`                            | string    | 20 bytes       |
| `value`                         | int       | up to 32 bytes |
| `data`                          | binary    | unlimited      |
| `v`                             | int       | 1 byte         |
| `r`                             | int       | 32 bytes       |
| `s`                             | int       | 32 bytes       |
| `created_at`                    | timestamp |                |

Names are the traditional ones for Ethereum transaction fields. See the definition of [Transaction class in pyethereum](https://github.com/ethereum/pyethereum/blob/develop/ethereum/transactions.py#L20-L50).

Make sure to use a type that can store 32-byte integers. For more info about sizes see [What is the size (bytes) of a simple Ethereum transaction versus a Bitcoin transaction?](https://ethereum.stackexchange.com/questions/30175/what-is-the-size-bytes-of-a-simple-ethereum-transaction-versus-a-bitcoin-trans)

#### Implementation details
- The implementation should be defined in Concent's code (not in SCI) since it depends on Django.
    - It might be a good idea to create a separate Django app for it.
- It should use database locks to prevent multiple instances from modifying the same data.
    - `GlobalTransactionState` is the one that should be locked. While it's locked, no other instance can change it or add/remove/modify transactions.
- Every function of the storage object should be running inside a transaction (even if the code outside is not). This will ensure that the lock is released if an exception interrupts the operation.
- An instance of our storage implementation should be passed as a parameter to `SCIImplementation`'s constructor.

**Comment by rwrzesien** [comment]
@cameel Should it use 'control' database ?

**Comment by cameel** [comment]
> 1. Should it use 'control' database ?

Yes. It's running on the control cluster so it can't use the storage database.

> 2. Are the types in `GlobalTransactionState` correct ? In the link which you have added there is a sample data but those values are not ints.

`big_endian_int` is just a custom class that represents an integer of arbitrary size (stored in big-endian order but that's not really relevant here). So conceptually it's an int. You of course may have to convert between this type, Python's int and the int representation in the database but that's an implementation detail.

> 3. `up to 32 bytes` do you mean `BIGINT` type in postgres ?

I don't mean anything. I'm only stating requirements. Use whichever type that satisfies these requirements.

**Comment by rwrzesien** [comment]
@cameel 

Do we want soft delete when removing or reverting transactions ?

**Comment by rwrzesien** [comment]
> 5. I have compared what is in the link you have provided and what is in golem tests for Transaction class (there is only limited data there -> https://github.com/golemfactory/golem-smart-contracts-interface/blob/v1.4.2/tests/test_storage.py) and I am a little bit confused on how sample full data passed to Transaction class should look like. Do you know maybe when I can find this info ?

Sample data stored by JsonTransactionsStorage
```
"2122": {
    "nonce": 2122, 
    "gasprice": 1000000000,
    "startgas": 80000,
    "to": "0x694667d7787cfca1892606e81734860a617537b2",
    "value": 0,
    "data": "0xfc32339a000000000000000000000000296b69c878a7498ef4c4516465213edf84fc4b300000000000000000000000003413d761a5c2c3bea075170d32965fcaa8ba053c0000000000000000000000000000000000000000000000000000000000002710000000000000000000000000000000000000000000000000000000005b436d6f",
    "v": 28,
    "r": 105276041803796697890139158600495981346175539693000174052040367753737207356915,
    "s": 51455402244652678469360859593599492752947853083356495769067973718806366068077
}
```

**Comment by cameel** [comment]
> 4. Do we want soft delete when removing or reverting transactions ?

You mean leave the item in the database and just mark it as deleted? It's not needed but if you want this for debugging purposes, I'm not against it.

**Comment by rwrzesien** [comment]
> You mean leave the item in the database and just mark it as deleted? It's not needed but if you want this for debugging purposes, I'm not against it.

Unfortunately it will not be possible to add soft delete, because it is possible to revert transaction (what really removes it), what decreases nonce, and as it is unique, the old database record must not exists.

**Comment by cameel** [comment]
We could have a separate table without the unique constraint if we really wanted to keep old transactions.
