### ISSUE TITLE
Refactor Concent core validators

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#593]
Extension of https://github.com/golemfactory/concent/issues/394.

Validation in Concent `core` module can be improved. Here is the list of things to be done:
- Validators should not raise `http400` error, but either return `True/False` or raise `ValidationError` (or our custom subclass for it with `error_code`) - this one is for discussion first. I prefer raising `ValidationError` as the native Django validators do.
- `validate_int_value` is actually used only once, for validating `deadline` in `ComputeTaskDef`, so it might be either renamed nad refactored or used directly in validation of `ComputeTaskDef`.
- In both `validate_key_with_desired_parameters` and `validate_int_value` there is a type checking, it should be extracted to separate function and reused.
- `validate_report_computed_task_time_window`, `validate_golem_message_subtask_results_rejected` are used only once, and checks view logic, so they can be moved directly to view.
- `validate_golem_message_client_authorization`, `validate_list_task_to_compute_ids` are not used at all, they can be removed.
- `validate_subtask_price_task_to_compute` does the same checks as `validate_int_value`, they should be combined.
- `validate_file_transfer_token` is used in both `core` and `gatekeeper`, so should be in `common` instead of `core`, along with `validate_secure_hash_algorithm`.

**Comment by dybi** [comment]
> Validators should not raise `http400` error, but either return `True/False` or raise `ValidationError` (or our custom subclass for it with `error_code`) - this one is for discussion first. I prefer raising `ValidationError` as the native Django validators do.

I am totaly for raising exceptioin (and totaly against returning `True/False`). Please implement it via raising exception

**Comment by Jakub89** [comment]
>In both `validate_key_with_desired_parameters` and `validate_int_value` there is a type checking, it should be extracted to separate function and reused. 
`validate_subtask_price_task_to_compute` does the same checks as `validate_int_value`, they should be combined.

The problem with those refactors is that `validate_int_value` checks also if value can be converted to int (from `str` for example) where other functions raise exceptions immediately. So I'm not sure if they all can be combined in to one function without some weird case checking?

**Comment by rwrzesien** [comment]
@Jakub89 Right, I have missed that, however it is used only once now - to check `deadline` in `ComputeTaskDef`. So how about combining those two without casting to int, and add only checking if casting to int is possible for `deadline` ?
