### ISSUE TITLE
Instance of 'list' has no 'exists' member when setting default objects Manager

### ISSUE THREAD

**Issue by wyspiansky87** [golemfactory/concent#594]
https://docs.djangoproject.com/en/1.11/topics/db/managers/#default-managers

When you use custom objects manager and want to still use default manager you need to define default manager before custom manager: 
```python
class Subtask(Model):
    (...)
    objects = Manager()
    objects_with_timing_columns = SubtaskWithTimingColumnsManager()
```

When you set default manager (no matter if custom manager is set too), pylint throws errors in massage_handlers.

```
************* Module core.message_handlers
E: 79, 7: Instance of 'list' has no 'exists' member (no-member)
E:400, 7: Instance of 'list' has no 'exists' member (no-member)
E:475, 7: Instance of 'list' has no 'exists' member (no-member)
E:1158,49: Instance of 'list' has no 'exists' member (no-member)
E:1351, 7: Instance of 'list' has no 'exists' member (no-member)
E:1450,11: Instance of 'list' has no 'exists' member (no-member)
```

You get theese errors with just:
```python
class Subtask(Model):
    (...)
    objects = Manager()
```

**Comment by cameel** [comment]
Those are warnings from pylint, not errors. Does it work - i.e. does the admin panel show the list or show you an error page?

Also, what is on the lines this warning points at? Line 79, 400, 475, etc. Without seeing these lines it's hard to tell whether the warning indicates a real problem or not.

@rwrzesien Could you help out there?

**Comment by dybi** [comment]
does not reproduce - closing
