### ISSUE TITLE
Signing Service: Base application

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#599]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597).

#### Overview
The goal of this task is to prepare the base on which we can build the service. For now it's just a test application that connects to Middleman, sends a test message, prints the response and immediately disconnects.

This is just a base for the full service. The actual protocol between the service and the Middleman and signing of Ethereum transactions will be implemented on top of this base in subsequent issues.

#### New project
Create a new project not based on Django or any other web framework.
- Put it in a directory called `signing_service/` at the top level of Concent repository.
- The project should have its own `requirements.txt`/`requirements.lock`.
- Configure the project for unit testing
    - Add necessary dependencies.
    - Plug it into `full_check.sh`, `lint.sh`, `run_tests.sh`, `mypy.ini`, etc.
- Configure logging.
- Configure it to be able to send error reports to Sentry.
- It does not need a configuration file.

#### Command-line parameters
The project should have a top-level Python script that starts the server. It should support at least the following command-line parameters:
- Address of a Concent cluster (no default)
- Port to use for the connection (use the same default as in Middleman)
- Sentry DSN (optional)

#### Communication with Concent
This is just a simple test program to ensure that the application works.

1. Initiate a TCP connection to the Concent cluster.
2. Send a test message
3. Wait for the response and print it on the screen.
4. Close the connection and exit.

**Comment by rwrzesien** [comment]
@cameel 
> Wait for the response and print it on the screen.

The case is that Concent doesn't respond to messages sent this way. I think that if it is working as HTTP server it will respond only to correct HTTP request.

**Comment by cameel** [comment]
Update: There should be separate parameters for port and address.

**Comment by cameel** [comment]
Update: Added Sentry DSN to command-line parameters.
