### ISSUE TITLE
Validate ComputeTaskDef before starting validation

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#600]
Currently we are getting a several sentry reports related to exceptions with missing fields in `ComputeTaskDef` or its inner containers. 

Related sentry reports:
https://talkback.golem.network/sentry/concent/issues/27092/
https://talkback.golem.network/sentry/concent/issues/27144/

This should be either validated in `validate_task_to_compute`, and in case follow up current convention.

**Comment by dybi** [comment]
@rwrzesien, @cameel, I would be for addind validation of `ComputeTaskDef` within `validate_task_to_compute` - this way it would be checked for basically every message

**Comment by PaweuB** [comment]
Pivotal link:
https://www.pivotaltracker.com/story/show/158832069

**Comment by cameel** [comment]
Yeah. The whole `TaskToCompute` should be validated by Concent Core immediately after it receives a message that starts a use case. It's the same situation as in #382.

And we should be doing it at the beginning of every use case (not only in verification).
