### ISSUE TITLE
Make usage of creation and modification timestamps in our database models more consistent

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#604]
This is the result of discussion about timestamps from an unrelated issue: https://github.com/golemfactory/concent/issues/553#issuecomment-402573866

The following changes are needed:
- Add `created_at` and `modified_at` timestamps to:
    - `Subtask`
    - `PendingResponse`
- Add `created_at` timestamp to:
    - `Client`
    - `StoredMessage`
- Move `created_at` timestamp from `BlenderSubtaskDefinition` to `VerificationRequest`.
    - Add a migration that moves the timestamp from the old object to the new one.

When you're done, update the corresponding docs/blueprints (or drop me a comment so that I remember that I have to do it).

**Comment by rwrzesien** [comment]
@cameel 
> Not if it has a different name. I mean a situation where there's a timestamp that's for a different purpose but effectively is as useful as creation or modification date. For example the timestamp field in StoredMessage.

This is a different type of data. `StoredMesage` timestamp is taken from golem message and means timestamp when golem message was created. `createad_at` always mean for me when given row was stored in database. Same with `modified_at` - it means last time when row was modified. So this model can have both.

> I think that it would be be confusing to have multiple fields for the same purpose.

Off course, but in this case they don't have same purpose. What I have meant was that there can be different types of timestamps on the object.

> StoredMessage
> Well, technically this is the timestamp created by the client and his clock may be out of sync so we could add creation timestamp to be able to cross-check it.

Yes, that is what I have meant from the very beginning. 

> Client
> I don't see the point of having it here, but I'm not strongly against it.

Debugging, we might want to check with which `Subtask` given `Client` was created (it can have many `Subtasks` related). I know it should be oldest one but we might be surprised.

> Subtask
> Yeah, this one should have the timestamps.

I agree.

> PendingResponse
> They already have the creation timestamp. They do not need modification timestamp because they're never supposed to be modified.

It has `delivered` field which is modified.

> VerificationRequest
> This one looks like my mistake. I should have put the timestamp in VerificationRequest not in BlenderSubtaskDefinition (which conceptually inherits from VerificationRequest).

Can be changed easily and even filled with data migration from related `BlenderSubtaskDefinition.created_at`.

> BlenderSubtaskDefinition
> PaymentInfo
> These models are related to a "parent" model that already has a timestamp (this is a relation that works like inheritance). They're read-only so they do not need a modification timestamp.

I agree.

**Comment by cameel** [comment]
> This is a different type of data. `StoredMesage` timestamp is taken from golem message and means timestamp when golem message was created. `createad_at` always mean for me when given row was stored in database. Same with `modified_at` - it means last time when row was modified. So this model can have both.

OK. Good point. I was thinking mostly about messages that we receive directly. But it can also be used for stuff like `TaskToCompute` that may have been created in the past.

> Debugging, we might want to check with which `Subtask` given `Client` was created (it can have many `Subtasks` related). I know it should be oldest one but we might be surprised.

But in which situation you would need this information? `Client` is never really important. It just gets created whenever it's needed. It's always the subtask that we're interested in.

But anyway, like I said, I'm fine with adding it here if you think it's useful.

> > PendingResponse

> It has `delivered` field which is modified.

OK. Let's add `modified_at`.

> > VerificationRequest

> Can be changed easily and even filled with data migration from related `BlenderSubtaskDefinition.created_at`.

Yeah. It should.

**Comment by cameel** [comment]
It looks like we agree about all the changes. In that case I'm removing the blocker.

**Comment by rwrzesien** [comment]
> But in which situation you would need this information?

An unpredictable one :)

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159099630
