### ISSUE TITLE
Incomplete validation of zip files in in verification

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#610]
There is a missing check - downloaded archives are not check if they are valid `ZipFile`. 
In case zip file is bad, `VerificationResult.MISMATCH` should be scheduled, as provider must have intentionally uploaded a bad zip file (checksum of uploaded file is valid at this point).

**Comment by PaweuB** [comment]
Added to Pivotal:
https://www.pivotaltracker.com/story/show/158903050
