### ISSUE TITLE
Middleman: Accepting connections from the Signing Service

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#616]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597).

#### Overview
The goal of this task is to prepare a Django app that starts a TCP server and accepts a single connection from the Signing Service. Connection is kept open until the service closes it. New connections are rejected while one is active. At this point there's no protocol and authentication and all received data is simply echoed back to the client.

This issue can be done independently of #615 but if #615 is not done before, you'll need to do some initial work from it here (creating the app, implementing the main loop, etc.). The stuff that's already been mentioned in #615 is omitted here so please read that issue before starting work on this one.

#### Middleman app and its management command
1. Create an app called `middleman` (See #615).
2. Create a management command called `middleman` (See #615).
3. Support the following command-line parameters (in addition to the ones from #615):
    - `--external-port`: int - the port Signing Service will connect to, available both from inside and outside the cluster.

#### Main loop
When Middleman starts it should perform the following steps (in addition to the ones from #615):

1. Start a TCP server listening on the external port.
    - If it's not possible (e.g. something else listening on that port), exit with an error.
2. When a new connection is established on the external port run the Signing Service connection handler
3. Handle exceptions and signals (See #615).

#### Concent connection handler
1. If a connection is already established close the connection and return
2. Otherwise continue
3. Read data from the client
4. Echo data back to the client
5. Handle exceptions
    - When the client closes the connection, return without errors

**Comment by PaweuB** [comment]
Link in Pivotal:
https://www.pivotaltracker.com/story/show/158908178
