### ISSUE TITLE
Middleman: Message-oriented protocol

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#618]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597). This task depends on #615 and #616.

#### Overview
Currently Middleman is implemented as a simple echo server working with a raw byte stream. It's time to make it possible to exchange full messages.

#### Wire protocol
The wire protocol is described in the blueprint (#597). Use it to implement message-based exchange.

The same protocol will be used by the Signing Service and by Concent so make the implementation reusable.

#### Implementation
- Change connection handlers so that they receive and send back full messages.
    - You should read until you encounter a frame separator or read the number of bytes indicated as payload length (whichever comes first).
- Validate data frames:
    - Verify that received messages from Concent and the Signing Service are signed with the right keys.
    - That metadata signature is correct
    - That payload length is not longer than the payload.
    - That frame ID matches one of the requests that have not received a response yet.
- If a frame is invalid, respond with an `ERROR` frame.

#### Settings
- `SIGNING_SERVICE_PUBLIC_KEY` - The public key that can be used to verify signatures of messages sent by the Signing Service.
    - If this is not set and `middleman` is enabled in `CONCENT_FEATURES`,  `manage.py check` should report an error and `manage.py middleman` should exit with an error message and non-zero exit code.

**Comment by PaweuB** [comment]
Link in Pivotal:
https://www.pivotaltracker.com/story/show/158908200

**Comment by cameel** [comment]
Update: I have moved the wire protocol description to the blueprint.

**Comment by rwrzesien** [comment]
@cameel It is now as a separate directory on top level, should it be added to our checks (lint, mypy, tests etc.) as well ?

**Comment by cameel** [comment]
Yes to both questions. You should treat it as an independent library used by both Concent and Signing Service.

**Comment by rwrzesien** [comment]
@cameel 
> You should read until you encounter a frame separator or read the number of bytes indicated as payload length (whichever comes first).

As discussed in https://github.com/golemfactory/concent/pull/673#discussion_r204222011, if we move responsibility for proper message to the Client, I think it is enough to only read until separator.

**Comment by cameel** [comment]
What do you mean by "move responsibility for proper message to the Client"?

**Comment by rwrzesien** [comment]
I have meant that middleman protocol will not cut off extra bytes itself but consider message with extra bytes over payload an invalid message.

**Comment by cameel** [comment]
Update: `ServiceRefused` in the description replaced with an `ERROR` frame. I originally intended to change this after I finish the blueprint but forgot about it.
