### ISSUE TITLE
Signing Service: Error handling and reconnections

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#623]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597). This task builds upon #599.

#### Overview
The purpose of this task is to turn the simple client application build in #599 into a service that initiates the connection but then listens for incoming data. It should also handle errors properly and reestablish the connection if it gets interrupted.

#### Command-line parameters
The following new parameters should be added:
- Retry parameters - delay, number of attempts, etc.
    - Depends on how you implement the retry. I recommend a delay that doubles after each unsuccessful attempt and is reset after success.

#### Communication with Concent
1. Initiate a TCP connection to the Concent cluster
    - If you can't connect or the connection drops, retry, possibly with some configurable delay between attempts.
2. When a connection is established run the connection handler
    - An exception that escapes from the handler should interrupt the current connection.
3. Handle exceptions and signals
    - If the connection is interrupted due to a failure (e.g. disconnected cable), don't report it. Just reconnect.
    - If there was an unrecognized exception, log it and report to Sentry. Then reraise it and crash.
    - If a shutdown signal (SIGTERM) or Ctrl+C (`KeyboardInterrupt`) is caught, terminate the connection and exit without errors.

#### Connection handler
1. Read data from the connection
2. Echo data back over the connection
3. Handle exceptions
    - When the other side closes the connection, return without errors

#### asyncio
The client is completely synchronous but it may still be a good idea to use [asyncio](https://docs.python.org/3/library/asyncio.html) for blocking operations, like listening for data coming over a socket.

See also #615 and #616 which implement the similar mechanism on the server side.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/158969952

**Comment by rwrzesien** [comment]
@cameel 

> An exception that escapes from the handler should interrupt the current connection.

What do you mean by that ? Should it end process gracefully or close current socket and reopen a new one ?

**Comment by cameel** [comment]
Update: I made it clear that the service should crash when it encounters an unexpected error. Please see also the updated blueprint for information about how the service should handle errors.

**Comment by cameel** [comment]
> What do you mean by that ? Should it end process gracefully or close current socket and reopen a new one ?

I mean that it should end gracefully but after cleaning up still reraise the exception and let the service crash. Don't bother reconnecting. The main loop should send a crash report to Sentry but after that let the exception escape.

This is something that should not usually happen. Only if we have a bug - so letting the service crash is the best thing we can do. Kubernetes will restart it and it will just start again with a clean state and a fresh connection.

This behavior is meant only for unexpected errors. If you can think of any predictable failure (like a dropped connection), you should handle it. The crash is just an emergency exit in a situation where you don't really know what happened :)
