### ISSUE TITLE
Signing Service: Message-oriented protocol

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#625]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597). This task depends on #623.

#### Overview
Currently the Signing Service is implemented as a simple echo server working with a raw byte stream. It's time to make it possible to exchange full messages.

#### Wire protocol
The wire protocol is described in the blueprint (#597). Use it to implement message-based exchange.

The same protocol will be used by the Middleman and by Concent so make the implementation reusable.

#### Implementation
See the description of #618. Implement the same checks and way of communication but in the Signing Service.

#### Command-line parameters
- Concent's public key.
- Signing service private key: the private key used for signing protocol frames and Golem messages.
    - Should be passed as in #671.
    - Note that the public key can be easily computed from the private key.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/158969994

**Comment by rwrzesien** [comment]
@cameel 

> See the description of #618. Implement the same checks and way of communication but in the Signing Service.

Should be "Middleman".

**Comment by cameel** [comment]
No. The checks and communication should be implemented in the Signing Service not in the Middleman :P

**Comment by rwrzesien** [comment]
@cameel If the received message was not possible to deserialize, we should response with `ServiceRefused` wrapped in `GolemMessageMiddlemanMessage`. What value should be set as `request_id` then ?

**Comment by rwrzesien** [comment]
@cameel How to get private key for signing `ServiceRefused` ? Adding it to SigningService is in next issue, and I can't use `django.conf.settings` because SigningService is not being run in Django context. Can I just hardcode it for now ?

**Comment by cameel** [comment]
> Which private key should be used to sign Middleman protocol messages when sending them from SigningService to Middleman ?

Signing Service should have its own key for Golem messages. I have added it to the descrption now.

> Also, adding Concent public key is in following issues. Can I hardcode it for now ?

But why? Adding a parameter is easy and without it you will only be able to test against one specific Concent cluster.

**Comment by cameel** [comment]
@rwrzesien Is this task done?

**Comment by rwrzesien** [comment]
@cameel Yes, resolved in https://github.com/golemfactory/concent/pull/688, closing.
