### ISSUE TITLE
Each message should be stored with its timestamp not with store timestamp

### ISSUE THREAD

**Issue by MichalW-CP** [golemfactory/concent#627]
For timestamp in store_message we use datetime.datetime.now(timezone.utc). It should be parse_timestamp_to_utc_datetime(golem_message.timestamp).
```python
message_handlers.py

def store_message(
    golem_message:          message.base.Message,
    task_id:                str,
    subtask_id:             str,
):
    assert golem_message.TYPE in message.registered_message_types

    message_timestamp = datetime.datetime.now(timezone.utc)
    stored_message = StoredMessage(
        type        = golem_message.TYPE,
        timestamp   = message_timestamp,
        data        = copy.copy(golem_message).serialize(),
        task_id     = task_id,
        subtask_id  = subtask_id,
    )
    stored_message.full_clean()
    stored_message.save()

    return stored_message
```
In tests timestamp for stored_message is the same for each message that is stored. It should get timestamps individually for each message. 
In tests we can check if stored_message timestamp equals to message timestamp.
```python
tests/utils.py

    def _test_last_stored_messages(self, expected_messages, task_id, subtask_id, timestamp):
        assert isinstance(expected_messages, list)
        assert isinstance(task_id,           str)
        assert isinstance(subtask_id,        str)

        expected_message_types = [expected_message.TYPE for expected_message in expected_messages]

        for stored_message in StoredMessage.objects.order_by('-id')[:len(expected_message_types)]:
            self.assertIn(stored_message.type,                      expected_message_types)
            self.assertEqual(stored_message.task_id,                task_id)
            self.assertEqual(stored_message.subtask_id,             subtask_id)
            self.assertEqual(stored_message.timestamp.timestamp(),  self._parse_iso_date_to_timestamp(timestamp))

            expected_message_types.remove(stored_message.type)

        assert expected_message_types == []
```

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/158971816

**Comment by Jakub89** [comment]
@dybi suggested solution for tests:
- Remove `self.assertEqual(stored_message.timestamp.timestamp(), self._parse_iso_date_to_timestamp(timestamp))` from `_test_last_stored_messages()`
- Add unit test for `store_message` that checks timestamp mechanism

I personally like this solution, because checking `expected_messages` with something like `expected_timestamp` to those messages is a little problematic.

**Comment by rwrzesien** [comment]
@Jakub89 You can also change it in a way that allow passing `expected_messages` as a dict `{message: expected_timestamp}`. This way it will be still possible to test if created messages have expected timestamp.

**Comment by Jakub89** [comment]
@rwrzesien I did consider this, but look how for loop is constructed in `_test_last_stored_messages()`. Order of those checks is not based on our input, but rather on query filter. So it's hard to predict which `stored_message` are we checking.

**Comment by rwrzesien** [comment]
Right, lets leave it then.

**Comment by rwrzesien** [comment]
@Jakub89 Your answer gave mi one more idea. How about changing `_test_last_stored_messages` in the way that when you have a expected timestamp, message type, task_id and subtask_id you can query for last `StoredMessage` which has all of the above ? You could do this in a loop, querying for them one by one, and assert that `StoredMessage` with this data exists. 

It would actually make the implementation of `_test_last_stored_messages` better. The only thing that should be investigated first is if our tests doesn't create message `StoredMessage` with the same type and timestamp during single test.

**Comment by Jakub89** [comment]
@rwrzesien hmm I've started implementing previous solution already :/ and that was a lot of lines to remove in our tests. What You suggesting would probably work just fine but the effort to change it is much bigger, we would need to change calling of `_test_last_stored_messages` in all those tests. Besides what's the point of checking that timestamp in every test in all usecases? I like simple idea of unit test `store_message`, which also make it easier if something about timestamp will change in the future.

**Comment by dybi** [comment]
@rwrzesien, @Jakub89 I like the idea with unit test and not checking timestamp for all messages. Dealing with it has been PITA maintenance effort.

**Comment by rwrzesien** [comment]
@Jakub89 Ok, I have expected it might happen that you already have done too much to change it now so lets leave it as it is.

> Besides what's the point of checking that timestamp in every test in all usecases?

There is never enough of tests ;)

**Comment by Jakub89** [comment]
> There is never enough of tests ;)

They just take a long time on my potato laptop :P
