### ISSUE TITLE
View is called with client_message as None.

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#63]
In few of our tests there is a case when view is called with client_message being None, which means it failed to be loaded in api_views.py, but we don't handle this type of situation. When working on different issue I have found out that 3 of our current tests cause this situation. 

We should add check to api_views.py after load() is performed to check if returned message is None, and if yes return Http400 error with proper message. Also an additional test which checks this specific case is needed.

**Comment by cameel** [comment]
Looks like golem-messages has been updated to never return `None`: https://github.com/golemfactory/golem-messages/pull/98. This should be released soon. So we won't be getting `None` any more. 

We'll have to fix these tests after update though.

Just to make sure we really don't get `None`: please find all calls to `load()` or `deserialize()` in our code and add `assert decoded_message is not None` there as a sanity check.
