### ISSUE TITLE
Middleman: Signing Service authentication

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#630]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597). This task depends on #618.

#### Overview
As implemented now Middleman simply accepts connections from the Signing service without asking any questions. While a rogue service won't be able to impersonate the service because its messages need to be signed with the right key, an attacker can still prevent the real service from connecting and sit quietly hogging the connection.

To prevent this Middleman should not start the normal communication with the service until it manages to respond correctly to an authentication challenge.

Connections with Concent do not need to be authenticated. We're not worried about a rogue connection blocking others because Middleman is prepared to maintain multiple connections with Concent at any given time. Also, they're never accepted on the external port and can come only from inside the cluster.

#### Main loop
Modify the logic for accepting new connections
1. Allow multiple connections as long as none of them is authenticated:
    - If there are no established connections or if no connection is authenticated yet, allow new connections to start the authentication handler.
    - If any connection successfully passes the authentication process, immediately terminate all other connections with the service
    - If a connection is established and authenticated, do not allow new connections until this one ends.
2. Once a new connections authenticates successfully, enter the connection handler.

#### Signing Service authentication handler:
1. Generate a random string.
    - Make sure that you use a cryptographically secure pseudo-random number generator. See what golem-messages uses internally for its encryption and use the same thing.
    - Use strings of the same length. Not too short but not too long.
2. Start listening for a response from the service.
3. If the service does not respond in a predefined time, terminate the connection.
    - This time should not be too long.
4. Validate the response. If the validation fails, terminate the connection:
    - The response must be a valid data frame as described in the protocol.
    - It must be the authentication response. Any other message type is treated as a failure to authenticate.
    - The signature must match the public key of the service.
5. If the connection was terminated, log the incident at `INFO` level and return an error.
6. Otherwise return a success.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/158999840

**Comment by cameel** [comment]
@dybi Stuff like `ENABLE_AUTHENTICATION` should be mentioned before you close the issue.

Also why is this a constant and not a setting? How are we going to test authentication if it's permanently disabled?
