### ISSUE TITLE
Signing Service: Protocol messages

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#632]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597).

#### Overview
The Signing Service exchanges data with Concent using Golem messages. We need to several new types for that purpose.

Ideally these messages would be added only in Concent. They are not a part of the protocol used by Golem and Concent. But last time we talked about it, golem-messages required refactoring to allow defining arbitrary messages without registering them from within the library (https://github.com/golemfactory/golem-messages/issues/103). If that refactoring has not been done yet, submit our new messages in a pull request for inclusion in golem-messages. This will be a temporary workaround and we'll move them to Concent later, when it's possible.

#### `TransactionSigningRequest`
| Field                           | Type                   | Size           |
|---------------------------------|------------------------|----------------|
| `nonce`                         | int                    | up to 32 bytes |
| `gasprice`                      | int                    | up to 32 bytes |
| `startgas`                      | int                    | up to 32 bytes |
| `to`                            | string                 | 20 bytes       |
| `value`                         | int                    | up to 32 bytes |
| `data`                          | binary                 | unlimited      |
| `from`                          | string                 | 20 bytes       |

#### `SignedTransaction`
| Field                           | Type                   | Size           |
|---------------------------------|------------------------|----------------|
| `nonce`                         | int                    | up to 32 bytes |
| `gasprice`                      | int                    | up to 32 bytes |
| `startgas`                      | int                    | up to 32 bytes |
| `to`                            | string                 | 20 bytes       |
| `value`                         | int                    | up to 32 bytes |
| `data`                          | binary                 | unlimited      |
| `v`                             | int                    | 1 byte         |
| `r`                             | int                    | 32 bytes       |
| `s`                             | int                    | 32 bytes       |

#### `TransactionRejected`
| Field                           | Type                         | Size           |
|---------------------------------|------------------------------|----------------|
| `nonce`                         | int                          | up to 32 bytes |
| `reason`                        | `TransactionRejectionReason` |

#### `TransactionRejectionReason` enum
- `InvalidTransaction` 
- `UnauthorizedAccount`

**Comment by cameel** [comment]
Update: `ConnectionTimeout` added to `MiddlemanErrorCode`.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/158999732

**Comment by cameel** [comment]
Update: `MiddlemanError` removed. It will not be a messages after all. We'll use a special frame type for errors.

**Comment by cameel** [comment]
Update: Added missing `from` address to `TransactionSigningRequest`.

**Comment by rwrzesien** [comment]
@cameel Please change `from` field name to `from_address`.
