### ISSUE TITLE
Signing Service: Signing Ethereum Transactions

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#633]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597). This task builds upon #625 and depends on messages defined in #632.

#### Overview
In this task we want to make the service actually do something useful. It should start handling `TransactionSigningRequest`s by either returning a signed transaction or rejecting the request.

#### Command-line parameters
The following new parameters should be added:
- Ethereum private key: the private key that allows the service sign Ethereum transactions.
    - The key itself should never be used directly on the command line in production. The command can be seen by other users in the system (e.g. with `ps`). It might also end up in Bash history or in logs. Using a file leaves behind less trace.
        - Do it like in #671 - it should be possible to pass the key in three ways: in a variable, on the command line and in a file.
    - Note that the contract address can be easily computed from the private key.

#### Connection handler
Replace the handler described in #618 with the following code executed in a loop:

1. Read a complete message from Middleman
2. Validate the message. If the message is invalid, respond with an `ERROR` frame and end this loop cycle.
    - Is the frame correct according to the protocol? If not, error code is `InvalidFrame`.
    - Is frame signature correct? If not, error code is `InvalidFrameSignature`.
    - Is frame type `GOLEM_MESSAGE`? If not, error code is `UnexpectedMessage`.
    - Can the payload be decoded as a Golem message? If not, error code is `InvalidPayload`.
    - Is message signature correct? If not, error code is `InvalidPayload`.
    - Is Golem message type `TransactionSigningRequest`? If not, error code is `UnexpectedMessage`.
    - Is the content of the message valid? Do types match the schema and all values are within allowed ranges? If not, error code is `InvalidPayload`.
3. Validate the transaction. If the transaction is invalid, respond with `TransactionRejected`.
    - Is it possible to load the transaction using the library we're using to sign it? If not, rejection reason is `InvalidTransaction`.
    - Does the transaction execute a function from the contract that the service has the private key for? If not, rejection reason is `UnauthorizedAccount`.
4. If all the validations passed, sign the transaction.
5. Respond with `SignedTransaction`.
6. Handle exceptions
    - When the other side closes the connection, return without errors

The loop exits only if the service is stopped with a shutdown signal or Ctrl+C or if the handler fails due to an unexpected error.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/158999618

**Comment by rwrzesien** [comment]
@cameel 
>  it should be possible to pass the key in three ways: in a variable, on the command line and in a file.

What should be hierarchy for this ? Or should it fail when more than one is passed in the same time ?

**Comment by cameel** [comment]
It should fail.

**Comment by rwrzesien** [comment]
@cameel Which private key should be used to sign Middleman protocol messages when sending them from SigningService to Middleman ?

**Comment by cameel** [comment]
Update:
- Changed command-line arguments. Added private key for signing messages, removed ethereum address.

**Comment by cameel** [comment]
Update:
- Wrong issue, I should have added the private key to #625. I'm moving it there. But the Ethereum address is still removed because we don't need it.
