### ISSUE TITLE
SCI Callback: Submitting Ethereum Transactions to the Signing Service

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#635]
This is a part of the implementation of the "Concent Signing Service" blueprint (#597). This task assumes that the wire protocol described in #618 is already implemented.

#### Overview
Currently Concent is signing the Etherem transactions on its own by supplying a trivial callback that simply calls `Transaction.sign()`. We want to replace the callback with one that submits the transaction to the Signing Service and does not rely on having access to the private key.

#### Settings
Create the following new settings:
- `MIDDLEMAN_ADDRESS`: string - IP or domain name that can be used to connect to Middleman.
    - No default in production. `localhost` in development.
- `MIDDLEMAN_PORT`: int - The port on which Middleman is accepting requests. This should be the internal port, meant for connections with Concent.
    - Default should be the same as the port Middleman uses if you start it without giving it a port.
- `SIGNING_SERVICE_PUBLIC_KEY`: string - public part of the key used by Signing Service to sign Middleman protocol frames and Golem messages
    - No default in production, in development you can hard-code a key (use the same you used for the Signing Service)

Also, remove the setting that contains the private ethereum key. Update concent-deployment to remove this key from our configuration on the cluster as well.

#### Signing callback
The callback should do the following:
1. Create a `TransactionSigningRequest`.
2. Establish a TCP connection with Middleman.
    - If you can't connect, raise an exception immediately, without retrying.
3. Send the `TransactionSigningRequest`.
4. Read the response.
5. Close the connection.
6. If the response is a valid `SignedTransaction`, copy the signature to the transaction object passed to the callback by SCI and return.
7. Otherwise handle errors by raising an exception and interrupting the callback:
    - If the connection with Middleman times out before a complete response is received.
    - If the received data frame is invalid or the signature does not match its content.
    - If the request ID in the received data frame does not match the one in the data frame that was sent.
    - If the received Golem message is malformed or not signed by the Signing Service.
    - If the received Golem message is anything else than `SignedTransaction`, `TransactionRejected` or and `ERROR` frame.
    - If the received Golem message is `TransactionRejected` or an `ERROR` frame.
    - If the transaction data in `SignedTransaction` does not match the information we sent.
        - In particular if the contract address is different than the one in the request.
    - If the Ethereum signature in `SignedTransaction` is not a valid signature.
    - If the transaction in `SignedTransaction` is not signed with the right Ethereum private key.

The callback should replace [the one we currently pass to `SCIImplementation`](https://github.com/golemfactory/concent/blob/9f00af4aaeec85e87dd8359ccd12e1b634f7e3fe/concent_api/common/singleton.py#L10-L14)

#### Callback and the request from a Golem client
The callback is going to run in the context of a request from a Golem client submiting or retrieving a protocol message. The web server that's serving this request has a timeout after which it terminates the connection. Please make sure that a timeout like this interrupts the operation and rolls back all database changes. We don't want the client to disconnect and get HTTP 500 while Concent actually completes the trasaction successfully without any way for the client to know about it.

#### Handling exceptions from the callback
The exceptions should interrupt the request from a Golem client and result in a HTTP 502 response. This way all the incomplete changes get rolled back and the client hopefully tries again.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/158999944

**Comment by rwrzesien** [comment]
@cameel 

Which value should be used to set `from` on TransactionSigningRequest ?

**Comment by cameel** [comment]
The public address of the Ethereum account that the service has keys for.

Service validates that this public key matches its private key before signing the transaction. If it does not, it must reject it because it can't really make transfers from that account.

**Comment by rwrzesien** [comment]
@cameel 
> If the received Golem message is malformed or not signed by the Signing Service.

Should Concent have SigningService public key ? Wasn't it that MiddleMan "re-signs" message with Concent keys ?

**Comment by cameel** [comment]
Yes, Concent should know the key. I've added it in the description.

**Comment by rwrzesien** [comment]
@cameel 
Is `CONCENT_ETHEREUM_PUBLIC_KEY` added to Concent settings by any issue ? It is needed to check
> If the transaction in SignedTransaction is not signed with the right Ethereum private key.

**Comment by rwrzesien** [comment]
@cameel There is possibility to generate `ETHEREUM_PUBLIC_KEY` from signature and message hash, which allows you to generate `ETHEREUM_ADDRESS` from that key, which then can be compared but it contains some cases when this can fail, so I have added issue for replacing this https://github.com/golemfactory/concent/issues/735.
