### ISSUE TITLE
Additional validation for frames in `extra_data`

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#645]
Our validation for frames in `CTD` has a gap. At first it should be tested if `extra_data` has `frames` key in `extra_data` dict. 

Referring to: https://talkback.golem.network/sentry/concent/issues/27144/

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159031890

**Comment by kbeker** [comment]
Already fixed
