### ISSUE TITLE
Add computation_deadline and result_package_size fields to Subtask model

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#660]
To implement #329 we need to be able to access pieces of data from `ReportComputedTask` and `TaskToCompute` in a database query. To do this we need to maintain a copy of relevant fields on the `Subtask` table.

Add the following fields to `Subtask` model:
- `computation_deadline`: should be the same as `TaskToCompute.deadline`.
- `result_package_size`: should be the same as `ReportComputedTask.size`.

Add model validations that ensure that these fields always match the corresponding golem-messages.

Create a migration that fills these fields on existing model instances.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159162635
