### ISSUE TITLE
Add validate if reason in RejectReportComputedTask is valid enum

### ISSUE THREAD

**Issue by pawelkisielewicz** [golemfactory/concent#662]
Generally `reason` in `RejectReportComputedTask` should be one of three `enums`.
Currently handling `RejectReportComputedTask` in `handle_send_reject_report_computed_task` we only check:
if reason is one of them, 
elif is second, 
if is third. 

There is missing validation, if reason is valid enum in general. The task is to add this validation and return message to client if reason is invalid.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159228829
