### ISSUE TITLE
ForceSubtaskResultsResponse with both subtask_results_accepted and subtask_results_rejected

### ISSUE THREAD

**Issue by pawelkisielewicz** [golemfactory/concent#666]
Handling ForceSubtaskResultsResponse we are checking if:
`client_message.subtask_results_accepted is not None or client_message.subtask_results_rejected is not None`
This message should contain `subtask_results_accepted` OR `subtask_results_rejected`, but we are not validating case, in which message contains `subtask_results_accepted` AND `subtask_results_rejected`.
Please add missing validation and response to client (currently in this case it will be not handled at all)

**Comment by kbeker** [comment]
Am I wrong or this would be weird if we would have `subtask_results_accepted` and `subtask_results_rejected` in one message?

**Comment by pawelkisielewicz** [comment]
I agree with you- it would be weird and incorrect. This is the reason to validate, if `message` contains only and exactly one of them (`subtask_results_accepted` or `subtask_results_rejected`)

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159228783
