### ISSUE TITLE
Notifying the control cluster about finished uploads in the result transfer use case

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#667]
Currently Concent Core checks is a subtask result has been uploaded to the storage cluster by repeatedly polling it using HEAD method. We need to change this so that it works more like verification where the storage cluster notifies Concent Core (verification is described in #193).

See how a similar functionality has been implemented in verification: #208, #224, #411. Be careful not to repeat the same mistakes, like #468, #471, #540.

#### `Subtask`
Add the following columns:
- `result_upload_finished`: bool

#### `UploadReport`
Add the following columns:
- `result_transfer_request`: `ResultTransferRequest` foreign key
    - A report can now be associated with a `ResultTransferRequest`, a `VerificationRequest` or with both. The latter will happen if a subtask goes first through use case 3, then also through use case 5.

#### `ResultTransferRequest`
| Column name                   | Type      | Remarks                                                                                                                 |
|-------------------------------|-----------|-------------------------------------------------------------------------------------------------------------------------|
| `subtask_id`                  | string    | Subtask ID. Can't be `NULL` or blank.
| `result_package_path`         | string    | Relative path of the .zip file that contains the rendering result received from the provider. Can't be `NULL` or blank.
| `upload_finished`             | bool      | True when `upload_finished` task for this subtask has already been sent to the work queue. Can't be NULL.
| `created_at`                  | timestamp | Creation time of this model instance.
| `modified_at`                 | timestamp | Last modification time of this model instance.

#### `result_transfer_request` task
| Parameter name                | Type        |
|-------------------------------|-------------|
| `subtask_id`                  | string      |
| `result_package_path`         | string      |

Route this task to the `conductor` queue.

#### `result_upload_finished` task
| Parameter name                | Type        |
|-------------------------------|-------------|
| `subtask_id`                  | string      |

Route this task to the `concent` queue.

#### Conductor
- When nginx-storage uses the endpoint that notifies about a file upload:
    - Create `UploadReport` for the file
    - If `ResultTransferRequest` matching the file exists:
        - Report finished upload (see below)

##### Reporting finished upload
- Fill `result_transfer_request` in all `UploadReport` instances that refer to this file.
    - Both this field and `verification_request` can be filled at the same time.
    - If both `ResultTransferRequest` and `BlenderVerificationRequest` that refer to the same file exist and they both have `upload_finished` set to `False`, crash with an error. It should not happen.
- If `ResultTransferRequest.upload_finished` is `False`:
    - Post `result_upload_finished` to the work queue.
- Set `ResultTransferRequest.upload_finished` to `True`.

#### Conductor worker
- When `result_transfer_request` is received:
    - Create `ResultTransferRequest`
    - If at least one `UploadReport` is already available for the file listed in the request
        - Report finished upload (see above).

#### Concent worker
- When `result_upload_finished` task is received:
    - If the subtask does not exist, crash with an error.
    - Set `Subtask.result_upload_finished` to `True`.

#### Concent Core
- Instead of making a request to the storage cluster, make Concent check the `Subtask.result_upload_finished` flag.
- When a message to `send/` starts the result transfer use case, post `result_transfer_request` to the work queue.

**Comment by rwrzesien** [comment]
@cameel What action triggers `result_transfer_request` task?

**Comment by cameel** [comment]
Good point. It was missing. It should be posted to the queue when the transfer use case is successfully started. I've updated the description.

**Comment by rwrzesien** [comment]
@cameel Should `result_transfer_request` task check if `Subtask` with passed `subtask_id` exist and that it has `FORCING_RESULT_TRANSFER` state? If yes, what should happen when it does not?

**Comment by rwrzesien** [comment]
> You mean result_upload_finished? Because result_transfer_request is processed by the Conductor which does not have access to the subtask database.

Actually I have meant `result_transfer_request` but I forgot about databases issue. So it looks like checking this there will not be possible at all.

> If the subtask is in any state preceding FORCING_RESULT_TRANSFER, that's weird and should be logged as an error and reported to Sentry.

Should it be reported to Sentry also in the two detailed cases described below this paragraph?

**Comment by cameel** [comment]
Of course not :) Why would you report INFO or WARNING to Sentry? By logging I mean just logging.
