### ISSUE TITLE
Don't count timed-out tasks as active in the admin panel

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#668]
In #152 we have added an admin panel filter that shows only active subtasks. There's one problem though - the state of a subtask does not get updated until one of the clients involved in it actually contacts Concent. If that does not happen, the task stays in an active state even if it has timed out. This means that this filter does not filter out many tasks that have already ended.

To fix this, please replace the filters:
- `active` - rename it and replace with one that includes tasks in active states but only if current time <= `next_deadline`.
- `passive` - rename and replace it with one that includes only tasks that do not match the `active`filter.

Also update the soft shutdown countdown timer (see #335) to assume that soft shutdown has completed as soon as all tasks are either in passive states or already timed out.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/159192149
