### ISSUE TITLE
[WIP] MiddleMan raise IncompleteReadError when signing service close connection.

### ISSUE THREAD

**Issue by Jakub89** [golemfactory/concent#679]
When running middleman with default settings, which are: 
``` shell
INFO     | MiddleMan is serving on ('127.0.0.1', 9054)
```
and then running signing service with `./signing_service.sh 127.0.0.1 1 --concent-cluster-port=9054`:

1. Nothing happens, there's no response from either sides.

2. When closing signing service with Ctrl-C, we get this error:
```  shell
15:54:03 ERROR    | Exception occurred: 0 bytes read on a total of None expected bytes, Traceback: Traceback (most recent call last):
  File "/home/jakub/Documents/work/projects/concent/concent_api/middleman/middleman_server.py", line 89, in _handle_user_request
    data = await reader.readuntil()
  File "/usr/lib/python3.6/asyncio/streams.py", line 578, in readuntil
    raise IncompleteReadError(chunk, None)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of None expected bytes
 
15:54:03 ERROR    | Task exception was never retrieved
future: <Task finished coro=<MiddleMan._handle_user_request() done, defined at /home/jakub/Documents/work/projects/concent/concent_api/middleman/middleman_server.py:87> exception=IncompleteReadError('0 bytes read on a total of None expected bytes',)> 
Traceback (most recent call last):
  File "/home/jakub/Documents/work/projects/concent/concent_api/middleman/middleman_server.py", line 89, in _handle_user_request
    data = await reader.readuntil()
  File "/usr/lib/python3.6/asyncio/streams.py", line 578, in readuntil
    raise IncompleteReadError(chunk, None)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of None expected bytes
```

**Comment by rwrzesien** [comment]
https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.readuntil

> If an EOF occurs and the complete separator is still not found, an IncompleteReadError exception will be raised, and the internal buffer will be reset. The IncompleteReadError.partial attribute may contain the separator partially.

I think we could add handling of `IncompleteReadError` and close gracefully when it is caught.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159264674

**Comment by cameel** [comment]
I'm not sure if using `readuntil()` is a good idea. In our case waiting for the separator causes the problem that I have described in https://github.com/golemfactory/concent/pull/673#discussion_r204222011. It's OK while it's just an echo sever but when middleman protocol is done we'll need a method that allows us to process the message even before getting a separator.

**Comment by rwrzesien** [comment]
> It's OK while it's just an echo sever but when middleman protocol is done we'll need a method that allows us to process the message even before getting a separator.

So you want it to work also by reading payload_length from raw bytes and then read that amount of bytes and parse message ? The problem would be that in current implementation `payload_length` is on different positions depending on several factors. If that is a bug, I can try to make be on expected position, but it will require some changes in protocol.

**Comment by cameel** [comment]
Yes, it should be at a static position. The header is supposed to have constant length.

**Comment by rwrzesien** [comment]
I have investigated this a little bit, it looks like we won't be able to do much about it apart from catching and explicitly handling `IncompleteReadError` (currently all exceptions are re-raised), as we will currently keep reading until separator is met.

**Comment by cameel** [comment]
Sure, we probably need to catch and handle it.

I see that this exception inherits from `EOFError`. So it just means that the sender has closed the connection? It should be handled as such. How do we currently handle the connection being closed in the middle of a message? We need to do the same thing there.

After that we get a sequence of bytes representing a full or partial message. I see two options:
1. Process the received bytes as if there was a separator immediately behind them.
2. Assume that the lack of a separator means that the frame is invalid and reject it outright.

In any case, this should be caught and handled.
