### ISSUE TITLE
Optimize MiddleMan protocol helper to process more than 1 byte at a time

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#684]
Currently MiddleMan protocol `handle_message_receive` helper process 1 byte at a time. It should try to read more bytes if they're available (but not block if they're not) and also not process it one byte at a time.

Original source of this issue 
https://github.com/golemfactory/concent/pull/673#discussion_r205292433

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159430189

**Comment by rwrzesien** [comment]
Closing as already resolved in https://github.com/golemfactory/concent/pull/673.
