### ISSUE TITLE
signing-service: we need default value for `initial_reconnect_delay` setting

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent#692]
Now, to start the signing service, we always have to provide the value of `initial_reconnect_delay` setting. We want to use it only for non-standard use.

**Comment by rwrzesien** [comment]
@bartoszbetka The value is always required, without it SigningService won't start. But if you want, I can add a default for it. What value would you expect ? Is `1` ok ?

**Comment by cameel** [comment]
Seems fine to me.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159459270
