### ISSUE TITLE
Delete mocked verification

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#695]
Temporary hack for mocked verification must be deleted. 
1. Setting `MOCK_VERIFICATION_ENABLED` must be deleted.
2. Temporary hack in function `verifier.tasks.blender_verification_order` for mocked verification should be deleted.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159461179

**Comment by cameel** [comment]
@kbeker It's #475 that should have the `compatibility hack` label not this one. This one removes the hack.
