### ISSUE TITLE
Change task_id and subtask_id to match new requirements (UUID)

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#705]
Currently in ours tests we're using differentiated id's. Sometimes it is:
```python
subtask_id = '1'
subtask_id = 'test'
```
and etc. We should start to use same id's which Golem use. 

Find all places where `subtask_id` and `task_id` are created and change it to id's created by `uuid` library:
```bash
>>> from uuid import uuid4
>>> uuid4()
UUID('4bb9d417-c41c-40c7-857c-e9274b49d0a2')
```

**Comment by kbeker** [comment]
@cameel should we also add validation to these id's that they **must** be `UUID` instances?

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/158629290

**Comment by cameel** [comment]
> should we also add validation to these id's that they **must** be `UUID` instances? 

Yes. That's the whole point of the task. Golem had always been using UUIDs. The change is that UUIDs are now required so we can tighten our validations. You should check how Golem validates this and do the same in our code. Or, better, in golem-messages and only add assertions on our side.

Especially the code that constructs paths from IDs should have assertions to make sure dangerous paths cannot be constructed. You should test for example that it's not possible to construct a path that would overwrite nginx config or `/etc/shadow`.
