### ISSUE TITLE
Verifier fails to find the source package it has just downloaded

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#707]
At this moment we do not validate situation when file does not exist in moment when verifier wants to unpack archive to get file list. There should be added validation before verifier wants to get list of files from archives. Also please investigate why and how this situation may happen. 

Exception raised: 
```python
FileNotFoundError: No such file or directory: 
'/srv/storage/source_e5b64e01-bf44-8598-5831-07f321291102.9af2a0b9-a556-f3dd-9b4d-7c97c97ebcaa.zip'
```
Function which produces error:
```python
def get_files_list_from_archive(file_path: str) -> List[str]:
    """ Returns list of files from given zip archive. """
    return zipfile.ZipFile(file_path).namelist()
```

Please add unit tests and be sure that all `api-integration-tests...` works.

Sentry link: https://talkback.golem.network/sentry/concent/issues/31103/events/189679/

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159558351

**Comment by cameel** [comment]
> There should be added validation before verifier wants to get list of files from archives.

Not a validation. `assert`. It's not client's error. It's our code that called this function even though the file did not exist.
