### ISSUE TITLE
Verifier does not always handle VerificationMismatch caused by BadZipFile

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#708]
When verification shows that result should be `MISMATCH` or `ERROR` then `handle_verification_results` decorator should catch `VerificationMismatch` exception and pass to `verification_result` function `MISMATCH` or `ERROR` result without raising exception and causing error on sentry. 

All needed informations on sentry: https://talkback.golem.network/sentry/concent/issues/28905/

Please add new api-integration-tests` to `MISMATCH` result

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159559406
