### ISSUE TITLE
Use larger chunk size when downloading files with `requests` to reduce the speed overhead

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#714]
There should be added setting which will say how big chunk size is. Problem occurred when Concent got bigger file to save in verifier_storage and then render. Default value for `chunk_size` in `response.iter_content()` is `1`. 

From requests package -> ```def iter_content(self, chunk_size=1, decode_unicode=False)```

It should be a modifiable setting. I think that `CONCENT_CHUNK_SIZE` might be good name for this setting. What do you think @cameel ? Also how big `chunk_size` should be? 1024 bytes?

**Comment by rwrzesien** [comment]
If it is a setting, please add checks that:
- it is set only if `verifier` is in `AVAILABLE_CONCENT_FEATURES`.
- if set, it is positive int.

I think the name should be more related to verifier, ie. `VERIFIER_DOWNLOAD_CHUNK_SIZE`.

**Comment by cameel** [comment]
From what I see the size is a trade-off between memory usage and speed/responsiveness. A low value will work with less memory but you will need to process more smaller chunks which will have a bigger overhead. 1 byte at a time is quite extreme. I think we should try higher values. We're not very constrained with memory so high values are fine for us. Verifier needs a lot of memory because of Blender anyway. I think that 1 megabyte should be OK. But please test it with a large file (>= 1 GB) and chunk sizes of 1, 10, 100, 1000, ..., up to 1 gigabyte. Look at transfer speed and memory usage of the process. Post results in a table in a comment below.

Defining a setting for this is fine. But it should have a default. Also, whether it should be a general setting or one for verfier depends on your results. If it turns out that using a lot of memory is better, we'd probably still prefer to use less if we do a download in a different component. But if values over 1 MB don't help much, it would be fine to use this setting in the future or other components too if we ever need to make a download in them.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159649243

**Comment by kbeker** [comment]
#### `RAM usage in chunk_size function for file 2,8GB`
chunk_size [B]  | RAM usage [GB] | time [s] |
|------------------------|------------------|-----------------|
| 1                          | ~3 | too long didn't test
| 10                        | ~3 | 96.05483078956604
| 100                      | ~3 | 11.57115912437439
| 1000                    |~3  | 3.6279618740081787
| 10000                  | ~3 | 2.1257567405700684
| 100000                | ~3 | 1.8617238998413086
| 1000000              | ~3 | 1.225475549697876
| 10000000            | ~3 | 1.3610854148864746
| 100000000          | ~3 | 2.2390296459198
| 1000000000        | ~3 | 2.200515031814575
| 10000000000      | ~3 | 1.0469863414764404

#### `RAM usage in chunk_size function for file 1,4GB`
chunk_size [B]  | RAM usage [GB] | time [s] |
|------------------------|------------------|-----------------|
|1                          | ~1,5 | too long didn't test
|10                        | ~1,5 | 48.70388388633728
|100                      | ~1,5 | 5.953270196914673
|1000                    | ~1,5 | 1.8934152126312256
|10000                  | ~1,5 | 0.9374582767486572
|100000                | ~1,5 | 0.691551923751831
|1000000              | ~1,5 | 0.6295783519744873
|10000000            | ~1,5 | 0.7678999900817871
|100000000          | ~1,5 | 1.0419337749481201
|1000000000        | ~1,5 | 1.1349656581878662
|10000000000      | ~1,5 | 0.5774588584899902

**Comment by kbeker** [comment]
@rwrzesien 
>it is set only if verifier is in AVAILABLE_CONCENT_FEATURES.

This you mean `CONCENT_FEATUTER`?

**Comment by rwrzesien** [comment]
Yes, right.

**Comment by cameel** [comment]
@kbeker You asked about easily making a plot from these points. It's trivial with GNU plot.

### `speed-vs-chunk-size.dat`
```
1
10          96.05483078956604
100         11.57115912437439
1000        3.6279618740081787
10000       2.1257567405700684
100000      1.8617238998413086
1000000     1.225475549697876
10000000    1.3610854148864746
100000000   2.2390296459198
1000000000  2.200515031814575
10000000000 1.0469863414764404
```

### `gnuplot` Command
#### Display plot in a window
``` bash
echo "
    set logscale x
    set style fill solid
    plot 'speed-vs-chunk-size.dat' using 1:2 with boxes
" | gnuplot --persist
```

One-liner without line breaks:

``` bash
echo -e "set logscale x\nset style fill solid\nplot 'speed-vs-chunk-size.dat' using 1:2 with boxes" | gnuplot --persist
```

#### Save plot to a .png file
``` bash
echo "
    set output 'speed-vs-chunk-size.png'
    set terminal png size 800,600 enhanced
    set logscale x
    set style fill solid
    plot 'speed-vs-chunk-size.dat' using 1:2 with boxes
" | gnuplot
```

![speed-vs-chunk-size](https://user-images.githubusercontent.com/137030/43911828-c49694f2-9c00-11e8-894e-3cca84402c38.png)

#### Print the plot on the command line
``` bash
echo "
    set terminal dumb
    set logscale x
    set style fill solid
    plot 'speed-vs-chunk-size.dat' using 1:2 with boxes
" | gnuplot
```

```
  100 +--------------------------------------------------------------------+
      |****** +      +       +       +      +       +       +      +       |
   90 |-+   *                  'speed-vs-chunk-size.dat' using 1:2 *******-|
      |     *                                                              |
   80 |-+   *                                                            +-|
      |     *                                                              |
   70 |-+   *                                                            +-|
      |     *                                                              |
   60 |-+   *                                                            +-|
      |     *                                                              |
   50 |-+   *                                                            +-|
      |     *                                                              |
   40 |-+   *                                                            +-|
      |     *                                                              |
   30 |-+   *                                                            +-|
      |     *                                                              |
   20 |-+   *                                                            +-|
      |     *                                                              |
   10 |-+   ********                                                     +-|
      |     * +    ********* +       +      +       +       +      +       |
    0 +--------------------------------------------------------------------+
      10     100    1000   10000   100000 1e+06   1e+07   1e+08  1e+09   1e+10
```

### Styling the plot
That's just a simple plot, basically without any styles.

You can see more simple examples here: [How do you plot bar charts in gnuplot?](https://stackoverflow.com/questions/327576/how-do-you-plot-bar-charts-in-gnuplot)

If you want to style it more, it's very easy to find example by googling around.

**Comment by kbeker** [comment]
Ooo, thanks @cameel. Stored for future usage :)
