### ISSUE TITLE
Verifier parses out incorrect frame numbers from file names in the result package

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#715]
Function `parse_result_files_with_frames` in `verifier.utils` does not always work correctly. 
It should parse files which have theirs names like : "task_70002.png".

From `golem_chat`:
>Raczej 0002 oznacza numer klatki
A 7 numer subtaska 

For now this function won't catch it because it assumes that files name should look like this: `_0001.png`

**Comment by cameel** [comment]
> From `golem_chat`:
> >Raczej 0002 oznacza numer klatki
> A 7 numer subtaska 

Ignore this. This was just a guess. These file names came from a screenshot sent by @lukasz-glen and that was probably not what's really inside the package. At least @shadeofblue could not explain them with confidence and suggested for us to look at a real package produced by Golem.

So please check how those file names look like in a real package.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159649280

**Comment by kbeker** [comment]
This is what I found in in golem repo:
```
'GolemTask_10001.png'
'GolemTask_10002.png'
'out_420001.exr'
```

So I think that that our parser should parse files which has in theirs names `_xxxxyyyy.zzz`
where:
xxxx - number of task
yyyy - number of frame
zzz - file extension

**Comment by cameel** [comment]
@kbeker
But where did you find it? In the code or in tests? Tests often have dummy data so you should not rely on it. Please submit a golem task as a requestor and see how it looks like just in case.

Also, what was the task and subtask ID in these? Do these names come from different packages or from a single one?
