### ISSUE TITLE
Change port number in MiddlemanProtocol tests 

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#721]
For this moment tests in`MiddlemanProtocol` causes errors when nginx is locally launched. 

```python
        with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as server_socket:
            server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
            with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as client_socket:
                client_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
>               server_socket.bind(('127.0.0.1', 8001))
E               OSError: [Errno 98] Address already in use

tests/test_stream.py:356: OSError
```

Please change port `8001` to port number which won't be occupied by some other service

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159659180

**Comment by dybi** [comment]
please use `unused_tcp_port` or `unused_tcp_port_factory` fixtures (https://github.com/pytest-dev/pytest-asyncio#unused_tcp_port) for ensuring that free (non occupied) TCP port is used in tests
