### ISSUE TITLE
Make MiddleMan protocol responsible for generating request_id

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#726]
Currently `request_id` can be passed as parameter when creating new MiddleMan protocol message. This can lead clients to create their own handlers its value, each one implemented differently.

To avoid this, MiddleMan protocol should handle generating request_id on its own. To achieve this:
- Make passing parameter as optional. If it is not passed, protocol should generate it. It must be still possible to pass it manually for responses. It should be also possible to pass function generating ID.
- If passed manually, it should be validated that it is either `int` or function generating ID.
- There should a defined constant for `request_id` for responses for messages that was not able to be deserialized (it should be equal to `0`).

**Comment by cameel** [comment]
> If it is not passed, protocol should generate it.

I think we should just allow passing a function that generates IDs. Also provide some function in the protocol and use it as a default.

> as we have to allow both `UUID` and integer `0`).

We don't want o allow both at the same time. The type of the ID was supposed to be hard-coded in the protocol.

**Comment by rwrzesien** [comment]
> I think we should just allow passing a function that generates IDs. Also provide some function in the protocol and use it as a default.

But for responses you have to use the same ID. Also, you have to manually set `0` for responses for invalid frames.

**Comment by cameel** [comment]
OK. But it could at least be a helper function meant to be used by default. The caller could get the ID from it and pass it to the sending function instead of having to generate it by himself even in the simplest use cases.

**Comment by rwrzesien** [comment]
I agree, I just wanted to point out that we still need also possibility to set it manually for mentioned cases.

**Comment by rwrzesien** [comment]
Closed, as after discussion no changes are needed with current implementation.
