### ISSUE TITLE
`TypeError - expected string or bytes-like object` raised when updating a subtask

### ISSUE THREAD

**Issue by PaweuB** [golemfactory/concent#729]
Still active exception from Sentry as described in: #195 
https://talkback.golem.network/sentry/concent/issues/29/

Added as a New Story/Bug in Pivotal:
https://www.pivotaltracker.com/story/show/159822787

@pawelkisielewicz please provide more details in description.

**Comment by cameel** [comment]
@PaweuB I don't think we need a new issue for this on Github. #195 is fine. I'd only create a new one on Pivotal and link it with the same issue on Github.

Issues on Pivotal are for planning so having two is fine. On Github we prefer to have the discussion in a single place.

So I suggest closing this one and linking to #195 from Pivotal.

**Comment by PaweuB** [comment]
Ok, so I'm closing this Issue. Discussion continued in #195
