### ISSUE TITLE
Integration tests for "Provider forces requestor to accept or reject results" use case

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#73]
Add integration tests for https://github.com/golemfactory/concent/issues/41. 

**We are not doing 4A for now.**

- Try to follow our existing convention, but if also possible try to follow https://github.com/golemfactory/concent/issues/70. We now have core/tests/utils.py where repeatable pieces of code can be put.
- Apart from creating test for every single scenario described in blueprints, please try to add negative scenarios, like in https://github.com/golemfactory/concent/issues/21 (ie. sending a message twice, sending message when previous message has not been sent, sending contradictory messages, sending messages when his time window is already over, trying to fetch messages when queue is empty, etc.).
- The payment API which is used in this use case should be mocked, a mock example can be found in `test_integration_get_task_result.py`, this one might be more complex, probably requiring mocking requests lib for a particular tests.
- Tests that will not be use case specific should be put in separate test case (I think there should exists one by now).
- Add any necessary new tests.

**Comment by cameel** [comment]
@rwrzesien @kbeker What is the status of this task? Is it in pivotal? Is it done?

**Comment by rwrzesien** [comment]
@cameel 
It is done, it was done as a part of 3rd use case.
