### ISSUE TITLE
Create shell script to install requirements from Signing Service, MiddleMan Protocol and Concent_api

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#731]
Currently to run all tests we need to install all requirements separately in Singing Service, MiddleMan Protocol and in Concent_api. We should have one script which would do this for us. 
Script should be placed in directory where is `full_check.sh`.
It should install:
- requirements from concent_api
- requirements from singing_service
- requirements from middleman_protocol

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159846621
