### ISSUE TITLE
Replace CONCENT_ETHEREUM_ADDRESS with CONCENT_ETHEREUM_PUBLIC_KEY 

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#735]
Replace `CONCENT_ETHEREUM_ADDRESS` with `CONCENT_ETHEREUM_PUBLIC_KEY`. Generate `CONCENT_ETHEREUM_ADDRESS` from `CONCENT_ETHEREUM_PUBLIC_KEY`.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159848266

**Comment by cameel** [comment]
Please remember that this needs to be synchonized with deployment. We need to change the settings in our configs there.
