### ISSUE TITLE
[Bankster Testing] Create wrappers for basic communication.

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#741]
This is part of #647. It depends on https://github.com/golemfactory/concent/issues/740.

Create wrappers for basic communication.
- For sending requests to `ConcentApi`, reuse helpers from `api_testing_common.py`.
- For `MiddleMan` and `SiginingService`, create one wrapper which:
    - Creates a socket and connects it to given component.
    - Creates a given `Frame` with given payload.
    - Uses `MiddleMan` protocol for sending `Frame` over created socket.
    - Uses `MiddleMan` protocol for receiving response.
    - Verifies that response is as expected.
- For `Ethereum Blockchain`, create several wrappers which:
    - Set equal balance on used `Ethereum` accounts. This should be launched at the beginning of the test which tests `Ethereum Blockchain` component.
    - Get `Ethereum` account balance using `PaymentInterface`.
    - Get `Ethereum` account balance and check if it is equal to expected using `PaymentInterface`.

**Comment by dybi** [comment]
@rwrzesien, one remark - wrappers should be very much like `sci_callback`, i.e. they should mimic SCI callback as much as possible (best: reuse functions defined there)

**Comment by rwrzesien** [comment]
@dybi I was thinking about making them more generic. I am not sure if we need whole `SCI Callback` functionality just to send message through socket, but at the end we might end up with something very similar :)

I guess you have meant a case when message is sent to `MiddleMan`, right ?

Please remember that there will be also tests that goes through `SCI Callback` => `MiddleMan` => `SigningService => `MiddleMan` => `SCI Callback`, so it the whole flow will also be tested.

**Comment by rwrzesien** [comment]
Closing, as this work will be divided between #742, #742 and #744.
