### ISSUE TITLE
[Bankster Testing] MiddleMan

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#743]
This is part of #647. It depends on #740.

- Create one wrapper which:
    - Creates a socket and connects it to given component.
    - Creates a given `Frame` with given payload.
    - Uses `MiddleMan` protocol for sending `Frame` over created socket.
    - Uses `MiddleMan` protocol for receiving response.
    - Verifies that response is as expected.

Create a test suite for testing communication flow: request to `MiddleMan` => `MiddleMan` should send request and get response from `SigningService` => Response from `MiddleMan`.

TODO: Specify test cases

**Comment by dybi** [comment]
@rwrzesien: defined scanarios are here: https://github.com/golemfactory/concent/issues/724

**Comment by rwrzesien** [comment]
@dybi I think the fun will start when you add routing and queues :) I see you have added the scenarios I was thinking of too, like sending several messages simultaneously, and mixing correct and incorrect messages. Lets see what else can we think of. 

If you want we can merge those two issues.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159927457
