### ISSUE TITLE
E2E tests for full transaction lifecycle after introducing SCI Callback 

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#744]
This is part of #647. It depends on #741.

Create a test suite for testing communication flow: request to `ConcentApi` with `ForcePayment` Golem message => `ConcentApi` should make force payment to provider and call `SCI Callback` => `SCI Callback` should send request and get response from `MiddleMan` => Transaction should appear on `Ethereum Blockchain` and update accounts balance.

For sending requests to ConcentApi, reuse helpers from `api_testing_common.py`.
For `Ethereum Blockchain`, create several wrappers which:
    - Set equal balance on used `Ethereum` accounts. This should be launched at the beginning of the test which tests `Ethereum Blockchain` component.
    - Get `Ethereum` account balance using `PaymentInterface`.
    - Get `Ethereum` account balance and check if it is equal to expected using `PaymentInterface`.

1. Test that sending correct `ForcePayment` will result in changing used Ethereum account balance with values from `ForcePayment`.

EDIT:

2. Test that sending correct `ForcePayment` when requestor has `0` funds on his deposit account, will result in concent sending `ForcePaymentRejected`response with reason: `NoUnsettledTasksFound`

3. Test that sending correct `ForcePayment` when requestor has insufficient (but `requestor_balance > 0`) funds on his deposit account,  will result in transffering all available deposit funds from `requestor`'s account to `provider`'s account.

**Comment by dybi** [comment]
@rwrzesien, do we have any proposals of how to automatically evaluate if Ethereum account balance has been changed?

**Comment by rwrzesien** [comment]
@dybi As discussed with @kbeker today, we can do this using the same way Concent does it, which is `common.singleton.PaymentInterface.get_deposit_value`, because:
1. This tests should be allowed to make imports from `concent_api`, as current cluster tests do. 
2. We will know Ethereum addresses from `TaskToCompute` from `ForcePayment`.

Actually, it looks like it will be the only way to do this. Unfortunately we cannot check if given `Transaction` had appeared on blockchain, because its hash will be not known for the test.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/159927519

**Comment by dybi** [comment]
Updated with TC#2 and TC#3 description.
@cameel is 

> 
2. Test that sending correct `ForcePayment` when requestor has `0` funds on his deposit account, will result in concent sending `ForcePaymentRejected`response with reason: `NoUnsettledTasksFound`

really the desired behavior? `NoUnsettledTasksFound` seems a bit misleading in this case.

**Comment by cameel** [comment]
Based on Łukasz's documentation I think it should be `ServiceRefused` with `TooSmallRequestorDeposit`. Generally #996 is now the place where this is documented (see the table with prerequisite conditions). The Golem team has not accepted it yet but I'm going to update it if they tell us it should be something else.
