### ISSUE TITLE
Getting version by `setup.py` in Singing Service and MiddleMan Protocol

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#745]
Currently script `setup.py` in SS and MM Protocol gets version only when `RELEASE-VERSION` file exists. This way of importing version prevent installation these apps as a requirements from e.g. `requirements.lock` file. 
There should be added importing version by script same way as it is done in golem_messages repo -> https://github.com/golemfactory/golem-messages/blob/master/setup.py#L7

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159919495
