### ISSUE TITLE
Create shell script for generating requirements-development.lock

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#746]
Script should create file `requirements-development.lock` with newest `requirements-development.txt`.

Script should do:
1. Create clean virtual environment.
2. Install requirements.lock
3. Install requirements-development.txt
4. Generate requirements-development.lock from `pip freeze`
5. Delete virtual environment.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159920388

**Comment by cameel** [comment]
After talking with @kbeker, this needs to work a bit differently.

The script for generating `requirements-development.lock` file should work just like the one for `requirements.lock`. In fact, this should probably be a single script with path to the requirements file as a parameter. It should assume that the packages are already installed and just need to be frozen into the `.lock` file.

But we may want to have additional script that creates a clean virtualenv, installs the packages and calls the script described above. Basically, a script version of our procedure for regenerating the requirements files.

**Comment by dybi** [comment]
@kbeker, please update the description, so it reflects what is really being done in this issue

**Comment by cameel** [comment]
@kbeker What about the description?
