### ISSUE TITLE
Use one retry of message trying to store subtask

### ISSUE THREAD

**Issue by pawelkisielewicz** [golemfactory/concent#759]
There is another one problem similar to https://github.com/golemfactory/concent/issues/718, but in case when subtask does NOT exist in database. The case and solution should look like this:

1. Two or more messages are trying to create a new subtask (the same) in our database at one time. 
2. One of them will success, others will fail with IntegrityError. 
3. We should catch this IntegrityError in `store_subtask`, create a new custom Error only for this case and raise this new Error. 
4. New Error should be caught at the beginning of validations (e.g. beginning of `handle_message` or `view`. Important is to do it before database lock for existing subtasks). This custom Error is necessary to be 100%, we are catching error from `store_subtask` and not from other parts of application. I'm not sure if it would be possible, but this way we are 100% that 'new Error' comes from `store_subtask`
5. Message should be retried and validated again. It is possibility that concent will answer with e.g. `ServiceRefused.REASON.DuplicateRequest`, but message should try to pass all validations again with new database state (after one process successfully finished). There is no danger the same problem will be again, because subtask with this id will already exist in database and we use select_for_update lock to execute all processed one by one, if there will be more than one waiting.

In this case inside function store_subtask may be a good idea to create a new nested atomic block, but only inside this particular function to:
- gracefully rollback changes from this function if necessary
- catch IntegrityError and raise new custom Error to retry validations ONLY in this case

**Comment by cameel** [comment]
1) This is really the same problem as in #486
2) This is not limited to `Subtask`. We should do this in all cases where we create a new object in the database.
3) You can check the PostgreSQL error code from the exception with `exception.__cause__.pgcode`.
    - [IntegrityError: distinguish between unique constraint and not null violations](https://stackoverflow.com/questions/12490172/integrityerror-distinguish-between-unique-constraint-and-not-null-violations)
    - [psycopg2.errorcodes](http://initd.org/psycopg/docs/errorcodes.html)
4) Unfortunately a nested atomic block is not enough. To get an `IntegrityError` you need to commit the whole transaction. To implement this correctly we really need `@atomic` blocks smaller than a view.
    - The transaction **must** be committed before you perform any action that may have irreversible side-effects. Like adding tasks to queue or making payments. Without this retry is not safe.

**Comment by pawelkisielewicz** [comment]
OK. 
Ad. 1 - right :)
Ad. 2 - right, I think it should be separate issue for this ('find and fix other cases like this'). But I would first fix this problem only for subtasks in this issue and in second step, after merge to master other cases. Is it ok?
Ad. 3 - will check :)
Ad. 4 - maybe use `on_commit` function. It will be not so hard to implement, safe and splits explicitly functions calling side-effects. But also in separate issue. What do you think?
