### ISSUE TITLE
Passing environment and component names to the Signing Service

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#762]
In deployment we always configure `RAVEN_CONFIG` with the name of the current environment (`concent-dev`, `concent-staging`, etc.) and component (`concent-api`, `gatekeeper`, `conductor`, etc.):

See [an example of `RAVEN_CONFIG` in concent-api/local_settings.py](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/kubernetes/config-maps/concent-api/local_settings.py.j2#L42-L46).

This allows us to see in Sentry where the error happened. To get that in Signing Service we need to:
- Allow specifying environment name on the command line (`--sentry-environment` option).
- Hard-code component name to `signing-service`.

Environment name can be an arbitrary string. It's not mandatory - if not specified, the `environment` key  should simply not be present in `RAVEN_CONFIG`.

Add information in the `README` that this option exists and that it should match the Concent environment.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160092152
