### ISSUE TITLE
Views sometimes overwrite a subtask when they're supposed to create it or fail

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#770]
The problem originally came up in this review: https://github.com/golemfactory/concent/pull/764#discussion_r213659010

Our views use `store_or_update_subtask()` to create or update a subtask, depending on whether it already exists or not. The problem is that subtask data passed to the function is fetched first and only then the function checks whether the subtask exists. This means that if another process creates the subtask after the data has been fetched but before the check, the subtask is updated even though the view should report that the subtask already exists and fail with HTTP 5xx.

To fix this, the code should decide whether the subtask needs to be created or updated only once and not change that decision. You can achieve that by splitting `store_or_update_subtask()` into separate `create_subtask()` and `update_subtask()` and moving the check to the view.

Also, remember to use `select_for_update()` when you fetch the data that will later be used to update the subtask and/or check subtask's existence. It's best if the check and fetching are actually a single query (i.e. use `get()` or `filter()` instead of `exists()` and then check existence by simply looking at the result/catching the exception).

### Example illustrating the problem
1. Client 1 submits message x with `subtask_id = A`.
2. Client 2 submits message y with `subtask_id = A`.
3. Process 1 checks if subtask with `subtask_id = A` exists. It does not.
4. Process 2 checks if subtask with `subtask_id = A` exists. It does not.
5. Process 1 prepares subtask X with `subtask_id = A` and data from message x.
6. Process 2 prepares subtask Y with `subtask_id = A` and data from message y,
7. Process 1 calls  `store_or_update_subtask()`
    1. `store_or_update_subtask()` checks if subtask with `subtask_id = A` exists. It does not.
    2. `store_or_update_subtask()` tries to save subtask X and succeeds.
8. Process 2 calls  `store_or_update_subtask()`
    1. `store_or_update_subtask()` checks if subtask with `subtask_id = A` exists. It does.
    2. `store_or_update_subtask()` updates subtask X with data from subtask Y and succeeds.
9. Result
    - Both clients get HTTP 2xx. Both succeeded.
    - Both clients may have triggered Irreversible actions for the same subtask.
    - Data from message x has been overwritten by data from message y. One subtask has been created but irreversible actions were executed twice.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/160169099
