### ISSUE TITLE
Decoded responses by Content-type instead of status in api tests

### ISSUE THREAD

**Issue by pawelkisielewicz** [golemfactory/concent#772]
Currently in our api tests we are deciding, how to decode response using response status. This is not good approach, we should use content_type to decide how to decode response.  As @cameel wrote, "Responses with the same code can have different content in different situations." 
See comments in https://github.com/golemfactory/concent/pull/764 for more details

**Comment by cameel** [comment]
I see that we have a regression from #72. It's back. Could you fix it while you're at it? It's pretty trivial one-line change so I don't want to create a separate another issue for it.

**Comment by cameel** [comment]
You have a typo in the title.

**Comment by cameel** [comment]
The proper way to decode a HTTP response in the simplest case (i.e. we don't care about encoding, origins, cookies, redirects, etc.) is this:
- If `Content-Type` header is present and response body is empty -> response is invalid
- If `Content-Type` header is missing and response body is non-empty -> response is invalid
- If `Content-Type` is not one of the supported formats -> cannot decode response
- Try to decode response body based on `Content-Type`.
    - E.g. if it's `application/json`, use `json.loads()`. If it's `text/plain`, just assume UTF-8 and convert it from `bytes` to `str`. If it's XML, use an XML parser.
- If decoding fails -> cannot decode response

If it did not fail at any step above, you have a decoded response you can process according to application's internal rules. Note that it might be a successful response (HTTP 2xx), an error response (HTTP 4xx, HTTP 5xx) or something else (e.g HTTP 1xx, HTTP 3xx) . To know which one it is you have to look at the HTTP status code.

- HTTP 2xx can be simply processed
- HTTP 4xx should be treated as a problem in your application and fixed unless you specifically know that it can happen in your case and expect it
- HTTP 5xx is a bug or a transient failure on the server side. All you can do here is to retry later or give up saying that the server is broken.
- You won't normally get HTTP 3xx becase many HTTP clients (e.g. `requests`) resolve redirects by default. So if it happens, there must be something wrong in your program - treat like you treat HTTP 4xx.
- HTTP 1xx is an informational response. You can only get it if you're doing something special like streaming downloads or switching protocols. So if you're not doing anything like that, it must be some misconfiguration on the server side. Treat it like you treat HTTP 5xx.
