### ISSUE TITLE
Update `task_id` and `subtask_id` in tests that are not uuid

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#776]
There are still left a lot of `task_id` and `subtask_id` in tests which are defined as not uuid strings. Please fix them all.

Also, it is worth checking why tests were passing with wrong `task_id` and `subtask_id`. Maybe it would be good to add `error_code` checking in those places.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160233197
