### ISSUE TITLE
Merge `receive/` and `receive-out-of-band/` into one endpoint

### ISSUE THREAD

**Issue by Jakub89** [golemfactory/concent#787]
Step 1(before any change in golem-app):
- Allow `receive/` endpoint to return `receive_out_of_band` messages.
- Adjust message handlers.
- Change tests to use `receive` instead of `receive_out_of_band` endpoint.

~~Step 2:~~
- ~~Wait for golem until they stop using `receive_out_of_band/` endpoint.~~

~~Step 3:~~
- ~~Delete `receive_out_of_band/` endpoint.~~

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160283588

**Comment by cameel** [comment]
1. Don't delete the view. It should still stay in the API for compatibility. Add a separate task for removing it later, when Golem no longer uses it.
2. Don't forget that we still need its functionality. The messages should still be returned, just from `receive/`, not `receive-out-of-band/`.

**Comment by Jakub89** [comment]
@cameel issue updated

**Comment by PaweuB** [comment]
Pivotal for Part 2 & 3 of #787: 
https://www.pivotaltracker.com/story/show/160384405

Keep this Issue open till fulfilling part 2 und 3.

**Comment by cameel** [comment]
@Jakub89 When you merge this please drop a comment in #264 so that I remember I have to update it.

**Comment by cameel** [comment]
@Jakub89 Is this done? I think that part 2 and 3 should be covered by separate issues.

**Comment by Jakub89** [comment]
part2: #842
