### ISSUE TITLE
SigningService: Make _set_was_sigterm_caught_true a method and test it

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#803]
In early stages of `SigningService` implementation `_set_was_sigterm_caught_true` was defined as function inside a method. This way it cannot be unit tested.

I have made a quick prove of concept that it can be a method too, which will allow to unit test it.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160478329

**Comment by dybi** [comment]
still valid, priority `low`
