### ISSUE TITLE
SigingService: Exclude `if __name__ == .__main__. ` from coverage report

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#804]
There is a part of SigingService which is used to run main script. There is no way to unit test it (at least I couldn't find any which doesn't modify the current code). This part doesn't contain any logic, just instantiates components, so it could be excluded from report.

```
[report]
exclude_lines =
    if __name__ == .__main__.:
```

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160478329
