### ISSUE TITLE
Add unit tests for core/payments/backends/sci_backend.py

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#810]
`core/payments/backends/sci_backend.py` has functions which execute some logic, however they are mocked in integration tests, hence not really tested at all. Unit tests for them should be added.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160478633

**Comment by dybi** [comment]
not valid anymore - there is 98% coverage ATM, closing.
