### ISSUE TITLE
Wrong expiration deadline in FileTransferToken in verification

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#827]
When a provider submits `SubtaskResultsVerify`, Concent generates and returns a `FileTransferToken` that allows uploading both source and result packages. The timing blueprint (#165) states that the upload must end before `SubtaskResultsRejected.timestamp` + AVCT so this also should be the expiration time.

Actually due to changes in Łukasz's specification this is now `SubtaskResultsRejected.timestamp` + AVCT + MDT, but the blueprint has not been updated to reflect that yet.

In the code I see that the token is generated by `create_file_transfer_token_for_golem_client()` that calls `calculate_token_expiration_deadline()`. The resulting time for upload is `TaskToCompute.deadline` + 3 * CMT + 2 * MDT which is completely wrong for this use case.

I'm surprised it even works in our tests - verification is not allowed to start before `TaskToCompute.deadline` + `SVT`, which is much longer than that. That's probably because due to #538 we just assume that `SubtaskResultsRejected.timestamp` is after that (which in tests might not be).

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160545038
