### ISSUE TITLE
Fix and update verification time windows

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#828]
Due to inconsistencies I have mentioned in https://github.com/golemfactory/concent/pull/431#issuecomment-419968127 I reviewed our time windows in verification and looks like they are way off due to a mix of my mistakes in issue descriptions, bugs in the code and Łukasz's specification changes.

### Current state
- [Deadline for submitting `SubtaskResultsVerify`](https://github.com/golemfactory/concent/blob/v0.8.0/concent_api/core/message_handlers.py#L1335-L1344): `SubtaskResultsRejected.timestamp` + AVCT
- [Deadline for receiving `upload_finished`](https://github.com/golemfactory/concent/blob/v0.8.0/concent_api/core/message_handlers.py#L1385-L1396): `SubtaskResultsRejected.timestamp` + AVCT
- [Deadline for receiving `verification_result`](https://github.com/golemfactory/concent/blob/v0.8.0/concent_api/core/tasks.py#L73-L78): `SubtaskResultsRejected.timestamp` + AVCT + SVT
- [Upload token deadline](https://github.com/golemfactory/concent/blob/v0.8.0/concent_api/core/transfer_operations.py#L296-L301): `TaskToCompute.deadline` + 3 * CMT + 2 * MDT
- [Blender rendering deadline](https://github.com/golemfactory/concent/blob/v0.8.0/concent_api/core/message_handlers.py#L1398-L1401): `SubtaskResultsRejected.timestamp` + AVCT

### Expected state
- Deadline for submitting `SubtaskResultsVerify`: `SubtaskResultsRejected.timestamp` + AVCT + MDT
- Deadline for receiving `upload_finished`: `SubtaskResultsRejected.timestamp` + AVCT + MDT
- Deadline for receiving `verification_result`: `SubtaskResultsRejected.timestamp` + AVCT + MDT + CVT
- Upload token deadline: `SubtaskResultsRejected.timestamp` + AVCT + MDT
- Blender rendering deadline: `SubtaskResultsRejected.timestamp` + AVCT + MDT + CVT

Those changes are not on the timing diagram yet. They'll be added when this is implemented. Here's what the diagram will look like after they're introduced.

![concent-timing](https://user-images.githubusercontent.com/137030/45563348-5aca4c80-b84d-11e8-8e1c-3f915086cb2d.png)

#### Wrong expiration deadline in `FileTransferToken`
See #827.

#### Blender's deadline does not include time for rendering
SVT is the time for rendering and should be included in the deadline passed to `blender_verification_request()`.

#### Changes in Łukasz's specification
AVCT used to cover both accepting `SubtaskResultsVerify` and upload. Now there's a separate MDT interval for upload.

Changing this now would introduce a third state in verification and make it more complex. I propose to simply use AVCT + MDT instead of AVCT. Having more time to submit the message should not really be a problem for a compliant client.

#### Design errors in #556
In #556 I specified that AVCT is the time for rendering and that it's not defined by the protocol. That was wrong. AVCT is the time for submitting `SubtaskResultsVerify`. It may also be used for rendering if the message and upload come faster but that's not guaranteed. The changes we did to AVCT should have been applied to SVT.

For that reason I'm defining a new setting: CVT (`CONCENT VERIFICATION TIME`). It replaces the SVT and now should be computed as: `(TaskToCompute.deadline - TaskToCompute.timestamp) * ADDITIONAL_VERIFICATION_TIME_MULTIPLIER / BLENDER_THREADS`. AVCT should just be a normal setting with a default imported from golem-messages.

**Comment by cameel** [comment]
If you finish and merge this task before #431 is merged, please drop a comment there that the diagram needs to be updated. Otherwise the diagram update will be separate pull request.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160544990

**Comment by rwrzesien** [comment]
@cameel 
> AVCT should just be a normal setting with a default imported from golem-messages.

What is the corresponding name of the constant in golem-messages? I couldn't find anything relevant.

**Comment by cameel** [comment]
Should be simply AVCT or ADDITIONAL_VERIFICATION_CALL_TIME. There's a possibility that it's not defined there yet and will have to be added.

**Comment by rwrzesien** [comment]
> Should be simply AVCT or ADDITIONAL_VERIFICATION_CALL_TIME. There's a possibility that it's not defined there yet and will have to be added.

It is not there yet, I will add it as blocker in Pivotal.

**Comment by cameel** [comment]
Add an issue in golem-messages too.
