### ISSUE TITLE
Invalid messages in the receive queue crash staging

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#84]
We're getting HTTP 500 responses when calling the `receive/` endpoint on the staging server. The error is `NoneType object has no attribute ‘TYPE’` and happens because `decoded_message_data` gets the value of `None` from `deserialize()`.

The most probable cause is that `send()` is putting invalid messages into the database and deserialization fails but golem-messages returns `None` instead of raising an exception.

Staging has database migrated over from previous versions. Maybe the content of the data stored in the database has changed while schema remained the same and we're missing a data migration.

Investigate why the error happens and prepare a patch or a migration that will allow us to bring staging back to operation.

The issue can be reproduced with a call to `receive/`:

``` bash
curl -X POST http://35.198.165.137/api/v1/receive/ \
    --header "Concent-Client-Public-Key: ulzgu7fuaac9r+19TZXKkdki8m5v8xOG6cJeUCiEBdLsVEriADPGmP5i3Go6Gt1JIzTBO/Igofn5DLOCcEqwKw=="
```

### Stack trace
```
File “/srv/http/virtualenv/lib/python3.5/site-packages/django/core/handlers/exception.py” in inner
41.             response = get_response(request)
File “/srv/http/virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response
187.                 response = self.process_exception_by_middleware(e, request)
File “/srv/http/virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response
185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File “/usr/lib/python3.5/contextlib.py” in inner
30.                 return func(*args, **kwds)
File “/srv/http/virtualenv/lib/python3.5/site-packages/django/views/decorators/csrf.py” in wrapped_view
58.         return view_func(*args, **kwargs)
File “/srv/http/concent_api/utils/api_view.py” in wrapper
57.             response_from_view = view(request, message, *args, **kwargs)
File “/srv/http/virtualenv/lib/python3.5/site-packages/django/views/decorators/http.py” in inner
40.             return func(request, *args, **kwargs)
File “/srv/http/concent_api/core/views.py” in receive
71.     assert last_undelivered_message_status.message.type == decoded_message_data.TYPE
Exception Type: AttributeError at /api/v1/receive/ Exception Value: ‘NoneType’ object has no attribute ‘TYPE’
```

**Comment by rwrzesien** [comment]
@cameel Yes, probably something changes in golem_messages and we can't deserialize old message. I think the only option is to remove those from the database in migration, if that solution is ok I will prepare the migration.

**Comment by cameel** [comment]
Well, whether it's Concent code or golem-messages does not really matter. In production we won't be able to clear the database or freely remove messages. We'll have to fix them or, more likely (since the messages are signed) add an ugly workaround in code that handles them in a special way. I really want us to work from the very beginning with the mindset that there's a set of data that needs to be preserved between updates. This is something we have to be very careful about because it's not easy to go back when we deploy without errors and the code mangles the data. We can't just shrug it off and move on.

I talked about this with Adrian and since we this is not production yet we can make an exception here. I still want you to work on it a bit and find out what the cause is. Whether it's someting that was broken only in the old code or is it still broken. If it's the former, we'll just clear the database but if it's still broken, we need a fix. If it takes too long we'll just give up for now and go back to it later if there's time. But at least give it a go before you give up.

**Comment by rwrzesien** [comment]
@cameel I was just proposing quickest solution, but off course I can spent more time on this and try to fix the original issue. Could you provide me database dump from staging so I can work on exactly same data ?

**Comment by cameel** [comment]
I understand. We need a fairly quick solution here but not necessarily the quickest and dirtiest one possible :) I think that just investigating it and not spending time doing the actual workaround if the issue is only in the old version is a good balance. There's not that much time left until we have to launch and support a production instance and getting used to working with it is just as important as churning out new code.

On Monday I'll dump the data from staging and send it to you.

**Comment by rwrzesien** [comment]
@cameel I have loaded dump and done some investigation. The messages are not able to be deserialized because they were serialized using encryption function. Their header is marked as encrypted. I was able to deserialize messages using decrypt function which just simply returns passed data without doing anything with it, but their content was empty (like ie. task_to_compute was None). That caused different 500 errors along the way. I guess that they can be deserialized using golem_messages.shortcuts.load.decrypt function, but that requires private key which was used during serialization. If we don't have those, I don't think we will be able to do much with this messages, apart from creating new inner objects for them, which I don't think makes much sense. Please let me know what do you think about this, and if that means we can delete those.

**Comment by cameel** [comment]
So this means that the old code was completely broken? That it was not able to deserialize its own stored messages properly?

**Comment by cameel** [comment]
OK. I have cleared the database on staging.

In the future let's try harder to prevent broken data like this.
