### ISSUE TITLE
Extend Signing Service with email notifications

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#877]
this is a part of: https://github.com/golemfactory/concent/issues/872

Implement functionality in `Notifier` class, so it is able to send emails.
E-mail address should be added as a command line mandatory argument for running `Signing Service`:
`-e, --email, type=str`

**[Optional]** Some simple validation for email address could be added (like, it should be string of format `sth@domain.ext`).

`Notifier`'s instance should get this email address as argument and should be passed as argument for `Signing Service` instance.

**Comment by PaweuB** [comment]
https://www.pivotaltracker.com/story/show/161179031

**Comment by Jakub89** [comment]
`-e` is taken by `--sentry-environment` and `-m` is taken by `--max-reconnect-attempts`. I don't know if we need shorter version for `--email`, `-em` maybe?
