### ISSUE TITLE
Extend Signing Service with transaction sum storage

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#878]
This is a part of https://github.com/golemfactory/concent/issues/872

`Signing Service` should store its daily transaction amount in case it is restarted. 

The file should be called  `YYYY-mm-dd`, where `YYYY` stands for year, `mm` for month and `dd` for day, be in a text format and contain single number which would be the sum of  values of daily transactions made so far.

1. Upon creation, `Signing Service` should get current date and check whether there is a corresponding file.
1.1. If yes, it should try to read a single value out of it and set `self.daily_costs_so_far` accordingly
1.2 If no, or if reading from the file fails, `self.daily_costs_so_far` should be set to `0`. In case of failing to read the file, log the warning.
2. When `Signing Service` is asked to sign the transaction, it should check if the operation doesn't exceed daily limit (see: https://github.com/golemfactory/concent/issues/873)
3. Upon successfully signing the transaction, override the file contents.

Note: The files are not deleted - new day means a new file being created.
Note 2: The mechanism is very simple and when need arises could be transformed into DB storage.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161178998
