### ISSUE TITLE
Bankster: Add database models

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#894]
This is a part of the implementation of the "Bankster" blueprint (#479).

Add following models along with migrations:

#### `DepositClaim` model
- **Database**: `control`

| Column name                     | Type                  | Optional | Remarks                                                                                                                 |
|---------------------------------|-----------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `subtask`                       | `Subtask`             | yes      | Foreign key to a subtask object. Can be `NULL` if and only if `concent_use_case` is `ForcedPayment`.
| `payer_deposit_account`         | `DepositAccount`      | no       | The deposit account belonging to the client who is supposed to pay the claim. `payer_deposit_account.ethereum_public_key` cannot be the same as `payee_ethereum_public_key`.
| `payee_ethereum_address`     | string                | no       | Address of the Ethereum account belonging to the entity (requestor, provider or Concent) who is supposed to receive the claim. Cannot be the same as `payer_deposit_account.ethereum_public_key`.
| `concent_use_case`              | `ConcentUseCase`      | no       | Use case in which Concent claim the deposit.
| `amount`                        | int               | no       | The amount claimed. Must be greater than zero.
| `tx_hash`                       | string                | yes      | The hash of the Ethereum transaction that will cover the claim. Empty if the transaction has not been created yet. Must be unique - one transaction can satisfy only one claim.
| `created_at`                    | datetime             | no       | The creation time of the object.
| `updated_at`                    | datetime             | no       | Time of the last modification of any field in the object.

#### `DepositAccount` model
- **Database**: `control`

| Column name                   | Type                  | Optional | Remarks                                                                                                                 |
|-------------------------------|-----------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `client`                      | `Client`              | no       | `Client` who owns the deposit on this account.
| `ethereum_address`         | string                | no       | Address of the Ethereum account belonging to the client who owns the deposit account.
| `created_at`                  | datetime             | no       | The creation time of the object.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161280546

**Comment by dybi** [comment]
@rwrzesien, please update the issue: timestamp is a bit misleading - datetime seems a bit more clear ;)

**Comment by rwrzesien** [comment]
Changed `created_at` and `modified_at` type to `datetime`, as it is correct database type.

Changed `amount` type to `int`.
