### ISSUE TITLE
Bankster: `finalize payment` operation changes

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#896]
This is a part of the implementation of the "Bankster" blueprint (#479).

Requires https://github.com/golemfactory/concent/issues/894 and https://github.com/golemfactory/concent/issues/568 to be implemented first.

There should be some updates in the current implementation of `finalize payment` operation in Bankster to allow it to follow deposit state.

##### Input - replace current input with:
| Parameter                     | Type                              | Optional | Remarks                                                                                                                 |
|-------------------------------|-----------------------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `deposit_claim`               | `DepositClaim`                    | no       | The claim to pay.

##### Output - replace current output with:
| Parameter                     | Type                              | Optional | Remarks                                                                                                                 |
|-------------------------------|-----------------------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `tx_hash`                     | string                            | yes       | Hash of an Ethereum transaction that was created. Empty value if no transaction was actually submitted.

##### Sequence of operation - replace current sequence with:
1. **Deposit query**
    - Bankster asks SCI about the amount of funds available on the deposit account listed in the `DepositClaim`.
2. **Claim freeze**:
    - Bankster begins a database transaction.
    - Bankster puts a database lock on the `DepositAccount` object.
3. **Payment calculation**:
    - Bankster sums the `amount`s of all existing `DepositClaim`s that have the same payer as the one being processed.
    - Bankster subtracts that value from the amount of funds available in the deposit.
    - If the result is negative or zero, Bankster removes the `DepositClaim` object being processed.
    - Otherwise if the result is lower than `DepositAccount.amount`, Bankster sets this field to the amount that's actually available.
4. **Transaction**:
    - If the `DepositClaim` still exists at this point:
        - Bankster uses SCI to create an Ethereum transaction.
        - Bankster puts transaction ID in `DepositClaim.tx_hash`.
    - This part must be done while the `DepositAccount` is still locked to prevent two simultaneous operations from independently making two separate payments for the same claim.
6. **Unfreeze and result**: If everything goes well, the operation returns.
    - Bankster commits the database transaction.
        Database locks on `DepositAccount`s are released.
    - Bankster returns `DepositClaim.tx_hash` if a transaction has been created.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/161280988
