### ISSUE TITLE
Bankster: `discard claim` operation

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#897]
This is a part of the implementation of the "Bankster" blueprint (#479).

Requires #894 to be implemented first.

1. **Implement `discard claim` operation**
2. **Use the new operation in Concent Core**
    - This operation is only possible if the payment has not been finalized. If it has, the claim stays in the database until Bankster determines whether the corresponding Ethereum transaction has succeeded.
    - Concent Core performs this operation for all `DepositClaims` created in a use case for which payment is not necessary. This is the case for example if it's determined that the provider has not computed the subtask correctly or when the use case times out. Currently those use cases are `ForcedAcceptance` and `AdditionalVerification`.
    - `ForcedPayment` use case operates on more than one subtask and for that reason requires a separate operation.

##### Input
| Parameter                     | Type                              | Optional | Remarks                                                                                                                 |
|-------------------------------|-----------------------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `deposit_claim`               | `DepositClaim`                    | no       | The claim to discard.

##### Output
| Parameter                     | Type                              | Optional | Remarks                                                                                                                 |
|-------------------------------|-----------------------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `claim_removed`               | bool                              | no       | `True` if the claim has actually been removed.

##### Sequence of operation
1. **Claim freeze**:
    - Bankster begins a database transaction.
    - Bankster puts a database lock on the `DepositAccount` object.
2. **Claim cancellation**:
    - If `DepositClaim.tx_hash` not empty:
        - Bankster simply removes the `DepositClaim` object from the database.
        - `claim_removed` is `True`.
    - Otherwise
        - `claim_removed` is `False`.
3. **Unfreeze and result**: If everything goes well, the operation returns.
    - Bankster commits the database transaction.
        Database locks on `DepositAccount`s are released.
    - Bankster returns `claim_removed`.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161281188
