### ISSUE TITLE
Bankster: `settle overdue acceptances` operation changes

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#898]
This is a part of the implementation of the "Bankster" blueprint (#479).

Requires #894 and https://github.com/golemfactory/concent/issues/565 to be implemented first.

There should be some updates in the current implementation of `settle overdue acceptances` operation in Bankster to allow it to follow deposit state.

##### Input - add following parameters:
| Parameter                       | Type                        | Optional | Remarks                                                                                                                 |
|---------------------------------|-----------------------------|----------|-------------------------------------------------------------------------------------------------------------------------|
| `requestor_public_key`          | string                      | no       | Public key of the requestor. Comes from `TaskToCompute`.
| `provider_public_key`           | string                      | no       | Public key of the provider. Comes from `TaskToCompute`.

##### Sequence of operation - modify current sequence:
1. **Initialization**:
    - Bankster creates `Client` and `DepositAccount` objects for the requestor if they don't exist yet.
        - The transaction is committed at this point to prevent these objects from being rolled back in case of failure.
2. **Deposit query** (This should be already done, but please review and confirm):
    - Bankster asks SCI about the amount of funds available in requestor's deposit.
3. **Claim freeze**:
    - Bankster begins a database transaction.
    - Bankster puts a database lock on the `DepositAccount` object.
4. **Requestor's spare deposit check** (This is partially done, so please apply only necessary updates):
    - Bankster sums the `amount`s of all existing `DepositClaim`s where the requestor is the payer.
    - If the existing claims against requestor's deposit are greater or equal to his current deposit, we can't add a new claim.
        - Bankster responds with `claim_against_requestor` being `None`.
    - Otherwise Bankster continues.
5. **Claim calculation** (This should be already done, but please review and confirm):
    - Bankster sums up the amount specified in acceptances.
    - Bankster asks SCI for the list of all relevant payments listed on the blockchain (both normal payments performed by the requestor and forced payments performed by Concent).
    - Bankster computes the amount that is still owed to the provider.
    - Bankster compares the amount with the available deposit minus the existing claims against requestor's account.
        - If the whole amount can't be paid, Concent lowers it to pay as much as possible.
        - The final amount must be non-zero - spare deposit check prevents this.
6. **Transaction** (This should be already done, but please review and confirm):
    - Bankster uses SCI to create an Ethereum transaction.
7. **Deposit lock**:
    - Bankster creates a `DepositClaim` object
        - `subtask` is empty since the claim may refer to multiple subtasks.
        - `amount`: The amount actually used in the transaction.
8. **Unfreeze and result**: If everything goes well, the operation returns (Replace currently returned results).
    - The created `DepositClaim` is included in the result.
    - Bankster commits the database transaction.
        Database locks on `DepositAccount`s are released.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161281255

**Comment by cameel** [comment]
Step 7 updated in the blueprint (#479):
> 7. **Deposit lock**:
>     - Bankster creates a `DepositClaim` object
>         - `subtask` is empty since the claim may refer to multiple subtasks.
>         - `amount`: The amount actually used in the transaction.
>         - `tx_hash`: Transaction ID of the newly created transaction.

Originally it did not mention `tx_hash`.
