### ISSUE TITLE
Bankster: Blockchain event subscriptions

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#899]
This is a part of the implementation of the "Bankster" blueprint (#479).

Requires #894 to be implemented first.

1. **Implement `remove_claim` function**
2. **Register `remove_claim` function to SCI subscription handler**

##### Sequence of operation
The assumption here is that the event is only reported when a transaction has been successfully included in the blockchain and has enough confirmations to make its reversal very unlikely.

1. **Claim identification**:
    - Bankster begins a database transaction.
    - Bankster checks if `DepositClaim` with `tx_hash` reported in the event exists in the database.
        - If it does not, the handler ends.
        - If it does, the handler locks it (to prevent it from being modified between this step and the next).
2. **Claim freeze**:
    - Bankster locks the `DepositAccount` object associated with the claim.
3. **Claim removal**:
    - Bankster removes the `DepositClaim` object.
4. **Unfreeze**:
    - Bankster commits the database transaction.
        Database locks on `DepositAccount`s are released.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161281432

**Comment by cameel** [comment]
@rwrzesien Have you checked this assumption?

> The assumption here is that the event is only reported when a transaction has been successfully included in the blockchain and has enough confirmations to make its reversal very unlikely.

I'm not 100% sure when the event gets reported by SCI so I added this bit to ensure that we don't forget about this detail.

**Comment by cameel** [comment]
@rwrzesien What about my question?

**Comment by rwrzesien** [comment]
@cameel No, I didn't check, I thought it was known when the blueprint was created.

**Comment by pawelkisielewicz** [comment]
There was small problem, it is tested and fixed in https://github.com/golemfactory/concent/pull/967

**Comment by pawelkisielewicz** [comment]
This event is reported when transaction is successful in blockchain. It was tested manually and the assumption is true.

**Comment by cameel** [comment]
OK. I've checked in SCI sources and it does report only after `SCIImplementation.REQUIRED_CONFS` blocks.

BTW, the functions that return lists of transactions do not have this check they always take the first and last block to search. When using those we must remember to subtract that number ourselves.
