### ISSUE TITLE
End-to-end tests for multiple golem-messages routing

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#925]
There should be some end-to-end tests for testing how Concent network handles multiple golem-messages versions.

As it is client's resposibility to provide correct golem-messages version, the test needs to know it. The Concent instances should be named in the test, and for each of them there should parameter with their golem-messages version, ie:
```
> test-golem-messages-version.sh --concent_1_version=2.15.0 --concent_2_version=2.15.1 ...
```

Off course they will run under the same host, as we will be testing messages routing.

What we will be really testing is how Concent's view decorators reacts to HTTP header `HTTP_CONCENT_GOLEM_MESSAGES_VERSION`, so it doesn't matter which golem-messages message will be used. For simplicity, it should be the one that will change most unlikely, like `Ping` message.

The response for message which is not handled by Concent is `Http400` with error code `ErrorCode.MESSAGE_UNKNOWN`, so this response should be threated as correct. It means that a right version of Concent, handling the same version of golem-messages as in the header, got the request. Otherwise it would be `Http200` with message `ServiceRefused`. It would also have `reason` set to `UNSUPPORTED_PROTOCOL_VERSION` after https://github.com/golemfactory/golem-messages/issues/275 is implemented.

Tools and utils from `api_testing_common` should be reused if possible.

Possible test scenarios proposals:
1. Test if number of requests equal to known Concent instances with different golem-messages versions will be handled correctly.
- Create requests for each golem-messages version supported in the network.
- Check if response is `Http400` with error code `ErrorCode.MESSAGE_UNKNOWN`.

2. Test if unsupported golem-messages version will be handled correctly.
- Create request for several golem-messages versions not supported in the network.
- Check if response is `Http200` with message `ServiceRefused`.

3. Corner-cases of each of the above. 
- There are some corner rules on which version is treated as support or not. The corner-cases of those should be tested for both support and not-support
- The rules are defined here https://github.com/golemfactory/concent/issues/915

4. `Mayhem` scenario.
- Create a lot of requests with either supported or unsupported version. Send those requests in pseudo-random order.
- Test if each response is correct.
----------------------------------
# EDIT
After discussion, we have come to conclusion that all we need are simple ("sanity") tests that would check how `nginx-router` behaves.
Four scenarios have been identified:
1. _A request with `latest` version of `Golem Messages` is received._
**Expected**: `nginx-router` will forward it to the cluster with the latest version deployed; user will receive `Http400` with error code `ErrorCode.MESSAGE_UNKNOWN`
2. _A request with `latest - 1` version of `Golem Messages` is received._
**Expected**: `nginx-router` will forward it to the cluster with the previous latest version deployed; user will receive `Http400` with error code `ErrorCode.MESSAGE_UNKNOWN`
3. _A request with unsupported protocol version is received._
**Expected**: `nginx-router` will respond with `Http404`.
4. _A request with malformed header (`Golem Messages` version has a wrong, non-semver format) is received._
**Expected**:  `ngingx-router` will respond with `Http400` with error code `"bad-request"`

I would be good if script, during setup , could determine versions automatically. If it is not possible or to time consuming to implement, let versions be provided as command line parameters. In such case, provide support for short and long naming, ie:
```
> test-golem-messages-version.sh --concent_1_version=2.15.0 --concent_2_version=2.15.1 ...
```

```
> test-golem-messages-version.sh -v1=2.15.0 -v2=2.15.1 ...
```

**Comment by dybi** [comment]
In 1.
> Check if response is `Http200` with message `ServiceRefused`.

I think it should be `Http400` with error code `ErrorCode.MESSAGE_UNKNOWN`.

In 2. 
> Check if response is `Http400` with error code `ErrorCode.MESSAGE_UNKNOWN`.

I think it should be `Http200` with message `ServiceRefused`.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161745792

**Comment by rwrzesien** [comment]
@dybi Right, fixed.

**Comment by Jakub89** [comment]
> For simplicity, it should be the one that will change most unlikely, like `Ping` message.

Shouldn't we also check database in this tests? I would argue that `receive` view is the one that can cause the most bugs. Or maybe we could extend existing e2e tests with some flag for testing on two different golem-messages version?

**Comment by dybi** [comment]
@Jakub89 - as discussed offline, it should be ok

**Comment by Jakub89** [comment]
Running this test like this:

>test-golem-messages-version.sh --concent_1_version=2.15.0 --concent_2_version=2.15.1

would test the same version, because on production `load-balancer` doesn't care about golem-messages patch versions. Sending `v2.15.0` messages to concent that work with `v2.15.2` should work just fine, and the response golem-messages version from concent is `2.15.2'.
So I would suggest to run this test like this:
```
./api-e2e-cluster-multiple-golem-messages-routing.py http://devel.concent.golem.network -c1 2.15.0 -c2 2.14.0
```
