### ISSUE TITLE
Prevent transaction nesting when using @atomic

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#937]
When we create transactions with `atomic()`, we usually rely on the fact that exiting the block commits the transaction. Only an actual commit releases locks and reveals `IntegrityErrors` caused by attempts to create two identical records in parallel.

Unfortunately one of the features provided by Django is that a call to `atomic()` when there's already a transaction in progress creates a savepoint. When such a nested `atomic()` block exits, the savepoint is simply removed and there is no commit. This ensures atomicity of the outer transaction but at the cost of making the nested one non-durable.

For that reason we want to avoid nesting transactions. It is however easy to nest transactions by mistake without realizing it when they're hidden in helper functions. The goal of this task is to implement a wrapper over `atomic()` (let's call it `non_nesting_atomic()`) that raises an exception if there's already a transaction in progress and calls `atomic()` only if there isn't. You can check that with `get_connection(using).in_atomic_block`.

After implementing it, replace all uses of `atomic()` in our code with the wrapper and run tests. It it uncovers any cases of undesirable nesting, fix them by reorganizing the code.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162008119

**Comment by cameel** [comment]
@rwrzesien noticed that `non_nesting_atomic()` does not work in unit tests because they use transactions to clean the database. We could switch to `TransactionTestCase` as a base class but that would make our tests about 8 times slower. We don't want that.

As a workaround my suggestion is to add a setting called `DETECT_NESTED_TRANSACTIONS`. `non_nesting_atomic()` should allow nesting if this setting is `False`. Set it to `False` in `settings/testing.py` and to `True` in `settings/base.py`. This way we won't be able to detect nesting when running unit tests (which would be really useful) but we'll still catch it in end-to-end tests and on the cluster. That's better than nothing because nesting is really hard to notice and the code breaks silently.
