### ISSUE TITLE
Unmock get_file_status function

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#95]
Currently our tests mock whole get_file_status. This was quick solution before release, but it is not ok in long term because we don't know if that function is really working. The mock should be only added for requests HEAD call to gatekeeper.

Also, please add tests for different responses from HEAD requests call to gatekeeper.

**Comment by cameel** [comment]
This is already done, right?

**Comment by rwrzesien** [comment]
@cameel Yes, we are using real call to what is defined as STORAGE_CLUSTER_ADDRESS.
