### ISSUE TITLE
Concent should answer DuplicateRequest if subtask in current or future state

### ISSUE THREAD

**Issue by pawelkisielewicz** [golemfactory/concent#951]
Currently in message handlers there is validated that ServiceRefused is returned only when subtask state in database is the same as "state in message". Eg. `ForceGetTaskResult` changes state to `FORCING RESULT TRANSFER` and there is currently validated, that if client sends `ForceGetTaskResult` and subtask is in state `FORCING RESULT TRANSFER` concent responses with `DuplicateRequest`. 
Concent should also answer with `DuplicateRequest` if subtask is in any on future states. If client sends  `ForceGetTaskResult` and concent is in `FORCING ACCEPTANCE` concent should also response with  `DuplicateRequest`. It should be added.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/162116452
