### ISSUE TITLE
Remove all positional arguments in `./signing_service.sh`  and replace them with keywords.

### ISSUE THREAD

**Issue by Jakub89** [golemfactory/concent#953]
`./signing_service.sh "85cZzVjahnRpUBwm0zlNnqTdYom1LF1P1WNShLg17cmhN2UssnPrCjHKTi5susO3wrr/q07eswumbL82b4HgOw==" "127.0.0.1"` cause error because position arguments are reverse. Changing to keywords arguments will make it easier to use for random people trying to deploy Signing Service.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162127921

**Comment by cameel** [comment]
@Jakub89 This task changes Signing Service parameters in non-backwards compatible way. Before merging it you should talk with @bartoszbetka about how it will be deployed. Our README with instructions needs to be updated, our Docker files need to be changed and a new package with Signing Service needs to be built and distributed.

**Comment by PaweuB** [comment]
@cameel Would You provide an Issue for actions that is important to manage with in deployment?

**Comment by kbeker** [comment]
Issue is already closed
