### ISSUE TITLE
Fix timings in API tests

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#962]
Right now API tests are using "some values" for protocol constants: values from concent's end point should be used.

**Comment by PaweuB** [comment]
This Issue should depend on https://github.com/golemfactory/concent/issues/828

Problem is in UC4, especially in test  `api-e2e-additional-verification-test.py` in function `test_case_3_test_for_invalid_time`. 
Should use protocol constans like in `api-e2e-force-accept-or-reject-results-test.py`

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162197271
