### ISSUE TITLE
One of the force payment e2e tests checks payments too far in the past

### ISSUE THREAD

**Issue by PaweuB** [golemfactory/concent#965]
This test checks payment too far in the past. This test will fail every time it will be started sooner than 12h from last run. 

Test is in `./api-e2e-force-payment.py` and called `test_case_2d_send_correct_force_payment()`

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162197245

**Comment by dybi** [comment]
Not a bug
