### ISSUE TITLE
API E2E test cleanup

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#968]
Our e2e test need some tweaking - there is some redundancy, wrong type annotations, unused code, etc.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/162196327

**Comment by cameel** [comment]
Looks more like cleanup than an upgrade. As is the task is too broad in my opinion. Could you list specific stuff that needs to be fixed?

**Comment by dybi** [comment]
For the moment, (except for @kbeker  tasks: #744 and #970) no more improvemnts are being planned at the moment - we can close this.
