### ISSUE TITLE
Fix discard_claim operation error handling

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#974]
Currently `discard_claim` operation has some misplaced exception catching. The code looks like:

```
 DepositAccount.objects.select_for_update().get(
            pk=deposit_claim.payer_deposit_account_id
        )

        if deposit_claim.tx_hash is None:
            claim_removed = False
        else:
            try:
                deposit_claim.delete()
                claim_removed = True
            except DepositAccount.DoesNotExist:
                claim_removed = False
```

1. `DepositAccount.objects.select_for_update().get()` is the method which raises `DoesNotExist` exception, so it should be wrapped in `try/except`.
2. `delete()` does not raise that exception, so it shouldn't be wrapped in catching it.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/162205946
