### ISSUE TITLE
The case with no payments from the requestor is not handled in the forced payment use case

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#980]
Originally reported in https://github.com/golemfactory/concent/pull/975#discussion_r236651316

The current code does not handle the case where the list of payments from the requestor found on the blockchain is empty.

https://github.com/golemfactory/concent/blob/e90c59c971a0e5c48e0529c586a4e8db1cae557d/concent_api/core/payments/bankster.py#L357-L370

Here's what Łukasz's spec says:

> Usługa Concent tworzy listę transakcji LT składającą się z listy transakcji płatności wykonanych przez Requestora, dla których podany w nich stempel czasu jest nie starszy niż T0. Lista może być pusta. (patrz punkt 4).

> Usługa Concent określa wartości V jako różnica sumy zobowiązań płatności z listy LAR oraz sumy przelewów na konto Ethereum EA z listy transakcji LT i sumy wymuszonych płatności LF.

Obviously if there were no payments from the requestor, Concent should charge him with the full cost of all subtasks for which provider has submitted acceptances (minus the amount covered by forced payments made by Concent if any).

So V = sum(LAR) - sum(LT) - sum(LF). If any of the lists is empty, the corresponding sum should be treated as zero.

Please make sure that in all cases where it's possible for one of these lists to be empty, the code works correctly.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162241739
