### ISSUE TITLE
Concent responds with ForcePaymentRejected if there was a payment after one of the acceptances

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#983]
Originally reported in https://github.com/golemfactory/concent/pull/975#discussion_r236654251.

In the current implementation Concent responds with `ForcePaymentRejected` in use case 5 if not all payments found on the blockchain were made before the first submitted acceptance.

In other words, a situation like this provider's request will be rejected because there was a payment made after the first SRA:
```
     -100 GNT    1 GNT         -100 GNT
       |         |               |
------SRA-------PAY-------------SRA------> [time]
       |         |
       T0        T1
```
_T0 is the timestamp of the oldest acceptance._
_T1 is the timestamp of the youngest payment._

The expected outcome in this situation is for Concent to pay the provider 199 GNT from requestor's deposit.

The code that does this is in `settle_overdue_acceptances()`:
https://github.com/golemfactory/concent/blob/e90c59c971a0e5c48e0529c586a4e8db1cae557d/concent_api/core/payments/bankster.py#L365-L389

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162265003

**Comment by Jakub89** [comment]
@cameel from what I understand, this bug comes down to delete one of our validations:
``` python
# Concent checks if all passed SubtaskResultAccepted messages from subtask_results_accepted_list
# have payment_ts < T1
if any(
    youngest_transaction_timestamp > subtask_results_accepted.payment_ts
    for subtask_results_accepted in acceptances
):
    raise BanksterTimestampError
```
Should it be replace with something else?

**Comment by cameel** [comment]
I think you can just remove it as long as all the unit tests pass. Please be sure to add a test for the situation from the description and any others you can think of.
