### ISSUE TITLE
Concent should reject force payment request if it includes acceptances from before the last settlement

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#984]
As described in #982, there are two types of forced payments. The one that Concent does in use case 5 settles everything done before it, even if it does not cover all the claims.

Currently Concent does not check when was the last time such a forced payment was made. Concent should find the last such payment and if it exists, compare its `closure_time` with the oldest `payment_ts` in submitted acceptances. If the's an acceptance older than the closure time, it should reject provider's request.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162264942

**Comment by rwrzesien** [comment]
@cameel 

> Concent should find the last such payment and if it exists

How can this be achieved? If this should be taken from result of call of `get_forced_subtask_payments`, then this can be done this way, because elements returned from `get_forced_subtask_payments` doesn't have `closure_time` attribute.

**Comment by cameel** [comment]
Please see the description of #982 I mentioned above. There are two types of forced payments and each has separate functions that create and list them. The one you need here is `get_forced_payments()`.

**Comment by rwrzesien** [comment]
@cameel In #982 I have replaced usage of `get_forced_payments` to `get_forced_subtask_payments` for the `TransactionType.FORCE` in `get_list_of_payments()` call. As I understand it is correct?

So that new call should happen in Bankster too, but before getting list of forced and batch transactions?

**Comment by cameel** [comment]
Yes. It's one of the checks before doing the calculations but since it needs information from the blockchain, it must be inside Bankster. You can define a new exception class to report it.

You need to look for any settlement payments (I'm going to start calling forced payments returned by `get_forced_payments()` _settlement payments_ from now on to make it clearer which ones I mean) that are after the earliest submitted acceptance. If there are any, refuse to run the algorithm and return `TimestampError`.

**Comment by PaweuB** [comment]
test

**Comment by cameel** [comment]
Update: After discussion with Łukasz it turned out that the acceptances from before the last settlement should be allowed after all. That's because the list of forced payments we take into account is supposed to contain settlement payments, not forced subtask payments.
