### ISSUE TITLE
`test_force_payment_commited` from golem's concent acceptance tests is failing

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#998]
to reproduce:
`pytest scripts/concent_acceptance_tests/force_payment/test_payment.py::RequestorDoesntPayTestCase::test_force_payment_commited` on branch `chore-update-concent-acceptance-test-after-sra-update` (GM v2.17.0)

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162449483

**Comment by dybi** [comment]
closing  as expected behaviour in the test was incorrect - test has been updated
